### ISSUE TITLE
About that Auto Generating repair issue

### ISSUE THREAD

**Issue by Vladmirangel** [peterhaneve/ONIMods#10]
So, i Posted a couple of stuff in steam comments, but i guess i didn't get the memo of posting it here. So i will just copy paste what i wrote in steam right below vVv
__________________________
dunno when this mod was updated, but in my case when i posted my other comment Sep 25, ladders and pipes were affected by the incorrectly generating repair errands. Let me check if they are still affected testing my save

_______________________________________

Well, here's some news. Here are my screenshots
http://prntscr.com/pblbxl 
http://prntscr.com/pblckk 

So it seems the one tile stuff is still affected

I also checked some of the Multi-tile buildings if they are affected by the bug.
some of the buildings are cleared off the bug like the Rock Crusher, Textile Loom, Exosuit Forge, Manual Generator Etc.

though some of the buildings still experience the bug, Jumbo Battery, Research Station, Super Computer, Etc

never bothered to test all buildings though.

______________________________________________________

well, i forgot to mention, but my game is heavily modded. don't know if that affects anything.

**Comment by peterhaneve** [comment]
I cannot reproduce the issue - it is possible that Steam has not updated your version of the mod yet. Try unsubscribing and resubscribing from the mod.

If you have the latest version, it should not be possible to enable auto-repair when already enabled (no popup message will appear).
