### ISSUE TITLE
Dupes ignoring permissions with airlocks

### ISSUE THREAD

**Issue by Random-Factor** [peterhaneve/ONIMods#100]
Dupes are still passing through airlock while permissions should deny them.

## Expected Behavior

Global permissions should prevent dupes from passing through
## Current Behavior

Dupes can still use airlock
## Mod Versions

Steam version from 1/13
## Steps to Reproduce

1.
2.
3.
4.

**Comment by peterhaneve** [comment]
I cannot reproduce this issue. Please attach an output log to issues, it really makes it easier to diagnose potential problems (especially mod conflicts) that are unreproducible for the author.

**Comment by peterhaneve** [comment]
After noticing that the issue was reported in *vanilla*, I switched back to vanilla to test and was able to fix the problem. Thank you for reporting!
