### ISSUE TITLE
Airlock entombed Dups (Spaced Out)

### ISSUE THREAD

**Issue by jglassmaker** [peterhaneve/ONIMods#106]
Airlock mod causes Dups to become entombed while still fully powered with the Spaced Out DLC enabled. The Airlock can work flawlessly for many cycles and then suddenly start causing entombed Dups. A small (moppable) amount of liquid on one side can sometimes trigger (note: when it happens a visual glitch in the top-center tile happens).

## Expected Behavior
Dups pass through Airlock without becoming entombed.

## Current Behavior
Dups become entombed - often when one side has liquid touching the Airlock.

## Mod Versions
Latest stream version, fresh copy of ONI w/ Spaced Out DLC enabled.

## Steps to Reproduce
Do not have a easily reproducible processes yet.

## Output Log
Will include once I can get a clean one.

**Comment by BallisticBuddha** [comment]
I was about to submit this bug report myself, but was still running tests and gathering result by the time I saw this got posted. This been happening constantly with only specific airlock doors in my colony and this only started after installing today's (January 28th) update to the Spaced Out DLC.**

From my testing so far, this seems to happen when a dupe is performing an errand that is so close to the airlock door that they perform the errand from _inside_ the door. For instance, if I put a storage bin just behind the door and a dupe goes in the room, but because the bin is so close, they are standing inside the door while taking/placing the item into the storage bin, they become entombed on their way out after performing the errand.

**Comment by BallisticBuddha** [comment]
Just ran a few more tests and can confirm that I can reliably reproduce this issue when having a duplicant perform an errand from inside the door. I just tried adding a deconstruction errand for some objects directly above the door, and they were consistently getting entombed when interacting with a nearby object 

I have attached my [Player.log](https://github.com/peterhaneve/ONIMods/files/5891931/Player.log) file. This was last saved immediately after incurring an entombment. There were no immediate log messages that showed up after the event, but it might help anyway.

What's also interesting about this is how, as you can see from the screenshot below, other duplicants can be passing through the door at the same time as the errand performing dupe, and will become "stuck" in the middle of the door, yet are not counted as entombed, only the errand performing dupe will become entombed.

![20210129010836_1](https://user-images.githubusercontent.com/711464/106239971-7b529180-61d1-11eb-8831-3ddccac5d343.jpg)

ONI build: EX1 56-559549
AirlockDoor version: 2.1.0.0

**Comment by jglassmaker** [comment]
@BallisticBuddha thank you for helping report on this issue! I wasn't sure yet how to reproduce but can confirm your steps. Hopefully we can get a fix for this soon but for now we can try to avoid it.

**Comment by peterhaneve** [comment]
Thank you for the report. Klei rewrote the falling and entombment monitor for Duplicants in last week's patch due to the recent issues with Duplicants floating in midair, which means that substantial changes to Airlock Door are necessary that might take quite a while to implement.

**Comment by LokeYourLord** [comment]
I'm facing the same issue, and many others are as well. I hope you can solve this in the near future because this is the only mod which adds a proper Airlock.

**Comment by peterhaneve** [comment]
This door bug is a bug in the DLC itself, and can occur on regular doors too:
![image](https://user-images.githubusercontent.com/29011570/107321711-e2850700-6a57-11eb-9215-e1500fb95a9d.png)
Nevertheless, version 2.2 contains a patch to the stock game that should resolve most instances of the bug. Please file a bug report on the Klei forums as this issue affects the default Airlock too!
