### ISSUE TITLE
Error with queue - NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by UlyanaLeyana** [peterhaneve/ONIMods#109]
## Expected Behavior

No game crash :) 
I don't have DLC.
## Current Behavior

NullReferenceException: Object reference not set to an instance of an object

PeterHan.QueueForSinks.SinkCheckpoint.MustStop (UnityEngine.GameObject reactor, System.Single direction) (at <4d42d3036e084336bcd9977909bf15a8>:0)
PeterHan.QueueForSinks.WorkCheckpoint`1+WorkCheckpointReactable[T].MustStop (UnityEngine.GameObject dupe, System.Single x) (at <4d42d3036e084336bcd9977909bf15a8>:0)
PeterHan.QueueForSinks.WorkCheckpoint`1+WorkCheckpointReactable[T].Update (System.Single dt) (at <4d42d3036e084336bcd9977909bf15a8>:0)
ReactionMonitor.<InitializeStates>b__4_2 (ReactionMonitor+Instance smi, System.Single dt) (at <a3eeae10f2404a1aa48270ce575d8be6>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <dc03b2a8a27f4f14b129057ddebff48a>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <dc03b2a8a27f4f14b129057ddebff48a>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <dc03b2a8a27f4f14b129057ddebff48a>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <dc03b2a8a27f4f14b129057ddebff48a>:0)
Game.SimEveryTick (System.Single dt) (at <a3eeae10f2404a1aa48270ce575d8be6>:0)
Game.Update () (at <a3eeae10f2404a1aa48270ce575d8be6>:0)

## Mod Versions

Steam subscription. Version 2.6.0.0. Updated by Mod Manager.
## Steps to Reproduce

1. I don't know how to reproduce, Got error while was busy with building.

## Output Log

https://www.mediafire.com/file/zvo11pwo7s5qm35/Player_%2523109.log/file

**Comment by peterhaneve** [comment]
This issue should be fixed by bdbfc4f.
