### ISSUE TITLE
does not work with latest patch

### ISSUE THREAD

**Issue by eihns** [peterhaneve/ONIMods#11]
Hey, maybe you didnt notice, but it this mod doenst work with latest patch. There is some error about cant access, only when enabling this mod. If oyu need more details let me know.

**Comment by peterhaneve** [comment]
Steam is serving you an outdated version of Fast Save. Try clearing the mod cache as documented in https://github.com/peterhaneve/ONIMods/blob/master/Docs/clearmodcache.md. The folder for Fast Save on Steam is **1867707267**.

**Comment by eihns** [comment]
Nope, i deleted all, all mods got "redownloaded?" game restartet. I then checked your mod, need to restart, and same error. see picture.
<img width="879" alt="nope" src="https://user-images.githubusercontent.com/43281991/66217702-16b02100-e6c8-11e9-9282-9b9d6dbc3ae9.png">

**Comment by eihns** [comment]
Also your mods shows as red in the list, but i dont really know why.

**Comment by peterhaneve** [comment]
If Fast Save is still being downloaded as an old version, you can try a [local install](https://github.com/peterhaneve/ONIMods#local-downloads).
