### ISSUE TITLE
Chane the Config Path of PLib/PLibOptions

### ISSUE THREAD

**Issue by wansyu** [peterhaneve/ONIMods#110]
I want to change the path of configuration file so that modder can update the mod without overwriting the config.json of user.
Here is the Code that I modified:
```
//POptions.cs
		private static string GetConfigPath(ConfigFileAttribute attr, Assembly modAssembly) {
			return Path.Combine(GetConfigFolderPath(modAssembly), attr?.ConfigFileName ??
				CONFIG_FILE_NAME);
		}
		public static string GetConfigFolderPath(Assembly modAssembly)
		{
			var Location = GetModBaseDir(modAssembly ?? Assembly.GetExecutingAssembly());
			string directoryName = Path.GetDirectoryName(Location);
			if (directoryName == null)
			{
				throw new DirectoryNotFoundException("Can't find root directory for config.json");

			}
			var _modsFolder = new FileInfo(directoryName).Directory.Parent.FullName;
			string text = Path.Combine(_modsFolder, "config");
			if (!Directory.Exists(text))
			{
				Directory.CreateDirectory(text);
			}
			var _modConfigFolder = Path.Combine(text, new FileInfo(directoryName).Name);
			if (!Directory.Exists(_modConfigFolder))
			{
				Directory.CreateDirectory(_modConfigFolder);
			}
			return _modConfigFolder;
		}

```
Then I recompile the PLibOptions.dll, and use it on my project.
## Expected Behavior
ModBaseDir is MyMod_Dev for example, the config.json should be stored in the path:
_\~\\OxygenNotIncluded\\mods\\config\\MyMod_Dev\\_
Test in Spaced Out! DLC installed Version 449460.

## Current Behavior
Act as default, the config.json is stored in the path:
_\~\\OxygenNotIncluded\\mods\\dev\\MyMod_Dev\\_

## Mod Versions
PLibOptions 3.9.0.0(commit id 56053e5)

## Steps to Reproduce

1. Modified the code of PLibOptions;
2. Compile PLibOptions and replace the original one of another mod project;
3. Compile mod project and move them to _\~\\OxygenNotIncluded\\mods\\dev\\MyMod_Dev\\_;
4. Run the Game and change the Option then find out the path of config.json.

**Comment by wansyu** [comment]
I modified the "internal ModOptionsHandler(Mod mod)" method and orther path relative to config then PLibOptions works as desired, but PLib is not.

**Comment by peterhaneve** [comment]
PLib uses *forwarding* to share code between mods and improve performance, which means that changing the configuration path handling code may not work as expected. In general, storing configurations outside of the mod folder has been frowned upon since the configuration is not removed when the mod is uninstalled. However, a new feature is pending to allow a persistent mod configuration storage in a very similar location. Check back closer to DLC release!
