### ISSUE TITLE
How to use AddTech() without new PBuilding()?

### ISSUE THREAD

**Issue by tomoya92** [peterhaneve/ONIMods#111]
I want to build once to support vanllia and dlc. but I wan't to use PBuilding class to create a new build. What should i do, please.

**Comment by peterhaneve** [comment]
PLib does not currently support using `AddTech` outside of `PBuilding`. This is a commonly requested feature, which may yet be added to PLib. However, new PLib features are unlikely with the DLC being changed so often. Check back closer to DLC release as the game is stabilized!

**Comment by peterhaneve** [comment]
This issue has been fixed in 45e4884. The new API you will want to use is `PBuilding.AddExistingBuildingToTech`.

**Comment by tomoya92** [comment]
thank you very much!
