### ISSUE TITLE
Moo Reproduction Mod Crashing Game and Uninstalling Renders Critter Drop Off Unusable

### ISSUE THREAD

**Issue by jacobhutchinson** [peterhaneve/ONIMods#112]
I started the game with the mod enabled, it worked for about 20 cycles before it crashed. Now it doesn't get more than one cycle before crashing, even when re-enabling it on a later cycle. The output error that caused the crash said this mod was responsible. I uninstalled it, but then, every time I click on the critter drop off the game crashes. For the record, I have no gassy moos yet and am on the first planetoid still. It is 100% reproducible on my end. If the mod is enabled, the game crashes in less than one cycle and I can click on the critter drop off and use it normally. If it is disabled, I can run the game with absolutely zero crashes, unless I click on the critter drop off. Now, I must enable the mod to place or use a critter drop off and then disable it before it crashes my game. Basically, my game is borked for any ranching until this issue is resolved. Also, I have a host of other mods installed, not sure if there is any interaction between them that I am not seeing, or if maybe I must change the ordering of the mods. I have not experimented much with either.

## Expected Behavior
The moo reproduction mod should not crash the game, nor cause the game to crash when clicking on the critter drop off after uninstalling the mod.

I am using the Spaced Out DLC.

## Current Behavior
The moo reproduction mod DOES crash the game and cause the game to crash when clicking on the critter drop off after uninstalling the mod.

## Mod Versions
I am using the must up to date version, updated via a mod updater.

## Steps to Reproduce
1. Install the mod
2. Wait until it crashes
3. Disable mod, which leads to no crashing
4. Click on the critter drop off and crash anyways.

## Output Log

Here is a link to the output log: https://www.dropbox.com/s/q0kyzz0h7ddyzdy/Player-prev.log?dl=0

**Comment by jacobhutchinson** [comment]
Another possible piece of the puzzle: When the game crashes after disabling the mod, it blames the 'Better Info Cards' mod for the crash (by highlighting it in red and disabling it), even though disabling that mod does not make the critter drop off clickable without crashing, but enabling Moo Reproduction does. Not that this bug wasn't confusing enough before, but thought this might help.

**Comment by peterhaneve** [comment]
It turns out that the issue was a race condition that does not occur with all configurations of Gassy Moos and is sensitive to the exact timing of a Moo's death. It should be fixed in ff30ab1.
