### ISSUE TITLE
OPTIONS_ONLY doesn't work with archived version

### ISSUE THREAD

**Issue by Truinto** [peterhaneve/ONIMods#113]
https://github.com/peterhaneve/ONIMods/blob/9d978178b76d6ef91d43f0a724af9e69f0b79c74/PLib/Options/POptions.cs#L271
should be
`var id = Path.GetFileName(GetModBaseDir(assembly));`
so it works with archived version. You already fixed that for the non OPTIONS_ONLY version at line 294.

**Comment by peterhaneve** [comment]
This issue should be fixed in d7d9ce5.
