### ISSUE TITLE
Blueprints crash

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [peterhaneve/ONIMods#114]
## Expected Behavior
It shouldn't crash
I have the latest DLC installed and running

## Current Behavior

IndexOutOfRangeException: Index was outside the bounds of the array.

Grid+ObjectLayerIndexer.get_Item (System.Int32 cell, System.Int32 layer) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Grid.cs:553)
Blueprints.TileVisual.Clean () (at <7a738cce296b43079653dabfdc8c6072>:0)
Blueprints.TileVisual.UpdateGrid (System.Int32 cell) (at <7a738cce296b43079653dabfdc8c6072>:0)
Blueprints.TileVisual..ctor (Blueprints.BuildingConfig buildingConfig, System.Int32 cell) (at <7a738cce296b43079653dabfdc8c6072>:0)
Blueprints.BlueprintsState.VisualizeBlueprint (Vector2I topLeft, Blueprints.Blueprint blueprint) (at <7a738cce296b43079653dabfdc8c6072>:0)
Blueprints.UseBlueprintTool.OnKeyDown (KButtonEvent buttonEvent) (at <7a738cce296b43079653dabfdc8c6072>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/PlayerController.cs:302)
KInputHandler.HandleKeyDown (KButtonEvent e) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:140)
KInputHandler.HandleKeyDown (KButtonEvent e) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:150)
KInputHandler.HandleEvent (KInputEvent e) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:127)
KInputController.Dispatch () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputController.cs:335)
KInputManager.Dispatch () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputManager.cs:63)
KInputManager.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/KInputManager.cs:52)
GameInputManager.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/input/GameInputManager.cs:62)
Global.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Global.cs:737)

## Mod Versions
steam subscription, DLL shows as version [2.3.360.35]

How do I do this?

## Steps to Reproduce
1. load game
2. have stored blue prints
3. have the DLC installed and running (might happen without it :[ )
4. try to scroll through the use blueprints option

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/6252656/Player.log)

**Comment by peterhaneve** [comment]
This repository is not the place to file issues with Blueprints, as it is written by 0Mayall, not me. The original Blueprints repository at https://github.com/0Mayall/ONIMods/ no longer appears to exist. Consider reporting the issue on the Klei forums under Mods and Tools, or on the unofficial Oxygen Not Included Discord server.
