### ISSUE TITLE
Not hiding pipes

### ISSUE THREAD

**Issue by LennyIndustries** [peterhaneve/ONIMods#116]
## Expected Behavior
With drywall hides pipes, the plate is expected to do this as wel.
Up to date steam version, no DLC.

## Current Behavior
It doesn't hide pipes.

## Mod Versions
Steam version, up to date using mod updater.

## Steps to Reproduce
1. install both mods
2. place pipe
3. place plate

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/6364652/Player.log)

**Comment by peterhaneve** [comment]
A change in how Sky compiles their mods ended up confusing the link code. This bug has been fixed in 1a63ae2.
