### ISSUE TITLE
The queue for sink mod only works with one sink

### ISSUE THREAD

**Issue by emipa606** [peterhaneve/ONIMods#12]
Even if you have multiple sinks, the dupes queue up for the first and ignore the rest.

**Comment by peterhaneve** [comment]
Dealing with all possibilities would cause a large performance impact. How close must another sink be to allow Duplicants to pass? How can we ensure that no other paths exist between the two sinks? What if it is broken, or out of water? If the first sink becomes available while Duplicants are in transit to the second one, should they go back?

If you use this mod, consider redesigning bathrooms to optimize exit paths. For example, try building sinks on both sides, or on multiple y-levels. Also consider fewer Duplicants per shift.

**Comment by emipa606** [comment]
The standard behaviour for dupes is to move on to the next available sink or just skip washing up if there are none available.
Why not just get them to queue if they find no sinks available? 
If possible, just look for another sink in the same room?

**Comment by peterhaneve** [comment]
Version 1.1 in eac2ec9 adds support for multiple sinks and scrubbers under very specific circumstances.
