### ISSUE TITLE
Doors entomb dupes

### ISSUE THREAD

**Issue by DanShu15** [peterhaneve/ONIMods#125]
Doors randomly lose the ability to charge themselves on load. They'll be saved charged and connected to the power network, but on load random doors will have an empty battery and still remain connected to the power network, but unable to charge their batteries.
## Expected Behavior

Upon load the doors that were fully charged should still be charged, and while connected to power they should be able to charge. The only solution seems to be deconstructing and reconstructing the doors.

I do own the DLC but this is in vanilla
## Current Behavior

Doors entomb the dupe inside of them upon loading. If the door cannot charge a dupe will still be able to enter them and will then be trapped and entombed. Normally a dupe cannot enter an airlock without any charge in it, but upon load it becomes possible if the doors didn't load their energy state properly.
## Mod Versions

Steam

I hadn't prior to this, but I confirmed that it's up to date with it and reloaded the game a few times to ensure the problem still persists
## Steps to Reproduce

1.  I can only assume it will reproduce if you start a sandbox game, build either a power supply or put in a cheat power, and build a block of several doors. Let them charge and then reload the game several times. I'm at cycle 450+, so it may present itself later in the playthrough
2. https://easyupload.io/h4o5oc I've uploaded my save game and mods folder to this link (7 day expiration timer) if that might be easier. There are currently several doors installed on a new farm block and a chlorine guyser I'm prepping for chlorine storage. Typically 2 to 5 of the doors will load unpowered and entomb the next dupe to enter them.
3. You stated on your steam page that you don't follow the comments, but this has been reported quite a few times in the past on there. There may be more information available there than I can provide

## Output Log

https://pastebin.com/BsTq9eyv

**Comment by DanShu15** [comment]
Ah interesting, mousing over a door experiencing the bug displays a total power available of 10.0 kj/10.0 kj
So while the meter displays empty the door is actually powered.
When I force a dupe to move through the doors they updated properly this time and nobody was entombed.
Try stacking the doors on top of eachother without a floor in between, that seems to trigger the bug more reliably than just reloading.
486 cycles and it's only happened on 2 doors. I'll upload a better save

**Comment by DanShu15** [comment]
Wait, that file link may have all the saves in it. If it does than rather than loading the latest save, load up cycle 486 from 
22:34:46 / May / 2021
or
22:28:54
Those should have someone currently entombed and sets of doors stacked to offer 2 entrances to some of the farm spots. Maybe the door stacking was the issue, and the load state was just an indication that something wasn't right. When freshly built before a reload they do work fine tho

**Comment by DanShu15** [comment]
I'm leaning toward the stacking of airlock doors being the issue. I've uninstalled all double stacked doors, and haven't had the issue since.
If that's correct, then the issue can be solved with a graphics change similar to the steam turbine that illustrates the need for tiles below the airlock doors. in a 4 tile high space you cannot use 2 stacked airlocks, you require 5 tiles high with a solid tile between the two doors

**Comment by peterhaneve** [comment]
It looks like double stacked doors cause a race condition, depending on their order in the save file (which is unspecified and can be different on each save). Depending on which door is loaded and initialized first, the door above may think it is missing a tile, but the normal entombed status effect does not appear on buildings with sim cell occupiers.

For now, I will add a warning to avoid stacked airlock doors to the Steam page.
