### ISSUE TITLE
[Queue for Sinks] Duplicants all queue behind 1 sink.

### ISSUE THREAD

**Issue by MasterAsagron** [peterhaneve/ONIMods#13]
I posted this on Steam, also posting here since you dont read steam comments.

This idea is a great one and should have been part of the game by default, however, cawphee.black's concern is a huge one, especially for scheduling.

> cawphee.black said:
> I love the idea of this.
> Thanks for it
> 
> Unfortunately if you have more than 1 sink they still all queue up for the first sink in the row and ignore all the rest of the sinks. So I see like 8 dupes sitting there waiting on 1 sink with 4 sinks going totally unused.
> 
> Any chance you can address this?

I understand you discussed this concern already in an issue posting however I do have a different option as an idea below.

A quick simple fix would be to allow us to turn off the queue functionality on individual buildings (a button similar to the disable building button for example) so we could say have 3 in the room without a queue and the last one would have a queue if needed for a 4 sink bathroom. 

For ore scrubbers this is fantastic, now Id only have to set up at most 2 of them to remove nearly 1 million germs. Right now I have 6 in sequence after my atmosuit dock near the slime biome. Ive only seen a duplicant use at most 2 in 1 go into the base but ive seen 3 used simultaneously.

**Comment by peterhaneve** [comment]
Checking for all cases is very intensive on performance. Version 1.1 in eac2ec9 adds support for multiple sinks and scrubbers under very specific circumstances.

**Comment by MasterAsagron** [comment]
Thanks for looking into that, ive seen other mods add buttons to buildings, wouldnt that have been an easier solution?
