### ISSUE TITLE
Feature Request for Falling Sand

### ISSUE THREAD

**Issue by strudo76** [peterhaneve/ONIMods#130]
Would it be possible to add an option setting to set the dig task of the fallen sand to a higher/specific priority. Sometimes sand will fall blocking access to an area, especially when digging up a ladder, which obviously stops dupes getting there for other tasks. Having a higher priority would allow the digger to get rid of the fallen sand immediately after it's fallen and not interrupt the other dupes tasks.

**Comment by peterhaneve** [comment]
The new Ceiling Collapse warning in both the base game and the DLC should now warn of sand falling and displacing Duplicants. Therefore, this feature will not be added to Falling Sand.
