### ISSUE TITLE
The Challenge100K mod doesn't work after The Big Merge Update

### ISSUE THREAD

**Issue by alpha6** [peterhaneve/ONIMods#131]
The mod doesn't work after The Big Merge Update

## Expected Behavior
The mod can be activated

## Current Behavior
Mod status is "Outdated" in in-game mod-menu

## Mod Versions
From 13 Nov, 2020 @ Steam workshop

## Steps to Reproduce
1. Update game to The Big Merge Update

**Comment by peterhaneve** [comment]
The 100K Challenge mod is not yet ready to be updated, as Klei is still changing world generation nearly every week. Check back after the Mergedown goes live!

100K Challenge worlds created before the Mergedown update should still be playable after the update. Consider creating a world with the DLC switched off in Steam/Epic, then playing it with the DLC switched back on.
