### ISSUE TITLE
Queue for Sinks broken after update

### ISSUE THREAD

**Issue by Cimlemad** [peterhaneve/ONIMods#132]
Duplicants aren't queuing at sinks.
## Expected Behavior

Dupes should wait while other dupes are washing their hands.
# Current Behavior

Duplicants are not stopping anymore if a wash basin is in use.
## Mod Versions

Mod 3.2.0.0 // Steam version EX1 S13-469473, mod forced update with mod updater.
## Steps to Reproduce

1. Fresh start with only ModUpdater and Queue for Sinks enabled
2. Build 3 outhouses and a single wash basin.
3. Wait for them to use outhouses at the same time.
4. Stinky doesn't wash his hands.
## Additional note
Several users are reporting the mod not working from the Steam Workshop comments section.
## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/6798280/Player.log)

**Comment by peterhaneve** [comment]
This issue has been fixed in ef1ea09.
