### ISSUE TITLE
Airlock Door Queue

### ISSUE THREAD

**Issue by Dencay** [peterhaneve/ONIMods#133]
Hey Everyone,

I noticed a lot of cancelled Errands on a single heavily used Airlock Door where Pathfinding seems to kick in.
Basically the Destination becomes unreachable during operation because both door are unpassable at this point.

I'm not schooled in the ways of modding but...
Is it possible to add "Queue for Sink" like behavior to the Door so Dupes wait a bit longer before dropping their Errand?

Much appreciated!

**Comment by peterhaneve** [comment]
If the door is very heavily used, some errands may be cancelled if the door cannot recharge quickly enough. This is most likely in low pressure areas where Duplicants can cycle the airlock very quickly. Duplicants will normally queue anyways if the door has enough charge but is busy.

Consider building multiple parallel doors (with a tile in between to avoid #125) and limiting Duplicant access permissions to spread out usage between doors and allow them to recharge.
