### ISSUE TITLE
The mod "Reloading In Motion" shows "Mod out of date" since July 16th Breath of Fresh Air update

### ISSUE THREAD

**Issue by strudo76** [peterhaneve/ONIMods#134]
As per title, "Reloading In Motion" shows "Mod out of date" and cannot be enabled. This occurs when playing the base game with the DLC installed, but not enabled. I have not tried enabling the mod when the DLC is enabled.

**Comment by peterhaneve** [comment]
Reloading in Motion is currently obsolete. Klei has added code to doors and plants that remembers the state across reload, so this mod is no longer necessary and can be safely disabled.
