### ISSUE TITLE
Sweep By Type stuttering/unresponsive when opening the filter menu

### ISSUE THREAD

**Issue by faltonico** [peterhaneve/ONIMods#14]
When i open or close the filter menu the game pauses/stutters/becomes unresponsive for a fraction of a second. 
It is even more noticeable than when selecting storage bins.

**Comment by peterhaneve** [comment]
Sweep By Type needs to check which materials are discovered when it is used. Especially during the first use, the loading / destroying of the icons takes a noticeable time.

If this takes more than a second or so, I can add a mod option to disable the material icons.

**Comment by faltonico** [comment]
I like the icons, but if it is making that to happen, i rather not have them at all, IF you can't do anything about the situation.

Can you somehow keep a cache of icons? Don't put them on the memory though, the game keeps eating memory constantly.

**Comment by peterhaneve** [comment]
Sweep By Type 1.7 now has a Mod Options menu to disable the material icons.
