### ISSUE TITLE
out of date mods

### ISSUE THREAD

**Issue by WantsHarderGames** [peterhaneve/ONIMods#145]
Both the 100k challenge and absolute zero is out of date. Any chance there will be an update?

**Comment by peterhaneve** [comment]
I do not maintain Absolute Zero. 100K Challenge was just updated this weekend! If it still appears out of date, use Mod Updater (https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).

**Comment by WantsHarderGames** [comment]
Thanks. Sorry for the wrong modpack request. I had to reinstal the game cause thats the only way i got it to work. I dont know if i should feel old or a millennial. (aw my gawd, clicking dont work. aw my gaaaaawd)
