### ISSUE TITLE
EfficientFetch: question on possible bad choices

### ISSUE THREAD

**Issue by TheMule71** [peterhaneve/ONIMods#147]
Hello,
my apologies if this isn't the best place to put a simple question. This isn't a issue. This isn't something I have seen. It's very unlikely it happens. I'm just curious, this is a "what if" question.

With efficient fetch, say you are to build a Insulated Tile made of Igneous Rock.  There are heaps of igneous rock nearby, but they are all 99 kg or less (below 25%). There's a 500 kg on the other side of the map.

Would a dup run all the way to the 500 kg heap because of this module?

**Comment by peterhaneve** [comment]
In this case, Efficient Supply would force the Duplicant to use a stack larger than 99 kg, even if it was farther away. However, in practice this situation is unusual - consider collecting debris in a few central locations if you think this will happen often.
