### ISSUE TITLE
Automation Missing

### ISSUE THREAD

**Issue by SirHawke** [peterhaneve/ONIMods#15]
For some reason when using this mod the ability to access the automation construction tab is missing. The overlay, and the items such as power shutoff are available, but anything located in the automation tab is missing.

**Comment by peterhaneve** [comment]
Which mod is affecting the automation tab?

**Comment by SirHawke** [comment]
The Queue for sinks mod. I've since removed it, and my automation menu is back.

**Comment by peterhaneve** [comment]
Queue for Sinks does not affect the automation menu; you may be suffering from a bug (https://forums.kleientertainment.com/klei-bug-tracker/oni/smart-home-research-missing-r22857/) in the base game which is known to cause menus to sometimes disappear.

**Comment by peterhaneve** [comment]
This bug is likely fixed in the Preview branch (https://forums.kleientertainment.com/game-updates/oni-alpha/) which mentions in the changelog:

- Fix newly researched build categories not appearing when there are insufficient materials
