### ISSUE TITLE
Rest for the Weary, not updated.

### ISSUE THREAD

**Issue by nirahiel** [peterhaneve/ONIMods#151]
People are saying in the [comments](https://steamcommunity.com/sharedfiles/filedetails/?id=2373109589) that this mod break their save, I would like to know if there are plans to publish an update at some point.

Thanks for such amazing mods !

**Comment by peterhaneve** [comment]
Rest for the Weary has already been updated almost three months ago. If it is somehow still out of date, you need to force an update with [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283). If *all* mods are out of date, you need to verify game files.
