### ISSUE TITLE
Airlock Door Crashes on Testing Branch U38-486258-50

### ISSUE THREAD

**Issue by Lbphero** [peterhaneve/ONIMods#159]
When I load my save, or Open a New Save and Place a new Airlock Door, on the newest update of the preview testing branch.

## Expected Behavior
Forgive my lousy wording, I believe the intended behavior is for the airlock door to be able to spawn without crashing.
Spaced Out is installed, I am on the Preview Public Testing Branch.

## Current Behavior
The game crashes without quitting to desktop upon loading an existing save with airlock doors or placing new airlock doors in a new one, automatically disabling Airlock Door.

## Mod Versions
 I am using a steam subscription.
 I have installed and enabled mod updater, the version installed seems to be the most up-to-date version by Mod Updater's Rules.

## Steps to Reproduce

1. Enable Airlock Door.
2. Hit New Game, generate any kind of Map, preferably with sandbox/debug mode on.
3. Once loaded in, attempt to place an airlock door.
4. the game will crash.

## Output Log
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/7551516/Player-prev.log)

Error in PAirlockDoorComplete.AirlockDoor.OnSpawn 
System.MissingMethodException: void Grid/BuildFlagsFakeFloorIndexer.set_Item(int,bool)
  at PeterHan.AirlockDoor.AirlockDoor.OnSpawn () [0x000c3] in <da80ef261f9e43c38687d818ec99e654>:0 
  at KMonoBehaviour.Spawn () [0x00078] in C:\jenkins_workspace\workspace\Preview_Simgame_Windows\game\Assets\Plugins\Klei\util\KMonoBehaviour.cs:285 

UnityEngine.Debug:LogError (object,UnityEngine.Object)
Debug:LogError (object,UnityEngine.Object) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Debug.cs:152)
DebugUtil:LogErrorArgs (UnityEngine.Object,object[]) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/DebugUtil.cs:191)
DebugUtil:LogException (UnityEngine.Object,string,System.Exception) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/DebugUtil.cs:201)
KMonoBehaviour:Spawn () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:292)
KMonoBehaviour:Start () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:243)

Build: U38-486258-SD

**Comment by Lbphero** [comment]
Still an issue on the newest non-testing update, U38-486499-50.

**Comment by peterhaneve** [comment]
There is no support for Public Testing branches, but Airlock Door has been updated now that U38-486499 is live.
