### ISSUE TITLE
Airlock door / the stock bug fix / fast save  broke after latest patch.    

### ISSUE THREAD

**Issue by CristiCDX** [peterhaneve/ONIMods#160]
## Expected Behavior
  work
 
Yes, not using any branch. just getting the basic spaced out updates

## Current Behavior

It Crashes existing game saves. leads to UE crash log

## Mod Versions

steam subscription and I'm using the mod updater

## Steps to Reproduce
 
1. AD  load existing save the file with the mod enabled
2. AD   lag while loading :)
3.AD    crash
4. AD    (it can be fixed by disabling the mod, loading the save file without it, saving, reactivating the mod, loading the latest save. now it loads with the mod,building another airlock leads to crashing again thou  ) 

[Player.log](https://github.com/peterhaneve/ONIMods/files/7574822/Player.log)
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/7574823/Player-prev.log)

first time using GitHub , Idk what I'm doing :)

**Comment by peterhaneve** [comment]
`[PLib] Mod AirlockDoor initialized, version 3.0.0.0`

You are still running version 3.0 of Airlock Door, which was released 25/06/2021 and is over six months out of date. It looks like Mod Updater is indeed active, so try clicking the green checkmark again next to Airlock Door to force it to update once more.
