### ISSUE TITLE
PipPlantOverlay: Pip planted a seed in a too-many-plants orange tile 

### ISSUE THREAD

**Issue by mx2048** [peterhaneve/ONIMods#164]
Pip planted a seed in a too-many-plants orange tile. See the images below.

![bandicam 2021-12-17 02-46-22-335](https://user-images.githubusercontent.com/24634074/146533870-0c869e2f-b916-42e6-8b8c-2d1ea50dbad1.jpg)

![bandicam 2021-12-17 02-46-29-279](https://user-images.githubusercontent.com/24634074/146533895-6145c53f-069a-4181-b55f-aeeaec6ab4e3.jpg)

## Expected Behavior
Supposedly, pips should not plant in orange tiles when in the Pip layout. 
Playing vanilla ONI. The Spaced Out DLC is installed bu disabled.

**Comment by peterhaneve** [comment]
According to the vanilla rules, that tile indeed does have too many plants - all of the mushrooms on the bottom floor are within 5 tiles of the target plant. Do you have any other mods installed?

**Comment by mx2048** [comment]
Yes, I have the following mods installed:
GasOverlay
Bigger Camera Zoom out
Geyser Calculated Average Outpit Tooltip
Build Over Plants
Better Info Cards
Suppress Notifications
Show Building Ranges
Better Deselect

**Comment by mx2048** [comment]
The same pip foraged a new acorn and planted it right next to another arbor tree. It appears the vanilla game allows planting seeds anywhere now (or it is just a sort of a bug). Your mod probably has nothing to do with it.

![bandicam 2021-12-17 22-15-09-647](https://user-images.githubusercontent.com/24634074/146631475-ebb1b77a-2f86-4f16-a22e-f3e6713ec31f.jpg)

**Comment by peterhaneve** [comment]
Pips can plant seeds in Farm Tile regardless of the other planting criteria, as the resulting plant will not be Wild. While it might be helpful to update the diagnostics in Pip Plant Overlay, this change should not affect the primary purpose of the overlay for planning out parks and natural farms.
