### ISSUE TITLE
Request - Future Mod Suggestions

### ISSUE THREAD

**Issue by Electrocutor** [peterhaneve/ONIMods#165]
I don't know if you accept input for ideas or not, but I figured I'd drop a few and see what you thought.

[ Research: Gravitas ]
- Adds end-game research branch
- Requires conditions that can only be met when utilizing end-game materials and difficult to accomplish tasks
- Requires studying existing Gravitas devices to unlock as well
- May also include some Archaic furniture
- Unlocks the ability to make Gravitas devices, such as Anti Entropy Thermo-Nullifier, Teleport Receivers, Teleport Transmitters, Neural Vacillator, etc. The teleports would need a drop-down to select which colony to teleport to/from per device and should consume something substantial to function each time for balance vs supply rockets.

[ Gameplay: Line of Sight ]
- Similar to darkness mods, but instead of requiring light to see an area, it blocks view of any areas that have not been within line-of-sight of dupes. This way, you must dig and venture before you can see what is where.

[ Survival: Thirst ]
- Duplicants have thirst
- Works like hunger, except for clean water
- Drinking germs would likely cause sickness

[ Fix: Catch Breath ]
- Make it so oxygen is actually required
- Current game does not use oxygen when they hold breath, and does not use oxygen when they catch breath after holding it
- I figure the best way would be to have a catching-breath state that doubles their oxygen use until they catch their breath
- If the place they are trying to catch their breath runs out of oxygen, they would have to find more

[ Gameplay: Meteors Restored ]
- Turns meteor storms back on for Spaced Out
- Also affects rockets
- Would need to play some to figure out balance and to see if any additional buildings or something would be necessary

[ Survival: Sanity ]
- Makes recreation a survival requirement, similar to hunger, but instead of death causes accelerated stress

[ Gameplay: Pressure ]
- Have the mass per tile of gas affect temperature if it changes up or down
- Perhaps also have state affected by mass per tile/pressure; such that you could manually create phase change coolers

**Comment by peterhaneve** [comment]
Please post mod suggestions on the [Klei modding forums](https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/) so that any mod maker can see them.
