### ISSUE TITLE
Airlock Door "Trapped" duplicants

### ISSUE THREAD

**Issue by VasVadum** [peterhaneve/ONIMods#167]
## Expected Behavior
Duplicants should be walking through the door like normal.
No I don't have Spaced Out.

## Current Behavior
A duplicant will sometimes walk into the room behind the airlock, and for no reason, become trapped till someone else goes through the door. Sometimes my power grid goes down because I don't have enough production, but the doors store a certain amount of power in them that I see, and they are all fully charged. There's no reason the duplicant should be "trapped". Its really starting to agitate me because they keep peeing all over the floor and the game has this retarded oxygen system that causes pee to generate polluted oxygen that floats around inside your base forever because it can't be gotten rid of in any way shape or form as it just randomly moves around like a puff of smoke that can't vanish, as if real life totally worked that way.

## Mod Versions
I installed the latest version of the mod for the first time, there's no download conflict with updating. I didn't even own the game till about a week ago.

## Steps to Reproduce
I'm not sure I can give you a list of steps to reproduce. This happens entirely at random right now.
![20211225020921_1](https://user-images.githubusercontent.com/1490797/147379730-6ae2d575-48a1-4a5b-a1b7-1949fa8778c5.jpg)
![20211225020931_1](https://user-images.githubusercontent.com/1490797/147379731-d95f4a8f-1415-4f7f-8b13-aaafb542ca6d.jpg)

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/7775577/Player.log)

**Comment by peterhaneve** [comment]
Due to a quirk in the game's pathfinding system, ladders next to airlock doors are not always treated as locations where the Duplicant can stand and wait for the door to open. Try adding at least one regular tile for the Duplicant to stand on each side of the door.
