### ISSUE TITLE
Airlock door mod crashes game in latest oni update

### ISSUE THREAD

**Issue by raggynld** [peterhaneve/ONIMods#169]
the game crashes once building a airlock door or loading a game with existing airlock door(s)

oni spaced out DLC build version: u39-490405-50

**Comment by peterhaneve** [comment]
You have an outdated version of Airlock Door. You may need to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) as ONI does not always automatically update mods.
