### ISSUE TITLE
Claustrophobia Dupe Gen bug

### ISSUE THREAD

**Issue by Kiahnte** [peterhaneve/ONIMods#17]
Your mod claustrophobia appears to cause a bug where the middle dupe in generation will not, after you start, have the skills shown when generating (i.e. his skills won't even match his interests as the game intends now).

**Comment by peterhaneve** [comment]
Claustrophobia does not affect Duplicant generation at all. This issue seems like a mod conflict, most likely with Duplicant Settings Generation Manager or Advanced Start.
