### ISSUE TITLE
When playing the 100K challenge map, space is surrounded by neutronium

### ISSUE THREAD

**Issue by jjalling** [peterhaneve/ONIMods#170]
Unable to use rockets, because space is surrounded by neutronium. The meteors can't pass as well.

## Expected Behavior
No neutronium in the space biome.
I have the Spaced Out! DLC installed, but it us not enabled.
I experience the same if playing the public beta as well.

## Current Behavior
The space biome is surrounded by neutronium, making it impossible to use rockets.

## Mod Versions
V. 3.0.0.0 using the steam workshop.

## Steps to Reproduce
1. Make a new 100k challenge map
2. Enable sandbox mode to reveal full map
3. Check if there is neutronium in the space biome
4.

**Comment by jjalling** [comment]
Thank you for solving this so fast. Happy new year!

Br Jonas

**Comment by peterhaneve** [comment]
It appears that the neutronium border spawning issue was changed in or near build 482865. The required tag to prevent the border from appearing has been added to all new 100K worlds.
