### ISSUE TITLE
Do you mind people translating your mods via "Mod Translation"?

### ISSUE THREAD

**Issue by DDEle** [peterhaneve/ONIMods#171]
Hi Peter,
I'm the author of [Mod Translation](https://github.com/ONI-Wiki-zh/ModI18n). Do you mind people adding translations of your mods (and PLib) with Mod Translation? You don't need to change anything in your code and you are not expected to keep your mod stable.

Mod Translation is designed for modders and translators and it helps mods to be international easily and timely. It worked by downloading translations from [a Github repo](https://github.com/ONI-Wiki-zh/ONIi18n) and overriding game strings with them, which means your mods don't need to update and force everyone to restart their game for a new language to appear, and Steam failing to update is not an issue either. Similarly, it also makes the translator's life easier when adding or updating mod text in terms of updating translations accordingly.

Mod Translation only holds strings for translation. Therefore, it will never be able to steal your work as users must subscribe to the original mod (or install locally if you have made that possible). Both the mod itself and the repository that holds translations are with MIT license and are free for everyone to use and contribute. If you don't mind me adding support to your mods, you will be able to opt out at any time later.

I noticed that many of (or all of) your mods themself are translatable, However, it seems that some of their translations have not yet been pushed or updated to the steam workshop. In this case, your mods will benefit from easier translation updating.

I'll not copy your current translated strings to my repo directly in any case but ask the original translator to add it to ModI18n's repo instead.

**Comment by peterhaneve** [comment]
I would prefer that translations for these mods would be included with the mod. If you have translations for these mods that are not currently in this repository, feel free to submit a pull request.

Some translations have indeed not been uploaded to Steam, but due to Steam's problems with updates, I am hesitant to update a mod for just translation changes.

**Comment by DDEle** [comment]
Well, allowing adding translations via Mod Translation does not mean that no translation can be provided with the original work (so that users without Mod Translation will also have translations). Instead, I'll encourage translators to contribute to the original mod repos (e.g. yours) at the same time. In your case, Mod Translation helps eliminate the gap (seems to be weeks to months for some mods) between translators' submissions and steam workshop users' screens.

**Comment by peterhaneve** [comment]
I would not mind people translating mods with Mod Translation (as it only affects their installation), but I would also prefer if the translation was also submitted here so I could integrate it eventually.

**Comment by DDEle** [comment]
OK. I'll make sure to mention that when I accept PR/dealing with issues. Thanks for your consideration.
