### ISSUE TITLE
PeterHan.PLib.Core.PLibStrings Chinese Translation Update

### ISSUE THREAD

**Issue by Ventulus-lab** [peterhaneve/ONIMods#173]
Hi Peter,
I found that the Chinese translations of its own strings in PLib.Core were not updated with PLib.Since this is something that has a very wide impact, I rushed to translate it and submit it to you. I would also like to remind you that the template file is not complete either, there should be 35 strings now.

[PeterHan.PLib.Core.PLibStrings.zip](https://github.com/peterhaneve/ONIMods/files/7944562/PeterHan.PLib.Core.PLibStrings.zip)

**Comment by Ventulus-lab** [comment]
BTW, I would also like to make a suggestion. I hope you can remove the hesitation. There are now many players speaking different languages in countries all over the world. Many modules will update their versions for the sake of translation. Many of your mods are excellent and are used by many players as essential modules. They are waiting in vain for the translation updates of some of your modules. For example "Finish-Up time" and so on.
Of course, if you don't want to go through the hassle of submitting to steam, I suggest you work with DDEle's "ONIi18n" module to give players a taste of the new translated text before you update it to steam. His module downloads po files from github, so it's very easy and quick to update strings.

**Comment by peterhaneve** [comment]
Thank you for contributing a translation update. I have unfortunately very busy at work and have not had a chance to update many mods recently, but PLib version 4.7.1 will have your translation update and will roll out to mods one by one.

Updating mods for just translation can be dangerous - Steam often gives out older versions of bugs with critical bugs, sometimes even reverting mods to older, broken versions when the game "updates". I will usually not make a new release with translations only for this reason.

**Comment by peterhaneve** [comment]
I went through and updated a large number of mods with the corrected Chinese translations.
