### ISSUE TITLE
bug in NoWasteNoWant

### ISSUE THREAD

**Issue by Ventulus-lab** [peterhaneve/ONIMods#175]
It seems that NoWasteNoWant does not handle Cooking Ingredient very well such as Pincha Peppernut and Sleet Wheat Grain . When the freshness of Pincha Peppernut and Sleet Wheat Grain is less than the set value, the dupes repeatedly put them in the fridge.  Then they drop out automatically.Drop in and out repeatedly

**Comment by peterhaneve** [comment]
It appears that this issue was introduced by the Buff and Shine update just before DLC's public launch. It is fixed in File Version 1.1 (https://github.com/peterhaneve/ONIMods/commit/fdcd06a43cdd3b5e7076d7d59c809e0a0a26e949).
