### ISSUE TITLE
Airlock Door

### ISSUE THREAD

**Issue by Banhammer60** [peterhaneve/ONIMods#179]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Banhammer60** [comment]
The icon does not appear in the base menu

**Comment by peterhaneve** [comment]
With no logs it will be almost entirely impossible to diagnose the issue. However, note that none of the mods here are supported on the Public Testing branch. If you care about this mod, consider sticking with the stable release.

**Comment by Banhammer60** [comment]
Stable version is also faulty
