### ISSUE TITLE
sweep by type: items sometimes duplicated in list

### ISSUE THREAD

**Issue by DefectiveNu** [peterhaneve/ONIMods#18]
I've had 3 times now Super coolant become checked when I had all liquids deselected.  The checkmark stays completely blank still, but a 2nd entry for super coolant appears at the bottom and is checked if you expend the menu.

**Comment by peterhaneve** [comment]
In what category does the other super coolant entry appear? If some super coolant becomes gas or solid, it will create an entry in Unbreathable Gas or Liquifiable.

**Comment by peterhaneve** [comment]
This issue should be fixed in Sweep By Type 1.9.
