### ISSUE TITLE
Show Building Ranges mod does not work with latest version [Game Update] - 496912

### ISSUE THREAD

**Issue by joeymojo** [peterhaneve/ONIMods#180]
## Current Behavior
![image](https://user-images.githubusercontent.com/100447957/155810741-2feb42f8-5f15-49b0-89ab-dbe0475e6759.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by peterhaneve** [comment]
You need to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283), as described in the issue directions, to force update Show Building Ranges and potentially other mods to the version compatible with the update.

**Comment by joeymojo** [comment]
Thank you very much for all the hard work. This fixed my issue.
