### ISSUE TITLE
Door not available in build menu

### ISSUE THREAD

**Issue by kuxynator** [peterhaneve/ONIMods#185]
Door not available in build menu
Mod Version 3.5.0.0 Mod Updater used.

Any Idea oder still a bug?

**Comment by peterhaneve** [comment]
There is no information in this issue about which mod is failing, and without logs issues will be nearly impossible to diagnose. It still seems likely that the wrong mod version is installed, consider clicking the green checkbox can force updates even if the mod seems up to date.

**Comment by kuxynator** [comment]
several mods in one repository, has a few disadvantages  ;-)  my issue refers to "Airlock Door"
Force Update has helped. But then something is dirty in the chain, if two actions are required: use Mod Updater AND Force Update. you don't really come up with that, if you have not already had a similar case. ;-)
Thx
