### ISSUE TITLE
Fast save crashed after update

### ISSUE THREAD

**Issue by nskyzh** [peterhaneve/ONIMods#186]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by slgray16** [comment]
Some additional information:   

- DLC installed
- A crash occurs while loading the game but before loading the saves.  
- The game automatically disables your mod which resolved the issue.  
- This is affecting multiple users.  I would guess all users, but about 10 have reported an issue on the steam workshop page.

It should be really easy to reproduce but let me know if you need logs.

Thank you again for your mod.

**Comment by peterhaneve** [comment]
This game update broke almost every mod, but you can use Mod Updater, as described in the issue directions, to force update all mods to the version compatible with the update.
