### ISSUE TITLE
Game Crash with Automated Colony/Automated Composter: Selecting Recipe

### ISSUE THREAD

**Issue by kuxynator** [peterhaneve/ONIMods#189]
Mod: Automated Colony (I assume)
Building: Automated Composter

Game crashes when building a composter and selecting a recipe for the first time.
 
NullReferenceException: Object reference not set to an instance of an object

SelectedRecipeQueueScreen.GetIngredientDescriptions (ComplexRecipe recipe) (at <33cbadb4d53344698461e1b8bda03e57>:0)
SelectedRecipeQueueScreen.RefreshIngredientDescriptors () (at <33cbadb4d53344698461e1b8bda03e57>:0)
SelectedRecipeQueueScreen.SetRecipe (ComplexFabricatorSideScreen owner, ComplexFabricator target, ComplexRecipe recipe) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ComplexFabricatorSideScreen.ToggleClicked (KToggle toggle) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ComplexFabricatorSideScreen+<>c__DisplayClass34_1.<Initialize>b__1 () (at <33cbadb4d53344698461e1b8bda03e57>:0)
Util.Signal (System.Action action) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KToggle.Click () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KToggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <53ba8544b0394db88dcaac034e1fe553>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <04d0cd30fbf9474897ce2cf447facfe7>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <04d0cd30fbf9474897ce2cf447facfe7>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U41-498381-SD

**Comment by kuxynator** [comment]
Its on the first recipe "Compostable to dirt" 
https://prnt.sc/Rnc_1W324Sw
![20220312060906_1](https://user-images.githubusercontent.com/66268429/158005078-99f1a5d9-72f3-4e79-aefb-d5ab57ef2344.jpg)
Other recipes seems to work w/o crash.

BTW I'm not sure if this really from you, but it was the most obvious. 
The Gane does not show the mod name for objects (like in Factorio) Is there a current mod that shows such information?

**Comment by peterhaneve** [comment]
This mod is not maintained in this repository. Are you using [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1828749978)? If so, you need to contact Rainbow, not me.
