### ISSUE TITLE
Feature request: Incubator supply errand type

### ISSUE THREAD

**Issue by Tenzian** [peterhaneve/ONIMods#196]
Would it be possible to add to Stock Bug Fix a change of the errand for supplying eggs to incubators from "Farming Supply" to "Ranching Supply"?

It doesn't seem like Farming is the correct skill for this errand: All the other incubator related jobs are Ranching & it's annoying to have a dedicated farmer cross the map to fill up incubators.

![Screenshot 2022-03-21 at 18 10 36](https://user-images.githubusercontent.com/13963952/159337258-f9ee00ab-a06a-4529-b48b-07784175761e.png)

**Comment by peterhaneve** [comment]
This bug fix has been added in Stock Bug Fix 3.10.0.0.

**Comment by Tenzian** [comment]
Thank you!
