### ISSUE TITLE
critter count and fish release not working in stock bug fix

### ISSUE THREAD

**Issue by treemasaki** [peterhaneve/ONIMods#198]
I installed the fix bug before but now seems the bug exists again the critter count and fish release are not counting properly
the critter count keeps flashing from 0-1
![20220325224533_1](https://user-images.githubusercontent.com/102371465/160144393-fc005a7c-523d-4547-a9c4-ae85db4942c4.jpg)
![20220325224526_1](https://user-images.githubusercontent.com/102371465/160144536-78483e98-d6fe-44b8-83b4-43f3a716e70a.jpg)

![20220325224846_1](https://user-images.githubusercontent.com/102371465/160144405-5e5b1aaf-b5f1-4659-9fa8-e7e6ed081b57.jpg)

**Comment by peterhaneve** [comment]
This is a [different bug](https://forums.kleientertainment.com/klei-bug-tracker/oni/critter-sensor-doesnt-work-with-tropical-pacu-r31143/) in the base game, where Tropical Pacu cause excessive room rebuilds, breaking both the Critter Sensor and Fish Release. Unfortunately no easy fix is available for this one yet in Stock Bug Fix.

**Comment by treemasaki** [comment]
> This is a [different bug](https://forums.kleientertainment.com/klei-bug-tracker/oni/critter-sensor-doesnt-work-with-tropical-pacu-r31143/) in the base game, where Tropical Pacu cause excessive room rebuilds, breaking both the Critter Sensor and Fish Release. Unfortunately no easy fix is available for this one yet in Stock Bug Fix.

Thanks but does that mean the fish release bug fix is only applicable to pacu and gulp pacu?lol

**Comment by peterhaneve** [comment]
The fish release fix fixes a totally separate bug from the Tropical Pacu bug, which also affects the Critter Sensor. Unfortunately that bug is much harder to fix as it involves several game systems interacting with each other, namely Decor updates and room rebuilds fighting each other in a loop.
