### ISSUE TITLE
you need to fix your mod updater 

### ISSUE THREAD

**Issue by nijakattack** [peterhaneve/ONIMods#199]
I think I speak for everyone on the steam mod page and that your mod is stopping everyone from playing are games
when the game starts up it goes to the page were it disables the mods that are causing the game to stop working.

**Comment by peterhaneve** [comment]
The recent Klei update means that most users will probably need to [manually install](https://github.com/peterhaneve/ONIMods/blob/main/README.md) Mod Updater from this GitHub to get it working again. Steam does not auto-update mods, so you must download and install the working version manually to update other mods.
