### ISSUE TITLE
[FEATURE REQUEST]Hot Key configuration

### ISSUE THREAD

**Issue by DarkApocalypse** [peterhaneve/ONIMods#2]
Could you add a config file or a way to modify the hot key for BulkSettingsChange?

**Comment by peterhaneve** [comment]
Due to the way that Klei implemented Actions, making this configurable would actually require rewriting most of the game's keyboard action code. Such a change would be an extreme effort but is definitely on the long term radar.

**Comment by peterhaneve** [comment]
Settings Change Tool version 1.2.0.0 adds the ability to customize hotkeys.
