### ISSUE TITLE
[mod]: uninstalled or not found on workshop. Check your connection, and that the mods directory has sufficient disk space and permissions

### ISSUE THREAD

**Issue by celtek** [peterhaneve/ONIMods#200]
## Expected Behavior
Mods should be able to be updated.
No DLC.

## Current Behavior
Getting an error when trying to force update my mods:

"[mod]: uninstalled or not found on workshop. Check your connection, and that the mods directory has sufficient disk space and permissions"

Plenty of space on my disk and the permissions haven't changed. Obviously my internet connection is fine.

## Mod Versions
Steam subscriptions. Force updating results in the above error.

## Steps to Reproduce

1. Open ONI.
2. See all mods disabled because they're "out of date."
3. Attempt to force update mod.
4. Get the error that mod is uninstalled or not found on workship. Check connection, disk space, permissions.

## Output Log

Getting an error when trying to force update my mods:

"[mod]: uninstalled or not found on workshop. Check your connection, and that the mods directory has sufficient disk space and permissions"

Plenty of space on my disk and the permissions haven't changed. Obviously my internet connection is fine.

[Player.log](https://github.com/peterhaneve/ONIMods/files/8358039/Player.log)

**Comment by peterhaneve** [comment]
This is an unfortunate bug that should have been fixed in Mod Updater 2.7 which was just released. It is likely that you will need to unsubscribe and resubscribe to Mod Updater, or to manually install it from this repository, to allow mods to be updated again.

**Comment by celtek** [comment]
Reinstalling fixed the issue. I think it was an issue with ONI.
