### ISSUE TITLE
Fast Track: kcal graph on top left keeps jumping between ~0kcal and the expected kcal amount 

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#201]
While using Fast Track, I'm seeing the expected performance increases, but I'm noticing that the kcal amount keeps jumping between a normal expected kcal amount (for what's in a fridge or freezer on a given asteroid) and either 0 kcal, or very low kcal amounts (2400 for instance). It stays here for a few moments, then recovers and starts showing the normal amount, every few seconds or so.

## Expected Behavior

The kcal amount displayed should be normal for food that's accessible, even if disabled in consumables. 

This is in regular released Spaced Out DLC with Fast Track and a variety of quality of life mods (including Waste not Want Not, the only mod I have that should be affecting food specifically)

## Current Behavior

The available calories keeps updating between either 0 or very low kcal amounts (and showing red) and back. Additionally, "unpermitted food" notifications keep showing up as well, despite dupes being permitted to eat some (but not all) of the food in the freezer.

## Mod Versions

Local version, acquired last night from github, mod_info.yaml says version "0.2.5.1"

N/A

## Steps to Reproduce

1. Load the attached save.
2. Unpause the game and observe for a short period of time.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8403062/Player.log)

[The Underground Home.zip](https://github.com/peterhaneve/ONIMods/files/8403064/The.Underground.Home.zip)
<img width="582" alt="Oxygen Not Included 4_2_2022 10_21_08 AM" src="https://user-images.githubusercontent.com/12467241/161394210-76076dad-72cc-4088-a4b6-12d02d67873e.png">
<img width="646" alt="Oxygen Not Included 4_2_2022 10_21_02 AM" src="https://user-images.githubusercontent.com/12467241/161394211-d99ffc4b-3a11-4ede-bb07-7b513b1bc5c0.png">

**Comment by peterhaneve** [comment]
This issue does not reproduce for me, so I believe that it is a race condition with background world inventory. Does the error go away if you disable the optimization *Background Inventory* in the mod options?

**Comment by anpilley** [comment]
I disabled Background Inventory and the issue is still replicating on my end.

**Comment by anpilley** [comment]
After a bit of experimentation with the settings around pathing and debris accessibility, the issue seems to disappear if I disable _Duplicants -> Fast Reachability Checks_, even if I re-enable _Background Inventory_.

**Comment by peterhaneve** [comment]
I believe that this has been fixed in [d5e5a1e](https://github.com/peterhaneve/ONIMods/commit/d5e5a1e0e29cae3f4c75b617e73603889a1a4f33). If the issue occurs again with Fast Reachability checks on, please open a new issue.
