### ISSUE TITLE
Fast Track: Rover doesn't function with "Reduce Debris Checks"

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#202]
## Expected Behavior

Rover should be moving around, doing tasks, or at least idling with Fast Track Enabled

This is a Spaced Out DLC game.

## Current Behavior

Rover stands still and doesn't start working when the option "Reduce Debris Checks" is enabled for fast track. Narrowed it down to this with a binary search of enabling settings affecting creatures (so the critter options, dulicant options, and item options)

## Mod Versions

Local Copy, v0.2.5.1
## Steps to Reproduce

1. Have a Rover on a planet (see attached save file, rover is at the top of the screen)
2. Enable Reduce Debris Checks
3. Note that Rover is not doing anything (in this case gathering sandstone)
4. Disable Reduce Debris Checks
5. See Rover start to function again

## Output Log

[The Smart Trainwreck.zip](https://github.com/peterhaneve/ONIMods/files/8405385/The.Smart.Trainwreck.zip)

[Player.log](https://github.com/peterhaneve/ONIMods/files/8405380/Player.log)

**Comment by peterhaneve** [comment]
Rovers now work, and should be almost as fast and efficient as Duplicants now, in [9564a9e](https://github.com/peterhaneve/ONIMods/commit/9564a9e5d0107e0ace4818d7c19320cf18af4e55).
