### ISSUE TITLE
Crash in Fast Track 0.2.11.0

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#204]
Using FastTrack 0.2.11.0, and hit a crash.

## Expected Behavior
Shouldn't Crash
Spaced out DLC enabled.

## Current Behavior
Crashed.

## Mod Versions
Local copy, Fast Track 0.2.11.0 pulled from github.

## Steps to Reproduce
Not sure if any particular event triggered it. I'd queued up a dig and then replaced the dig with a pump building, and followed that up with laying some pipes that intersected with existing natural granite tiles, all while paused.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8456132/Player.log)

**Comment by peterhaneve** [comment]
I made the SCP threadsafe now which should allow background offset updates without a race condition now.
