### ISSUE TITLE
Lock up in main menu while trying to restart after changing FT mod settings. (disable batch audio)

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#205]
I was having some audio issues, and I disabled Batch Audio from the main menu after save/quit-to-menu (per Fradow's suggestion), and the game locked up with audio stuttering.

## Expected Behavior
DLC enabled, game shouldn't lock up, and shouldn't be experiencing audio issues. The audio around the research reactor shouldn't be stuttering

## Current Behavior
I was viewing around the Research reactor while some dupes did tasks, when I got the audio issues initially, but it got worse and worse over time and started affecting every area of the map. Eventually i saved and quit to menu, and then disabled Batch audio, and that's when the game locked up instead of restarting.

The game locked up.

## Mod Versions
Local copy off github, 0.2.11.0.

## Steps to Reproduce
Play for some time around a research reactor. 
Notice audio degradation (clicking sound while reactor running) and then progressively more stuttering over the course of some time.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8457399/Player.log)

[The Underground Home Cycle 600.zip](https://github.com/peterhaneve/ONIMods/files/8457406/The.Underground.Home.Cycle.600.zip)

**Comment by peterhaneve** [comment]
Apparently `LoopingSoundsManager` dislikes being throttled so much with short sounds, so I cut it back to half framerate instead of 5 FPS. The lockup on restart is not Fast Track, as the log shows the restarter is called.
