### ISSUE TITLE
Deselect materials is not working on the steam workshop

### ISSUE THREAD

**Issue by LittlePrincessSushi** [peterhaneve/ONIMods#208]
A month or two ago the mod of deselecting new materials stopped working.

## Expected Behavior
A working mod that deselects new materials in storage containers

## Current Behavior
It crashes when trying to open the game

## Mod Versions
The one that is on steam right now. Last updated Feb 21
the mod updater crashes the game as well so I cant use that (the name of the mod is in red in the mod list in-game)

## Steps to Reproduce
1.
2.
3.
4.

## Output Log
after searching for a long time, it doesn't want to appear. 

Every time the game starts it crashes. It will only work if I turn off the mod which is sad cuz it is kind of a must-have mod these days. Hope you can fix this.

**Comment by peterhaneve** [comment]
It looks like Steam is failing to update both Deselect New Materials and Mod Updater. You will need to [manually install](https://github.com/peterhaneve/ONIMods/blob/main/README.md) Mod Updater to get the correct versions of both mods.
