### ISSUE TITLE
Fast Track: Crash after clicking rocket Property tab on Starmap

### ISSUE THREAD

**Issue by jincheng95** [peterhaneve/ONIMods#209]
First of all, thank you for the mod and updates, making ONI a much more playable game. ❤️

## Expected Behavior
Game to display Property tab of the selected rocket on starmap without crashing.

## Current Behavior
Game crashes after clicking on the Property tab of the selected rocket on starmap.

## Mod Versions
Fast Track 0.2.15
No other mods running

## Steps to Reproduce

1. Go to starmap
2. Select any rocket
3. Click on property tab of the corresponding rocket
4. Game crashes

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8521852/Player.log)

**Comment by peterhaneve** [comment]
It looks like this one was already fixed by another change to reduce memory allocations of number formatters. But thanks for the report anyways!
