### ISSUE TITLE
Building Solution

### ISSUE THREAD

**Issue by altmank** [peterhaneve/ONIMods#21]
Hey, how would I build this solution myself? Fails to build properly as cloned.

**Comment by peterhaneve** [comment]
The .NET Framework 2.0 and 3.5 support required to build this solution is often not installed by default in modern versions of Windows. Try using the Control Panel method detailed in https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10 .

**Comment by altmank** [comment]
@peterhaneve Thanks, I do need to install that but  I was also not seeing the project ElementDict.csproj that is reference din the SLN in the repository.

**Comment by peterhaneve** [comment]
The ElementDict project can be ignored, it is not required for the other projects and is currently not ready for prime time.
