### ISSUE TITLE
FastTrack: Uptime calculation shows 10% instead of 100%

### ISSUE THREAD

**Issue by Raukgorth** [peterhaneve/ONIMods#210]
I have a ceiling lamp that is on 100% of the time. Uptime calculation show 10%. When unpaused the game flickers between 100% and 10%.
The electric grill correctly shows 90% uptime.

## Expected Behavior
It should be at 100%.

Yes, I have the DLC. Not using preview.

## Current Behavior
Uptime calculation show 10%. When unpaused the game flickers between 100% and 10%.

## Mod Versions
I'm using a local copy. version 0.2.17.0

## Steps to Reproduce
1. Launch ONI
2. Create a new game
3. Build a ceiling lamp and connect it to a power source that doesn't run out.
4. Watch uptime flicker between 10% and 100%.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8567127/Player.log)

General summary
In title.

**Comment by peterhaneve** [comment]
I think this race condition has been fixed in 0.2.18.

**Comment by Raukgorth** [comment]
I can confirm, that the issue is resolved with version 0.2.18
