### ISSUE TITLE
Fast Track: Disapering launch checklist text on rocket sidescreen

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#211]
## Expected Behavior

The test on the launch checklist should stay visible when the game is running and not paused

These are DLC rockets
## Current Behavior

After selecting a rocket after three seconds or so, all the text disappears from the checklist but the check boxes remain if the game is not paused.
## Mod Versions

v0.2.18
## Steps to Reproduce

1.Select a Rocket Platform or Solo Spacefarer nosecone
2. If paused, resume the game
3. Wait ~3 seconds
4. Watch text disappear

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8584483/Player.log)

**Comment by peterhaneve** [comment]
It looks like an improvement to freeze layouts on this screen fixed this issue as a side effect, it no longer repros on HEAD (but it does repro on the live version so it indeed was a problem!). Thanks for the report!
