### ISSUE TITLE
Fast Track: Massive FPS loss and game pausing with certian sidescreens open

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#212]
## Expected Behavior

Smooth animations and input while having any of the following side screens open:
refrigerator, lavatory, grill, microbe musher, storage bin, oxygen mask dock, crafting station, metal refinery, desalinator, canister filler, ethanol distiller, gas rocket port loader, liquid reservoir, hydrogen generator (idle)

## Current Behavior

Whenever the aforementioned side screens are open fps drops dramatically (95 -> 40 FPS) and the game does not run smooth (as in everything pauses then starts then pauses etc) as long as the side screen is open. I've checked all the following side screens and they don't cause the same issue:
tiles, pneumatic doors, geysers, research stations, printing pods, med bed, plants, critters, duplicants, critter drop offs, mess tables, planting pots, rocket platforms, oxygen mask checkpoint, rock crusher, pedestal, solar panels, bottle emptier (idle), egg, manual generator, canister emptier (idle), power switch

It seems that this gets worse the longer the save file runs I had been playing for about an hour when I really started to notice it and investigate further but after the reload to make sure it was reproducible for this ticket it wasn't as obvious except on the storage bin.

## Mod Versions

v0.2.18
## Steps to Reproduce

1. Load attached save
2. Click on any listed building. (the storage bin is the most noticeable on fresh load)
3. Watch duplicants animations to see the pause start pause start action

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8591855/Player.log)
[The Smart Trainwreck.zip](https://github.com/peterhaneve/ONIMods/files/8591869/The.Smart.Trainwreck.zip)

**Comment by peterhaneve** [comment]
The base game has always been slow to update large storage lists. I did find a silly mistake that was causing the map to be scanned for new geysers too often, and fixed an instance of pickups being boxed in a dictionary, which may help with any GC-related issue like this one.
