### ISSUE TITLE
Fast Track: Geyser, critter and plant names repeat and have extra info text in front in name

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#213]
## Expected Behavior

Non-repeating geyser, critter, and plant names and no extra info text in front of geyser/critter/plant names in the mouse over tool tip.
## Current Behavior

When moused over the name of the geyser/critter/plant will continuously repeat and fill up the mouse over tool tip. Additionally extra info of the temperature, amount of, or number of units will appear in the tool tip before the geysers/critter/plant name.
## Mod Versions

v0.3.0
## Steps to Reproduce

1.Load game
2.Mouse over geyser/critter/plant
3.See tool tip explode with extra copies of the geyser/critter/plant's name

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8597634/Player.log)

**Comment by peterhaneve** [comment]
Apparently Better Info Cards was hiding a bug where an old buffer was not cleared. I fixed it in 0.3.1 along with further optimizing that slow storage side screen.
