### ISSUE TITLE
FastTrack Crash when clicked on tile.

### ISSUE THREAD

**Issue by Raukgorth** [peterhaneve/ONIMods#214]
The game crashed when I switched back to it. Not sure what I clicked on. Might be related to Better Info Cards.

## Expected Behavior
N/A
## Current Behavior
N/A

## Mod Versions
Local copy. Version 0.2.18

## Steps to Reproduce
Sorry, the issue was temperamental. Happened only once during a week of playtime.
1. Alt-tab to youtube.
2. Click on a tile.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8598735/Player.log)

NullReferenceException

PeterHan.FastTrack.UIPatches.InterfaceToolPatches.GetIndexedSelectable (System.Collections.Generic.List`1[T] hits, System.Int32& index, System.Int32 layerMask, KSelectable lastSelected) (at <31d58cde6d0a49978403ea3c126bfbd3>:0)
PeterHan.FastTrack.UIPatches.InterfaceToolPatches+OnLeftClickDown_Patch.Prefix (UnityEngine.Vector3 cursor_pos, SelectTool __instance) (at <31d58cde6d0a49978403ea3c126bfbd3>:0)
(wrapper dynamic-method) SelectTool.SelectTool.OnLeftClickDown_Patch1(SelectTool,UnityEngine.Vector3)
PlayerController.OnKeyDown (KButtonEvent e) (at <33cbadb4d53344698461e1b8bda03e57>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputController.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
GameInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
(wrapper dynamic-method) Global.Global.Update_Patch1(Global)

Build: U41-498381-S

**Comment by Raukgorth** [comment]
Happened a second time today.

Now I am sure that I started to right-click and drag while ONI was not activated.

I updated FastTrack to 0.3.1 

NullReferenceException

PeterHan.FastTrack.UIPatches.InterfaceToolPatches.GetIndexedSelectable (System.Collections.Generic.List`1[T] hits, System.Int32& index, System.Int32 layerMask, KSelectable lastSelected) (at <296242012d7a48f5a9f671c1c97fd9ae>:0)
PeterHan.FastTrack.UIPatches.InterfaceToolPatches+OnLeftClickDown_Patch.Prefix (UnityEngine.Vector3 cursor_pos, SelectTool __instance) (at <296242012d7a48f5a9f671c1c97fd9ae>:0)
(wrapper dynamic-method) SelectTool.SelectTool.OnLeftClickDown_Patch1(SelectTool,UnityEngine.Vector3)
PlayerController.OnKeyDown (KButtonEvent e) (at <33cbadb4d53344698461e1b8bda03e57>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputController.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
GameInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
(wrapper dynamic-method) Global.Global.Update_Patch1(Global)

Build: U41-498381-S

**Comment by peterhaneve** [comment]
I believe that this crash, which is indeed related to a conflict with Better Info Cards, has been fixed in 0.3.2.
