### ISSUE TITLE
Lastest FastTrack tag doesn't contain any prebuilt binaries

### ISSUE THREAD

**Issue by maquefel** [peterhaneve/ONIMods#216]
Hello Peter,

Thank you for your wonderful mod, it's really a life saver.

It looks like you forgot to pin latest binary for Fast Track, as i couldn't find any - am i missing something ?

**Comment by peterhaneve** [comment]
The latest release was not set to public. But in the future, if the release tag is not updated, the forum post also has a copy that should be updated.
