### ISSUE TITLE
FastTrack. Crash when using deconstruct tool

### ISSUE THREAD

**Issue by Raukgorth** [peterhaneve/ONIMods#218]
The game crashed when I tried to deconstruct my Gym. Crashed on releasing my mouse butting. I dragged deconstruct tool over a few manual generators, wires and light bulbs.

## Expected Behavior
N/A
## Current Behavior
N/A

## Mod Versions
FastTrack 0.3.3

## Steps to Reproduce
I was unable to reproduce it. After loading the game and selecting the same area to deconstruct the game did not crash.

## Output Log
ArgumentException: Accessing mismatched handle version. Expected version=14 but got version=13

HandleVector`1[T].UnpackHandle (HandleVector`1+Handle[T] handle, System.Byte& version, System.Int32& index) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KCompactedVectorBase.ComputeIndex (HandleVector`1+Handle[T] handle) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KCompactedVector`1[T].GetData (HandleVector`1+Handle[T] handle) (at <53ba8544b0394db88dcaac034e1fe553>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.GetCavityForCell (System.Int32 cell) (at <6fd363e4fc6a480fad1376f574b2adab>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber+GetCavityForCell_Patch.Prefix (System.Int32 cell, CavityInfo& __result) (at <6fd363e4fc6a480fad1376f574b2adab>:0)
(wrapper dynamic-method) RoomProber.RoomProber.GetCavityForCell_Patch1(RoomProber,int)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.UpdateRoom (OvercrowdingMonitor+Instance smi, KPrefabID prefabID) (at <6fd363e4fc6a480fad1376f574b2adab>:0)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.CheckOvercrowding (OvercrowdingMonitor+Instance smi, KPrefabID prefabID, System.Boolean& confined, System.Boolean& cramped) (at <6fd363e4fc6a480fad1376f574b2adab>:0)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.Prefix (OvercrowdingMonitor+Instance smi) (at <6fd363e4fc6a480fad1376f574b2adab>:0)
(wrapper dynamic-method) OvercrowdingMonitor.OvercrowdingMonitor.UpdateState_Patch1(OvercrowdingMonitor/Instance,single)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <53ba8544b0394db88dcaac034e1fe553>:0)
Game.SimEveryTick (System.Single dt) (at <33cbadb4d53344698461e1b8bda03e57>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U41-498381-S

[Player.log](https://github.com/peterhaneve/ONIMods/files/8635667/Player.log)

**Comment by Raukgorth** [comment]
Ok found concrete steps to reproduce the issue.

1. Load my save.
[Fortress.zip](https://github.com/peterhaneve/ONIMods/files/8639683/Fortress.zip)

2. Wait for these tiles to solidify.
![image](https://user-images.githubusercontent.com/98063793/167124932-bf5abeb7-272b-44d1-a1ee-878a7a804f65.png)

3. Deconstruct or build a tile in that room.
![image](https://user-images.githubusercontent.com/98063793/167125083-f01bed33-5602-492b-8aed-cd156af99cea.png)
4. Crash
![image](https://user-images.githubusercontent.com/98063793/167125137-97e93737-3f22-4762-b524-ee150dbaee28.png)

**Comment by peterhaneve** [comment]
If any background room prober issues can still be reproduced after version 0.3.4, please file a new issue.
