### ISSUE TITLE
Insulated Airlocks

### ISSUE THREAD

**Issue by lex-murden** [peterhaneve/ONIMods#219]
Hi, would you be willing to make the airlock door insulated? If not, would it be okay if I made the change and published it in the workshop giving you all the due credit?

**Comment by lex-murden** [comment]
I reckon you said that although there is vacuum between the doors, temperature could be transferred through the backwall, but I would hope my dupes would build the backwall out of insulated tiles at least.

**Comment by peterhaneve** [comment]
Insulating the Airlock Door is not currently on the roadmap. However, the code is available under the MIT License. Perhaps [this fork](https://github.com/ragzilla/InsulatedAirlockDoor) would be helpful?
