### ISSUE TITLE
FastTrack: Building Pneumatic Doors can't properly make a room.

### ISSUE THREAD

**Issue by DolphinWing** [peterhaneve/ONIMods#220]
Building Pneumatic Doors can't properly make a room. Not sure if that is related to other mods but when testing how to properly trigger the room detection, it crashed.

Long story: I was moving critters to a small room but can't make the game detected as a room. I tries to build doors to make a closed room but it was not detected. So I use tiles to the same place I want to put doors. The game detected it was a closed area and become a room. So I try to build a door next to the tiles and try to destruct the tile and the game crashed.

I have some small clips in Twitch and hope that helps.
First found the area was not treated as a room: https://www.twitch.tv/videos/1476701124
Build tiles at the same place becomes a room: https://www.twitch.tv/videos/1476701123
Try to remove tiles next to a door and crash: https://www.twitch.tv/videos/1476701125

## Expected Behavior
When building a Pneumatic Door to enclose a area, it should become room.

## Current Behavior
A newly built Pneumatic Doors was not treated as a room boundary.

## Mod Versions
Fast Track 0.3.3

Other enabled mod: Better Info Cards, Fast Save, Mod Updater and language packs.

## Steps to Reproduce

1. Enclose a area with doors.
2. Check room layout.
3. Destruct a door and change it to tiles.
4. Check room layout again.
5. Check https://www.twitch.tv/videos/1476701122

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8642356/Player.log)
[Player.log](https://github.com/peterhaneve/ONIMods/files/8642462/Player.log)

**Comment by DolphinWing** [comment]
This issue has similar error exception to #218

**Comment by peterhaneve** [comment]
If any background room prober issues can still be reproduced after version 0.3.4, please file a new issue.
