### ISSUE TITLE
Fast Track: Bacground Room Prober crash

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#221]
## Expected Behavior

No crashes

## Current Behavior

Game crashed with an error about the background room prober and then the log is the same error over and over.

## Mod Versions

v0.3.3
## Steps to Reproduce

Don't have any I was just playing when it crashed. Hope the log helps!

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8643801/Player.log)

**Comment by peterhaneve** [comment]
If any background room prober issues can still be reproduced after version 0.3.4, please file a new issue.
