### ISSUE TITLE
FastTrack, Crash when re-sizing my nature reserve

### ISSUE THREAD

**Issue by Raukgorth** [peterhaneve/ONIMods#222]
Still crashes in 0.3.4 when resizing rooms.

## Expected Behavior
N/A

## Current Behavior
N/A

## Mod Versions
FastTrack 0.3.4

## Steps to Reproduce
1. Change the boundaries of a room.

## Output Log
ArgumentException: Accessing mismatched handle version. Expected version=6 but got version=5

HandleVector`1[T].UnpackHandle (HandleVector`1+Handle[T] handle, System.Byte& version, System.Int32& index) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KCompactedVectorBase.ComputeIndex (HandleVector`1+Handle[T] handle) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KCompactedVector`1[T].GetData (HandleVector`1+Handle[T] handle) (at <53ba8544b0394db88dcaac034e1fe553>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.GetCavityForCell (System.Int32 cell) (at <0f723abc7ae5449492b75b7f57472e21>:0)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.UpdateRoom (OvercrowdingMonitor+Instance smi, KPrefabID prefabID) (at <0f723abc7ae5449492b75b7f57472e21>:0)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.CheckOvercrowding (OvercrowdingMonitor+Instance smi, KPrefabID prefabID, System.Boolean& confined, System.Boolean& cramped) (at <0f723abc7ae5449492b75b7f57472e21>:0)
PeterHan.FastTrack.CritterPatches.OvercrowdingMonitor_UpdateState_Patch.Prefix (OvercrowdingMonitor+Instance smi) (at <0f723abc7ae5449492b75b7f57472e21>:0)
(wrapper dynamic-method) OvercrowdingMonitor.OvercrowdingMonitor.UpdateState_Patch1(OvercrowdingMonitor/Instance,single)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <53ba8544b0394db88dcaac034e1fe553>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <53ba8544b0394db88dcaac034e1fe553>:0)
Game.SimEveryTick (System.Single dt) (at <33cbadb4d53344698461e1b8bda03e57>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U41-498381-S
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/8644784/Player-prev.log)

**Comment by peterhaneve** [comment]
All efforts to reproduce this bug have been futile. It is likely specific to your machine.

I added more debug information if this crashes again in 0.3.5. Please open a new issue with a new log if it does.

**Comment by Raukgorth** [comment]
Hey Peter,

Thanks for investigating this. I can confirm that on 0.3.5 method described in #218 doesn't crash the game for me too.

**Comment by peterhaneve** [comment]
I finally managed to reproduce this one locally and made a more lasting fix for the next version.
