### ISSUE TITLE
Fast Track (v0.3.4): Radbolt Reflectors absorb bolts wrongly

### ISSUE THREAD

**Issue by Lapin237** [peterhaneve/ONIMods#223]
## Current Behavior
![This reflector absorbs what it shoots](https://user-images.githubusercontent.com/93446350/167252004-24853890-3b79-44ac-b462-c8874941626b.png)
(pic: This reflector absorbs what it shoots.)
Reflectors absorb bolts wrongly.
I recorded videos to show the bug: 
In my base
https://1drv.ms/v/s!An8CbmCj9Lkag6xV0cbTeST035TqqA?e=UcS0e7
My reproducing
https://1drv.ms/v/s!An8CbmCj9Lkag6xWsy93ThYzTNzGUQ?e=dGGtMk

When I recorded the videos, there were other mods active. Then, I turned off all other mods and tried again, and the wrong behavior remains.

## Mod Versions
Local copy of v0.3.4

## Steps to Reproduce
1. Build a radbolt reflector as I do in the picture.
2. Shoot a radbolt to it.
3. It will absorb the radbolts from itself.

## Output Log
(This isn't a crash. Do I need to upload the log?)
[Player.log](https://github.com/peterhaneve/ONIMods/files/8645012/Player.log)

**Comment by peterhaneve** [comment]
The rounding error that causes different up/down behavior with radbolts passing through tiles also apparently effects the absorption cell. This issue has been fixed in 0.3.5.
