### ISSUE TITLE
Fast Track not compatible with Spaced Out! DLC

### ISSUE THREAD

**Issue by Bazeloth** [peterhaneve/ONIMods#224]
## Expected Behavior

I expect this to be compatible with the Spaced Out! DLC. According to this forum post:
![image](https://user-images.githubusercontent.com/19928782/167307179-0d79b9a3-19e2-4a79-adad-b57442cf4c77.png)
at https://forums.kleientertainment.com/forums/topic/138444-beta-fast-track-performance-mod-for-oxygen-not-included/

## Current Behavior

It is not. See screenshot: 
![image](https://user-images.githubusercontent.com/19928782/167307025-f3bf7a9c-df5d-42fd-b474-a5143b161c2b.png)

## Mod Versions

Local copy.

## Steps to Reproduce

1. Go to https://github.com/peterhaneve/ONIMods
2. Download the zip file
3. Extract the Fast Track to the /local/ folder 
![image](https://user-images.githubusercontent.com/19928782/167307080-e8674f74-2695-42ee-9472-003455e6fcb6.png)
4. Start the game. Go to Mods in the menu and see this:
5. ![image](https://user-images.githubusercontent.com/19928782/167307093-f095d7e7-fcfa-493c-9902-34c61c9ebcd0.png)

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8647424/Player.log)

**Comment by peterhaneve** [comment]
Fast Track is not correctly installed. Either you checked out the source code instead, or have nested the Fast Track folder. Make sure that the `FastTrack` folder in the local mods directory has the DLL file in it.

**Comment by Bazeloth** [comment]
I took the release with the dll and booted up the game. At first Fast Track was disabled:
![image](https://user-images.githubusercontent.com/19928782/167316215-6a62f508-3862-4220-ae61-bd24a63f9a3f.png)

I enabled it and clicked Close -> Restart:
![image](https://user-images.githubusercontent.com/19928782/167316233-ba9df536-35b1-4473-8dc4-08959ee176ba.png)

Then this occurred:
![image](https://user-images.githubusercontent.com/19928782/167316253-76ab8e6f-3e8a-47cb-a784-d3e52cbbde8e.png)

Here are the logs:
[Player.log](https://github.com/peterhaneve/ONIMods/files/8647819/Player.log)

Want me to make a new issue?

**Comment by dynam1c-afk** [comment]
This also happens to me
