### ISSUE TITLE
Game crash using Fast Track

### ISSUE THREAD

**Issue by Bazeloth** [peterhaneve/ONIMods#225]
A crash screen occurred.

## Expected Behavior

Spaced Out! DLC is installed -> public branch

## Current Behavior

The game crashed:
![image](https://user-images.githubusercontent.com/19928782/167483767-d7c790e5-87bf-469e-923c-c7a5af202788.png)

## Mod Versions

Local. Havent tried a force mod updater

## Steps to Reproduce

1. Build a room with 2 pneumatic doors
2. Finish building it

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8654782/Player.log)

**Comment by peterhaneve** [comment]
This issue should have been fixed in the recent 0.3.6 release. It appears that you are still using 0.3.5, so see if it reproduces on the latest version.
