### ISSUE TITLE
FastTrack: Crash while rebuilding a cooling loop

### ISSUE THREAD

**Issue by Raukgorth** [peterhaneve/ONIMods#228]
I'm not sure what exactly I have done to trigger this one.

## Expected Behavior
N/A
## Current Behavior
N/A

## Mod Versions
local 0.3.6

## Steps to Reproduce
Not yet known. If I manage to reproduce will update.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8664717/Player.log)

**Comment by peterhaneve** [comment]
All attempts to reproduce this issue have failed. Nevertheless, I added yet another check in 0.3.7 to try and prevent a crash when this rare case actually does occur.
