### ISSUE TITLE
ONI Mod updater out date

### ISSUE THREAD

**Issue by SonGoku83** [peterhaneve/ONIMods#229]
Just want to inform you that your mod updater for Oxygen not includet is not working any more and game mark the mod in red 
have a nice day ;) keep up with the good work for the comunity

**Comment by Bazeloth** [comment]
Did you try the latest version? He recently released a new one. By the way @peterhaneve i love the Fast Track mod; it has improved the performance by a ton!

**Comment by zheng-shi** [comment]
It's likely that your online mod updater needs to be updated by mod updater. You can install both the online and local version of the mod updater, first activate the local one such that the online one will be updated. Then you can uninstall the local one and activate the online version.

**Comment by peterhaneve** [comment]
Steam does not usually auto-update mods. Most users will probably need to [manually install](https://github.com/peterhaneve/ONIMods/blob/main/README.md) Mod Updater to update all mods again.
