### ISSUE TITLE
SweepByType doesn't apply symbol overrides

### ISSUE THREAD

**Issue by daviscook477** [peterhaneve/ONIMods#23]
Reproduction:
1. Spawn in a bunch of different shine bug morph eggs (e.g. shine bug egg and sun bug egg).
2. Open menu for sweep by type
3. All of the eggs will appear as the base shine bug egg

My guess is that sweep by type is just taking the base sprite but it needs to somehow check if that thing should have a symbol override prefix and then take a different sprite

**Comment by peterhaneve** [comment]
Should be fixed in a27333c
