### ISSUE TITLE
Fast track + Waste not Want not can cause dupes starve to death

### ISSUE THREAD

**Issue by zheng-shi** [peterhaneve/ONIMods#230]
## Expected Behavior
Dupe eats food if available, or a starving warning should pop up if there's no food available

## Current Behavior

Dupe would starve to death without any warning, when there's plenty of food available. It stops happening if I turn off either mods.

## Mod Versions

[mods.txt](https://github.com/peterhaneve/ONIMods/files/8671633/mods.txt)

## Steps to Reproduce

1. activate both fast track and waste not want not mods
2. have different types of food available
3. some dupes usually starve to death within 10 cycles

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8671596/Player.log)

<!--- Provide a general summary of the issue in the Title above -

->

**Comment by peterhaneve** [comment]
All attempts to reproduce this issue have failed. It is likely specific to your machine, or to Mac/Linux versions of ONI.

Does disabling "Flatten Averages" in the Fast Track options fix the issue for you?

**Comment by zheng-shi** [comment]
Hey, thank you for looking into it. There's still something odd going on regarding food detection after I turn off Flatten Average. Here's a save game file. If I have both mods on, the priority 9 fridge in the rocket Brave Vessel III shows no delivery available while there's a priority 6 fridge full of berry sludge. Problem solved I turn off the waste not want not mode.
[FlippedMax - Brigade.sav.zip](https://github.com/peterhaneve/ONIMods/files/8679931/FlippedMax.-.Brigade.sav.zip)

**Comment by peterhaneve** [comment]
There was an off-by-one bug in async amount updates that could have caused bugs similar to this one that has been fixed in Fast Track 0.3.8.

If you use the _Minimum Freshness_ slider on food storage in Waste Not Want Not, the way that the base game batches fetch errands can cause unusual behavior with Duplicant deliveries. This slider is best used for Auto-Sweeper only.
