### ISSUE TITLE
Algea not being delivered to Oxygen Diffuser

### ISSUE THREAD

**Issue by Bazeloth** [peterhaneve/ONIMods#231]
## Expected Behavior

I expect dupes to deliver Algae to the Oxygen Diffuser. Had to deconstruct the storage bin, then sweep it in order for them to pick it up.

I also tried rebuilding the Oxygen Diffuser, but something's off. Its made out of copper and theres a piece of copper right here:
![image](https://user-images.githubusercontent.com/19928782/167942144-326f514c-fc27-4628-bf18-508823cb2bd7.png)

Except for some strange reason it says 'no pending deliveries':
![image](https://user-images.githubusercontent.com/19928782/167942399-9ba78ae8-7583-4776-a39b-4c7bb9431fa8.png)

## Current Behavior

Dupes are being idle. They also like to be idle in a place where there's little to no oxygen. I see them holding their breath a lot, then they almost suffocate and move to a tile with oxygen.

## Mod Versions

Local

## Steps to Reproduce
Maybe it has something to do with the room i've water locked with oxygen masks?
![image](https://user-images.githubusercontent.com/19928782/167942700-467e3814-414f-4110-80ec-bfc17a318056.png)

## Output Log

I cant include the log file, for some reason it's massive:
![image](https://user-images.githubusercontent.com/19928782/167942891-f867d380-e31b-4909-aadd-3757021dcec8.png)

This is probably the cause of some stutters i'm seeing as well.

**Comment by Bazeloth** [comment]
Deleted the log file. Restarted the game. They started building the oxygen diffuser. Something is def wrong with the pathing. Not sure if it's the Fast Track mod.

**Comment by peterhaneve** [comment]
There is likely spam in the log file, can you include the last 1000 lines? Also make sure that you are using the latest version of the mod, as many similar - issues were fixed early in the 0.3.x series.

**Comment by Bazeloth** [comment]
[NewSplitFile-1.txt](https://github.com/peterhaneve/ONIMods/files/8673511/NewSplitFile-1.txt)
[NewSplitFile-7390.txt](https://github.com/peterhaneve/ONIMods/files/8673519/NewSplitFile-7390.txt)

Here is the first and the last 1000 lines of the file. Found it in the bin. Luckily i didn't shift + delete it. Memory issues, but i cant tell the root cause.

**Comment by Bazeloth** [comment]
> There is likely spam in the log file, can you include the last 1000 lines? Also make sure that you are using the latest version of the mod, as many similar - issues were fixed early in the 0.3.x series.

Im at version 3.7
![image](https://user-images.githubusercontent.com/19928782/167950382-69a9acc8-868e-4994-8b47-dc669a7cbf1c.png)

**Comment by Bazeloth** [comment]
`[16:05:24.482] [1] [WARNING] True Timelapse.OnNewDay but worldsToScreenshot is not empty` seems suspicious? could it be the cause of the memory issues?

**Comment by peterhaneve** [comment]
You are unfortunately pretty clearly out of memory for ONI. It happened to first run out in Fast Track code, but the whole game was affected as you can tell.

The latest public testing branch does fix several major memory leaks in the base game. Until it goes live, you should probably quit and restart ONI every few cycles to free memory.

**Comment by Bazeloth** [comment]
Alright thank you for explaining. Some may play only a couple of cycle at a time, but i let it run at the fastest pace mostly. It's not uncommon  for me to let the game run for 200 cycles. According to a reddit post from 2 years ago it has a bug where it collects a game snapshot right before saving, but it never gets cleaned up:

https://www.reddit.com/r/Oxygennotincluded/comments/fbti14/oxygen_may_not_be_included_but_memory_leaks_are/

I've never had pathing/gathering supplies problem before though. I'll follow your advice and restart the game rom the time to time. Do you have an indicator when the public testing branch would go live?

**Comment by peterhaneve** [comment]
After inspecting the code there are indeed some excess memory allocations in Fast Track, which I have fixed in 0.3.8. You may be able to run the game for longer now without a crash.
