### ISSUE TITLE
ModUpdater crash the game after install in new mod

### ISSUE THREAD

**Issue by nowing** [peterhaneve/ONIMods#232]
After I install a new mod from Steam, the ModUpdater crash the game. In the crash screen, keep ModUpdater active and restart the game, it will work normally.

## Expected Behavior
Install a new mod from Steam should not crash the game.
Have the Spaced Out! DLC installed.

## Current Behavior
After I install a new mod from Steam, the ModUpdater crash the game. 

## Mod Versions
Using Steam subscription, ModUpdater  v2.8.0.0

## Steps to Reproduce

1. Install a new mod from Steam
2. Return to game screen
3. Game crashed, and the ModUpdater is red.
4. Keep ModUpdater active and restart the game, it's ok.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8683455/Player.log)

**Comment by peterhaneve** [comment]
All attempts to reproduce this issue have failed. But I have added additional checks which may prevent the issue from occurring in the first place in version 2.9.

**Comment by peterhaneve** [comment]
I think that I finally tracked this one down to a race condition with Steam registering the mod as Installed *between* the Add and Update calls (it needs almost frame perfect precision!)
