### ISSUE TITLE
Random Crash on Vanilla ONI with lot of mods, ONI blames FastTrack

### ISSUE THREAD

**Issue by Prince-Mandor** [peterhaneve/ONIMods#233]
This happens on stable branch Vanilla game (Spaced Out! DLC installed, but turned off). 

## Mod Versions

FastTrack Version 0.3.8

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8694591/Player.log)

**Comment by peterhaneve** [comment]
The game will always blame Fast Track for all crashes even if it is not involved. I see a lot of `[WARNING] Writing large string   at RocketModule.DEBUG_OnDestroy (System.Object data) [0x00000] in <ab4bdc425be2489bb8a9b667082958c0>:0 
  at RocketModule+<>c.<.cctor>b__32_2 (RocketModule component, System.Object data) [0x00000] in <ab4bdc425be2489bb8a9b667082958c0>:0` before the crash in the log, which suggests that something is not quite right with one of your rocket modules. If you can reproduce a particular circumstance where the crash occurs every time, please add that information.

**Comment by Prince-Mandor** [comment]
Well, it is random crash, so I cannot reproduce circumstances. And there was no such crashes in half a year before. They became frequent only after FastTrack installation. But possibly this is just reaction of some old mod on increased speed.
Thank you anyway

**Comment by maquefel** [comment]
Funny thing, but i am currently also experience much more frequent crashes today, just after i installed the latest Windows 10 update. I've been playing with FastTrack for about a while - two weeks or so, and haven't experienced crashes so often.

**Comment by peterhaneve** [comment]
All attempts to reproduce this crash have failed, but I split up the location queues in [d2ac687](https://github.com/peterhaneve/ONIMods/commit/d2ac6877ce8d1ae92283a4403eccc4e7618b1e2f) which might reduce races on the background room prober.

**Comment by maquefel** [comment]
@Prince-Mandor looks like i found the reason for such crashes - did you mine or shave neutronium ?
I've debugged mined a piece of neutronium, and after i reloaded with save before mining it, crashes dissapeared.

**Comment by Prince-Mandor** [comment]
Okay, I no longer have this crashes after 0.3.9 update. So, issue can be considered closed
