### ISSUE TITLE
[Spaced Out] Fast Track crash when entering the temporal tear

### ISSUE THREAD

**Issue by antoine-fresse** [peterhaneve/ONIMods#234]
Pretty self explanatory, probably something to do with the destroyed rocket rooms

## Mod Versions
Fast Track 0.3.7.0 

## Steps to Reproduce
1. Enter Temporal Tear
2. Click Proceed
3. Crash

Disabling Fast Track fixes the issue

## Output Log
NullReferenceException: Object reference not set to an instance of an object

PeterHan.FastTrack.GamePatches.BackgroundRoomProber.UpdateRoom (CavityInfo cavity) (at <1fd10e9e51644a638dcc236d818f2806>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.RefreshRooms () (at <1fd10e9e51644a638dcc236d818f2806>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.Refresh () (at <1fd10e9e51644a638dcc236d818f2806>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber+Refresh_Patch.Prefix () (at <1fd10e9e51644a638dcc236d818f2806>:0)
(wrapper dynamic-method) RoomProber.RoomProber.Refresh_Patch1(RoomProber)
Grid.FreeGridSpace (Vector2I size, Vector2I offset) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ClusterManager.DeleteWorldObjects (WorldContainer world) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ClusterManager+<>c__DisplayClass51_0.<DestoryRocketInteriorWorld>b__3 (System.Object obj) (at <33cbadb4d53344698461e1b8bda03e57>:0)
Scheduler.Update () (at <33cbadb4d53344698461e1b8bda03e57>:0)
GameScheduler.Update () (at <33cbadb4d53344698461e1b8bda03e57>:0)

Build: U41-498381-S

The rocket rooms if that matters : 
![image](https://user-images.githubusercontent.com/5739266/169668713-b0f80604-dfd8-475c-b42d-a4a530dc70f5.png)

Thank you for the great work

**Comment by peterhaneve** [comment]
While I think that I figured the cause of this one out, I will wait to actually fix it until the public testing branch is released, as this section of code already differs in the upcoming game patch.
