### ISSUE TITLE
please update the ONI mod updater

### ISSUE THREAD

**Issue by DarkHunter65** [peterhaneve/ONIMods#235]
numerous ONI mods require the mod updater, but when it is enabled, since it is out of date it does not appear on the list of mods that causes a game crash in the "whoops a daisy" crash screen. please update the mod.
P.S: im sorry for probably leaving out vital information, i have no idea how github works
Sincerely, a person that likes video games[
1. enable mod updater and mod that requires it (example: germicidal UV lamps)
2. restart game as required
3. crash

**Comment by peterhaneve** [comment]
It looks like you will need to manually install Mod Updater, as ONI is giving you a version of Mod Updater over six months old. Manual installation instructions are available on [this website](https://github.com/peterhaneve/ONIMods/blob/main/README.md). To satisfy the dependency, remove the local version and turn on the Steam version once all Steam mods have been force updated.
