### ISSUE TITLE
Farm tiles show plants with 0 seeds colored instead of grayish

### ISSUE THREAD

**Issue by AndreDroschinsky** [peterhaneve/ONIMods#239]
When selecting a plant tile, all plants are shown colored, even those with 0 seeds

## Expected Behavior
Plants without seeds should be grayish
Spaced Out! DLC, Build 509629

## Current Behavior
All plants are shown colored, even those with 0 seeds. Only after clicking them, these plants are colored grayish.

## Mod Versions
FastTrack 0.9.0 from Github

## Steps to Reproduce
Build a farm tile, select a seed, and see the color for plants with 0 seeds.

Below are two screenshots, the first with FastTrack and Arbor Acorn clicked. Dasha Saltvine is colored.
The second is without the FastTrack Mod and without clicking on any plant.

![FarmTilesWithFastTrack](https://user-images.githubusercontent.com/67025442/171918596-3d174127-8edd-4ec4-9054-71bef573c3e2.png)
![FarmTilesWithoutFastTrack](https://user-images.githubusercontent.com/67025442/171918606-c412bd4a-8e40-40f4-9f60-1a1a2c2efcbf.png)

**Comment by peterhaneve** [comment]
This issue should be fixed in version 0.9.1.
