### ISSUE TITLE
Thermal Interface Plate don't transfer heat between each other

### ISSUE THREAD

**Issue by WardenCommander** [peterhaneve/ONIMods#24]
Thermal Interface Plate don't transfer heat between each other is this intended or could it be made possible? also it dont transfer heat with Tempshift Plate

**Comment by peterhaneve** [comment]
Thermal Interface Plate will not transfer heat to neighboring Thermal Interface Plates, as its area of effect is only 1x1 for performance reasons.

The latest version of Thermal Interface Plate _can_ transfer heat to neighboring Tempshift Plates, as Tempshift Plate has a 3x3 area of effect. If heat is not transferring, try disabling the Steam version and using a [local copy](https://github.com/peterhaneve/ONIMods/releases/tag/ModsLatest), as Steam does not always update mods correctly.
