### ISSUE TITLE
mod updater crash on startup [Game Hotfix] - 510738 and 510972 {no beta branch}

### ISSUE THREAD

**Issue by tonimark** [peterhaneve/ONIMods#241]
when the mod updater alone is installed the game crashes on startup
## Expected Behavior

the game would normally start

DLC not bought and not installed
## Current Behavior

the game crashes
## Mod Versions
using the subscribed steam edition the game reports it as v2.4.0.0
is not possible to update itself due to the mod itself just crashing

## Steps to Reproduce

1.install the mod updater [subscribe through steam]
2.enable the mod through the list (mods button)
3.launch the game
4.see the error

## Output Log
the output log is outaded , not generated

[Player.log](https://github.com/peterhaneve/ONIMods/files/8893602/Player.log)

also a crash log:
[crash.txt](https://github.com/peterhaneve/ONIMods/files/8893604/crash.txt)

**Comment by peterhaneve** [comment]
This version of Mod Updater is over a year out of date. If verifying game files does not fix the issue, you need to install a local copy.
