### ISSUE TITLE
Debris on top of the door cannot be retrieved

### ISSUE THREAD

**Issue by MarceloLaser** [peterhaneve/ONIMods#242]
If debris falls on top of an airlock door and there are no ways to access it from above, dupes will not climb the door or otherwise be able to reach the debris. This effectively causes some debris to be permanently stuck on top of doors in certain situations. Image example is attached.

<img width="526" alt="Capture" src="https://user-images.githubusercontent.com/7095289/175762482-8f32be75-ea9b-4b42-b63d-d32c6e711a9d.PNG">

## Expected Behavior
I have Spaced Out! installed, but this happens in the base game. Using the latest public Steam version. Preferable solution would be for dupes to be able to climb the airlock door, like they do with normal doors. Admissible solution would be for the debris to fall into the door, or be pushed to the side so as to fall in front of it in either side.

## Current Behavior
Debris gets stuck on top of door, dupes will not climb it.

## Mod Versions
Using Steam subscription, but updated today using mod updater.

## Steps to Reproduce
1. Build an entry two tiles high, with two tiles on top of one of its sides, and four tiles above it as if to create a ceiling.
2. Build any object immediately next to the wall section, on the inside, such as a wire.
3. Build the airlock door.
4. Deconstruct the object above the airlock door.
5. Debris from the deconstruction is now stuck on top of the door unless a ladder is placed immediately in front of it.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8984066/Player.log)

**Comment by peterhaneve** [comment]
Unfortunately, due to how Oxygen Not Included pathfinding is coded, adding a jump up to the top of the door is not possible. If that transition was valid, Duplicants could also jump out of the middle of the airlock up to the top, confusing the Duplicant vacuuming and queuing logic.
