### ISSUE TITLE
Crash on mismatched handle version

### ISSUE THREAD

**Issue by aznboy84** [peterhaneve/ONIMods#243]
FAST TRACK !

This error, A.K.A please update your mod : "ArgumentException: Accessing mismatched handle version. Expected version=70 but got version=69"

## Expected Behavior

Let the game run at it will happen after a couple cycles.

Base game

## Current Behavior

Expected it to not crash.

## Mod Versions

Using steam.

## Steps to Reproduce

1. Let the game run.
2.
3.
4.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/9076218/Player.log)

**Comment by peterhaneve** [comment]
All efforts to reproduce this bug have failed. It is likely machine specific.

Nevertheless, a few more synchronization locks have been added to 0.9.4 which may mitigate the issue.
