### ISSUE TITLE
Buildings ranges mod causes error (was working up until 2022)

### ISSUE THREAD

**Issue by dcasez** [peterhaneve/ONIMods#244]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by dcasez** [comment]
I'll test again when I get home later today or tomorrow but seems to have a problem with the last update.  I play vanilla.

**Comment by dcasez** [comment]
seems like it might be fine, didnt get an error on new colony... will close issue out for now.

**Comment by peterhaneve** [comment]
If it crashes again, make sure to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force an update.
