### ISSUE TITLE
FastTrack: "Find Safe Area" duplicant task never created while idle

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#246]
## Expected Behavior

Duplicants that cannot breath when they go idle should trigger the "Find Safe Area" task and move to a breathable location

Spaced Out! is active

## Current Behavior

Duplicants who go idle in the vacuum of space never trigger the "Find Safe Area" task causing them to idle far away from breathable areas until there lack breath triggers the "Recover Breath" task. I believe this also impacts duplicants going idle in non-breathable areas, but I have not tested that one as well as the space biome. Turning off FastTrack allows the duplicant to trigger "Find Safe Area" task.

## Mod Versions

Local, v0.9.3

## Steps to Reproduce

1. Move an idle duplicant to the space biome without any o2 available with a path back to o2 available
2. Watch them stand there until breath triggers "Recover Breath"

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/9096452/Player.log)

**Comment by peterhaneve** [comment]
It turns out that querying for safe cells was racy depending on the order in which potential safe cells were iterated. While it may be slightly slower, the completion condition has been updated in 0.9.4 to only exit if a full match is found.
