### ISSUE TITLE
FastTrack: Electrical Optimizations prevents equipment from running on battery

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#247]
## Expected Behavior

When solar panels are not providing power to a network but there is a charged battery present in the network equipment should function until the battery dies.

Spaced Out! Active

## Current Behavior

When solar panels do not provide enough power to run the total power consumption of the active equipment, the active equipment acts like there is only the amount of power available that is being produced by the generators even though there is more power in the batteries on the network to run everything. Then at night all active equipment connected to the charged battery does not operate.

## Mod Versions

Local, v0.9.3

## Steps to Reproduce

1.Make sure "Electrical Optimizations" are enabled in FastTrack 
2.Load the attached save
3.Note the charged jumbo battery in the middle of the screen and the "no power" equipment attached to it
4.Wait for morning and see the equipment turn on only as the solar starts to flow in
5.Turn off "Electrical Optimizations" to see the equipment work off of battery

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/9096914/Player.log)
[The Smart Trainwreck_Electircal.zip](https://github.com/peterhaneve/ONIMods/files/9096930/The.Smart.Trainwreck_Electircal.zip)

**Comment by peterhaneve** [comment]
This turned out to be a component update order issue that only occurred on networks with a mix of dead and charged batteries/generators. Most instances should be fixed in 0.9.4.
