### ISSUE TITLE
[Forbid Items] Persistence between sessions

### ISSUE THREAD

**Issue by MegaJani** [peterhaneve/ONIMods#248]
## Expected Behavior
Forbidden items should stay forbidden the next time one loads the save file.

## Current Behavior
They do not.

## Mod Versions
Steam version, force updated, vanilla game.

**Comment by peterhaneve** [comment]
This is a base game bug with an incorrect order of operations when removing serialized tags. Until Klei fixes it, I have added a workaround in version 1.1.

**Comment by Bazeloth** [comment]
"Forbidden" items? Such as?
