### ISSUE TITLE
[Automated Colony] Add Configurability.

### ISSUE THREAD

**Issue by TheFantasticLoki** [peterhaneve/ONIMods#249]
## Expected Behavior

This mod should have some form of config to tone down certain buildings in the game especially the super sweeper which has a rediculous range by default. Customize buildings has a function for this to adjust the auto sweeper range and adds an ingame adjustment slider which would be incredibly useful for the super sweeper to reduce on lag not to mention adding some form of power draw if we wanted. I haven't even touched the other buildings which I assume are similarly broken but all I wanted was the through tile capability of the super sweeper to make a more efficient storage design/expand slightly but the range is so massive it's nearly unworkable for normal use.

Yes I have and am using the spaced out dlc but no preview branch
## Current Behavior

Currently no way to configure the mod whatsoever.
## Mod Versions

Using steam subscription and I am on latest version of mod.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by peterhaneve** [comment]
This repository is not the right place to report issues with the mod "Automated Colony". Consider reporting it on the thread linked in the mod description, https://forums.kleientertainment.com/forums/topic/113661-mods-rainbowdesigns-mods/.
