### ISSUE TITLE
Severe Lag most times not responding on unpausing time sometimes on pausing too after installing FastTrack Beta

### ISSUE THREAD

**Issue by TheFantasticLoki** [peterhaneve/ONIMods#250]
When unpausing time in game after having been paused for a while like multiple minutes say while planning a build the game will freeze for 15-30 seconds then proceed as normal. only started occuring after installing fasttrack.

## Expected Behavior

Would like to be instructed on how I can give in-depth diagnostics required to debug as not familiar with how mods work in THIS game. Potentially get this resolved fast but my game is pretty heavily modded but I also feel that is what an optimization mod is for.

Yes I have the Spaced Out DLC and I am currently using it along with the latest (Stable?) build.

## Current Behavior

Unpause time after waiting for a few minutes, game freezes for 15-30sec.

## Mod Versions

latest beta release from github.

## Steps to Reproduce

1.
2.
3.
4.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/9160237/Player.log)

**Comment by TheFantasticLoki** [comment]
I disabled fast track entirely after noticing while panning my view slowly to one side my game was stuttering every single second at 1x speed. Game is running smoother after disabling fast track.

**Comment by peterhaneve** [comment]
Something in one of your other mods is crashing:
```
Can't add script behaviour . The script class can't be abstract!
Can't add script behaviour . The script class can't be abstract!
````

Frequent pausing suggests that other mods are excessively allocating memory, causing garbage collection pauses. Unity has a 20 year old garbage collector that is single threaded and stops all tasks while collecting. Given the number of mods you have installed, a mod incompatibility is also not out of the question. Consider disabling other mods to see which one is the culprit.
