### ISSUE TITLE
FastTrack crash on startup.

### ISSUE THREAD

**Issue by MicahZoltu** [peterhaneve/ONIMods#253]
## Expected Behavior
Game doesn't crash on startup.

## Current Behavior
Enabling FastTrack 0.9.4 with Spaced Out! and restarting ONI results in a crash during startup, before the main menu.

## Mod Versions
Local copy, FastTrack 0.9.4 downloaded from GitHub.

## Steps to Reproduce
1. Copy FastTrack 0.9.4 to local mods folder.
2. Launch ONI.
3. Enable FastTrack mod.
4. Restart ONI.
5. Crash on startup.
6. Disable FastTrack mod by removing it from `mods.json`.
7. Launch ONI.
8. Notice it no longer crashes.

## Output Log
Note: Some minor personal details were redacted from the log (e.g., folder names and usernames).
[Player.log](https://github.com/peterhaneve/ONIMods/files/9197315/Player.log)

## Additional Details
I have other mods installed (all yours), but no others enabled.

Screenshot of crash:
![image](https://user-images.githubusercontent.com/886059/181220859-0f89c846-0d6d-4033-a98b-0da53a051840.png)

**Comment by peterhaneve** [comment]
It looks like you have a copy of Oxygen Not Included from the Epic Games Store. As this version of the game has slightly different code than the Steam version, it is unfortunately not yet supported by Fast Track. Check back closer to release!

**Comment by MicahZoltu** [comment]
Is there anything that could be done to help speed up integration with the Epic Games version?  I'm a developer and wouldn't mind helping out *a little bit*.  I can't commit too much time, but if there is some simple but tedious task that a modding newb could take on to help out I wouldn't mind.

At the moment, I have quit playing ONI because of the lag issue but would love for this mod to work so I can get back into it!
