### ISSUE TITLE
Fast Track 0.9.6 linux U42-514967-S build crash

### ISSUE THREAD

**Issue by codernk** [peterhaneve/ONIMods#257]
## Expected Behavior
Smooth gameplay without lags

## Current Behavior
Game crashed after some time

## Mod Versions
local mods with Mod Updater
AI Improvements 2.6.0.0
Fast Track 0.9.6.0
Mod Updater 2.10.0.0
Suppress Notifications 2021.6.27.13
Research Queue 3.2.0.0
Show Building Ranges 3.3.0.0
Stock Bug Fix 3.17.0.0
Popup Control 2.4.0.0

## Steps to Reproduce
1. Install Fast Track
2. Play like 10-15 min
3. Game crashed

## Output Log
https://0x0.st/o9Wa.log

**Comment by peterhaneve** [comment]
This issue has already been fixed. Try the latest version of Fast Track.
