### ISSUE TITLE
Toggle Reclaim/Forbid, autosweeper gonna sweep

### ISSUE THREAD

**Issue by zivvel** [peterhaneve/ONIMods#258]
Playing with SO!

I have a pile of hot stuff, and each item is Forbidden.  Autosweeper can reach pile and a conveyer loader.  Loader wants igneous rock, and there is some hot Forbidden igneous in the pile.

## Expected Behavior
Reclaim the igneous rock, let the autosweeper put some in the loader, then Forbid the igneous, then the sweeper should not grab any more.

## Current Behavior
Instead, the sweeper keeps sweeping after the Reclaim/sweep 1t/Forbid dance.

Tried unpowering the sweeper (pliers on the power wire) and re-powering it, but it still sweeps the Forbidden igneous.

## Mod Versions
v1.1.0.0 -- I use Mod Updater

## Steps to Reproduce
Outlined above.

Forbid, Save, and Load seems to reset things so the sweeper will stop.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/9433875/Player.log)
![image](https://user-images.githubusercontent.com/242258/186923842-a46cf22e-7e73-473e-a988-e87e68fd080e.png)

**Comment by peterhaneve** [comment]
This turned out to be a base game bug where the sweeper did not check items it had previously cached to see if they were still fetchable. A somewhat ugly workaround has been added in version 1.2.0.0 (74b5dfc).
