### ISSUE TITLE
Thermal Interface Plate: Unexpected Heat Transfer Behavior

### ISSUE THREAD

**Issue by chris9871** [peterhaneve/ONIMods#260]
## Expected Behavior

When more than one Thermal Interface Plate comes into contact with a building (e.g. a Steam Turbine), each should transfer heat between the building and the TIP.

With Spaced Out, main released version.

## Current Behavior

Having more than one TIP in contact with a building seems to have no additional effect over the first one.  Outcomes:
1. This means that a single Aluminum TIP (and aluminum pipe) can cool a Steam Turbine down sufficiently; and
2. One Gold TIP (and gold pipe) can _almost_ cool down a Steam Turbine (the temp very slowly rises under continuous use); and
3. 2 or more Gold TIPs (with gold pipes) do not appear to have any benefit over a single one.

## Mod Versions

Steam Subscription with 3.7.0.0 (verified in the in-game window).
Mod Update force not tried (it's been at this version for months).

## Steps to Reproduce
1. Create a large room of 200C steam at 10kg pressure (exact pressure doesn't seem to matter).
2. Put 7 blocks of Ceramic Insulation at the top and centre the Steam Turbine on it.
3. Place a Gold Thermal Interface Plate at the bottom-centre-square of the Steam Turbine.
4. Place a cooling loop through the Thermal Interface plate (this should be granite or igneous pipe except at the point where the Thermal Interface Plate is which should be radiant pipe of the same material as the Thermal Interface Plate) which contains a continuous flow of cold water (2-20C makes the problem more obvious).
5. Send the water output of the Steam Turbine away from the Thermal Interface Plate (back into the room is fine) using igneous insulated pipes. 
6. Connect the power output to a lightbulb (or anything to make it go).
7. Watch the temperature of the Steam Turbine.

## Output Log

https://gist.github.com/chris9871/a661cecaadc8af19f1c6259ab7caabf4

**Comment by peterhaneve** [comment]
Thermal Interface Plates, especially made of conductive refined metals, are very good at equalizing heat. They usually far exceed the heat transfer between the liquid in Radiant Pipes and the pipe itself, so adding multiple when using a coolant with a low Thermal Conductivity (like Water) may appear to have almost no effect.

Take a look at https://forums.kleientertainment.com/forums/topic/84275-decrypting-heat-transfer/ for more details, especially the clamping applied when the total energy or heat transferred of two items is very similar.
