### ISSUE TITLE
Add support to hold construction mod to the settings change tool mod

### ISSUE THREAD

**Issue by CMaia1** [peterhaneve/ONIMods#261]
add support to this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2808978019 to the settings change tool

**Comment by peterhaneve** [comment]
Hold Construction is not currently open-source. Until the source code is available, I can do very little to add support. Consider asking the author to put their mod code in GitHub, as work will likely be required on both sides to make this possible.
