### ISSUE TITLE
Testing build crashes on startup with One Giant Leap / MoreAchievements

### ISSUE THREAD

**Issue by meekay** [peterhaneve/ONIMods#262]
## Current Behavior
Using the new test build that just came out (U43-522820-S), the game crashes on startup applying the MoreAchievements patch. Disabling One Giant Leap prevents the crash.

## Expected Behavior
It should not crash, and also there should be extra awesome achievements.

## Mod Versions
Oh Lordy, there are mods. See attached Player.log for details.

## Steps to Reproduce
1. Start Oxygen Not Included
2. Alas.

## Output Log
[PLib/MoreAchievements] Error running patches for stage AfterDbInit:

UnityEngine.Debug:LogErrorFormat (string,object[])
Debug:LogErrorFormat (string,object[])
PeterHan.PLib.Core.PUtil:LogError (object)
PeterHan.PLib.PatchManager.PPatchManager:Process (uint,object)
PeterHan.PLib.Core.PRemoteComponent:Process (uint,object)
PeterHan.PLib.Core.PRemoteComponent:Process (uint,object)
PeterHan.PLib.Core.PForwardedComponent:InvokeAllProcess (uint,object)
PeterHan.PLib.PatchManager.PPatchManager:Initialize_Postfix ()
(wrapper dynamic-method) Db:Db.Initialize_Patch2 (Db)
Db:Get ()
Assets:CreatePrefabs ()
Assets:OnPrefabInit ()
KMonoBehaviour:InitializeComponent ()
KMonoBehaviour:Awake ()
UnityEngine.Object:Instantiate<UnityEngine.GameObject> (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform)
Util:KInstantiate (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.GameObject,string,bool,int)
Util:KInstantiate (UnityEngine.GameObject,UnityEngine.GameObject,string)
LaunchInitializer:Update ()

Build: U43-522820-S

[Player.log](https://github.com/peterhaneve/ONIMods/files/9579810/Player.log)

**Comment by peterhaneve** [comment]
There is no support for the public testing branch on any mod in this repository, due to the rapid frequency of updates on it. Check back closer to release!
