### ISSUE TITLE
Critter Inventory pin to resource list ineffective

### ISSUE THREAD

**Issue by zivvel** [peterhaneve/ONIMods#263]
Playing with DLC enabled

## Expected Behavior
When I open "See All" and click the check-circle to toggle pinning of some critter categories, those categories should appear/track in the Resources list on the main UI.

## Current Behavior
No effect.  The circle checks, but the Resources list does not show any critters.

## Mod Versions
Whatever is current today, 2022-09-27.  In fact I tried un-subscribing and re-subscribing (restarting ONI in-between and after).

## Steps to Reproduce
as noted above

## Output Log
I don't think there's anything useful in it, but attached.
[Player-submit.log](https://github.com/peterhaneve/ONIMods/files/9658424/Player-submit.log)

**Comment by peterhaneve** [comment]
Due to a quirk of the Klei inventory screen, you may need to toggle pin on another, regular resource to get the list to update.

**Comment by zivvel** [comment]
Confirmed. Works after changing visibility of a non-critter.  Same goes for clicking the X in the displayed list.
