### ISSUE TITLE
Feature request: Debris heat transfer bug

### ISSUE THREAD

**Issue by Alex-1248** [peterhaneve/ONIMods#264]
When magma or molten metal falls into a cold liquid, solidifies and falls to the bottom of a container, it does not exchange heat with the liquid and the floor of the container.
More detailed information on klei's site:
https://forums.kleientertainment.com/klei-bug-tracker/oni/metal-from-metal-vulcano-does-not-transfer-heat-until-reloading-r33094
https://forums.kleientertainment.com/forums/topic/130534-another-debris-formation-bug
Can you fix this in Stock Bug Fix?
Thanks.

**Comment by peterhaneve** [comment]
This bug is likely to be related to the Sim, which is written in a different language and very difficult to mod. I would suggest upvoting the bug on the Klei website if you want a more prompt fix.
