### ISSUE TITLE
Rest for the Weary Error in Sweet Dreams Update

### ISSUE THREAD

**Issue by BlackBeltPanda** [peterhaneve/ONIMods#269]
## Current Behavior
Attempting to load the game results in an error with Rest for the Weary installed after the Sweet Dreams update. Uninstalling the mod also results in a crash as the new schedule block cannot be removed, rendering the save unplayable. Spaced Out! DLC is not installed.

## Mod Versions
Steam v2.3.0.0

## Steps to Reproduce
1. Install the mod
2. Launch the game
3. Load a save
4. Error

## Output Log
Installed error: [Player.log](https://github.com/peterhaneve/ONIMods/files/9711912/Player.log)
Uninstalled error: [Player.log](https://github.com/peterhaneve/ONIMods/files/9711915/Player.log)

**Comment by peterhaneve** [comment]
Almost all mods in this repository were broken by the recent patch, which was very disruptive to game internals. Most mods have been fixed as of this time.
