### ISSUE TITLE
Fast Track Startup Crash

### ISSUE THREAD

**Issue by Lbphero** [peterhaneve/ONIMods#271]
Upon Opening the game, it gives the black hole crash screen. Thought I would report this since I haven't seen anybody else do such.

## Current Behavior
The game crashes immediately upon opening, and does not allow me to continue. Not on any public testing branch.

## Mod Versions
Local 0.9.11

## Steps to Reproduce
1. Enable Fast Track
2. Restart
3. Witness Black hole screen

## Output Log
[output_log.txt](https://github.com/peterhaneve/ONIMods/files/9719715/output_log.txt)
[Player.log](https://github.com/peterhaneve/ONIMods/files/9719717/Player.log)

**Comment by anatoly-tapestry** [comment]
Same thing here, started happening after most recent update.

**Comment by peterhaneve** [comment]
After a huge rewrite in [929a66f](https://github.com/peterhaneve/ONIMods/commit/929a66fa029c5a48da550493365e34a6d16956b5), most issues with Sweet Dreams should be resolved.
