### ISSUE TITLE
NullReferenceException in AirlockDoor since U43-525812-S

### ISSUE THREAD

**Issue by blechema** [peterhaneve/ONIMods#272]
This happens randomly since the new ONI Version U43-525812-S

## Output Log

NullReferenceException: Object reference not set to an instance of an object

PeterHan.AirlockDoor.AirlockDoorTransitionLayer.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <c794748993af425fb6500c7c59881825>:0)
TransitionDriver.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
TransitionDriver.BeginTransition (Navigator navigator, NavGrid+Transition transition, System.Single defaultSpeed) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
Navigator.BeginTransition (NavGrid+Transition transition) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
Navigator.AdvancePath (System.Boolean trigger_advance) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
TransitionDriver.UpdateTransition (System.Single dt) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
Navigator.SimEveryTick (System.Single dt) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
Navigator+States+<>c.<InitializeStates>b__5_2 (Navigator+StatesInstance smi, System.Single dt) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
Game.SimEveryTick (System.Single dt) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
Game.Update () (at <6ab6b57553ed449280aa2485c86e9aab>:0)

Build: U43-525812-S

**Comment by peterhaneve** [comment]
Although you reported this change against U43-525812, it looks like today's hotfix U43-526233 also introduced breaking changes. See if you can reproduce them in the latest version (and please attach a full Player log file!)

**Comment by blechema** [comment]
I have reproduced the issue on U43-526233-S. Here is the Player-Log:
[Player.log](https://github.com/peterhaneve/ONIMods/files/9738605/Player.log)

**Comment by peterhaneve** [comment]
The version of Airlock Door installed is over eight months old. The Steam Workshop does not auto-update mods; make sure to install [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to download the latest version.
