### ISSUE TITLE
FastTrack 0.9.12 (SpacedOut Map): Background Inventory enabled removes all my inventory (everything is zero) in the Inventory-Tracker (TopRight)

### ISSUE THREAD

**Issue by michaelvolz** [peterhaneve/ONIMods#274]
## Expected Behavior

The Inventory-Tracker should display the correct values for the selected materials

SpacedOUT DLC, standard branch
## Current Behavior

The Inventory-Tracker displays all zeroes
## Mod Versions

Standard Steam, installed FastTrack as local copy
## Steps to Reproduce

1. Install FastTrack
2. Enable "Background Inventory"
3. Load SpacedOUT DLC Map/Resume Game
4.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/9741273/Player.log)

fyi: I am a big fan of your work. FastTrack is just amazing.

**Comment by michaelvolz** [comment]
fyi: "Resources" = Inventory-Tracker

**Comment by peterhaneve** [comment]
This issue, along with three other critical bugs, has been fixed in Fast Track 0.9.13.
