### ISSUE TITLE
[ISSUE] Game crashes when Dupes must gather and supply resources.

### ISSUE THREAD

**Issue by ArashiOdayakana** [peterhaneve/ONIMods#275]
https://pastebin.com/r0C3sFUa
https://imgur.com/a/eNaVLfS
All of the details are above.

Steps to Reproduce:
1. Launch game
2. Load/Create new world
    2a. Spawn into world
3. Task a Dupe with a build, storage, or repair order.
4. Game crashes with Efficient Supply in red text.
5. Refer to Pastebin URL above, an Imgur link shows what is on-screen.

**Comment by peterhaneve** [comment]
You have an outdated version of Efficient Supply, as Klei broke most mods with the recent Sweet Dreams update. As Steam does not auto-update mods, force an update through a mod like [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
