### ISSUE TITLE
Game crash when roller snake hatches from egg

### ISSUE THREAD

**Issue by UnderwearApp** [peterhaneve/ONIMods#276]
## Expected Behavior
Game should not crash
Spaced Out DLC

## Current Behavior
Game crashes

## Mod Versions
Steam subscription - Up to date
Have used Mod Updater

## Steps to Reproduce
1. Have roller snake egg
2. Let egg hatch
3. Crash
4. Profit

## Output Log
Player log attached
[Player.log](https://github.com/peterhaneve/ONIMods/files/9750064/Player.log)

**Comment by peterhaneve** [comment]
This crash was introduced by the hotfix U43-526233. Roller Snakes has been updated to version 3.2 which should fix it.
