### ISSUE TITLE
Mod Updater Crash after subscribing to new mod

### ISSUE THREAD

**Issue by Zaphodjoe** [peterhaneve/ONIMods#278]
## Expected Behavior
When I install a Mod the game should start without crashing

## Current Behavior
For months now whenever I subscribe to a new mod my game will crash and the cause given to Mod Updater. The log shows an issue with mod updater and steam update. It looks like maybe mod updater is trying to check the mod before steam even downloads it but I'm not 100% certain.

## Mod Versions
2.10.0.0 Steam Subscription

## Steps to Reproduce
Subscript to any new mod, start ONI, Game goes to main menu for a second then crashes and Mod Updater is RED in the list

1.
2.
3.
4.

## Output Log
I lost the log because I restarted a few times and now can't reproduce it but when I checked on the Steam Website for this mod other people had the same issue and said to use the one by ONY but I tried and that one got stuck downloading a file and caused a crash. People on discord said no one uses that one because it is broken they all use yours. Now I can't reproduce it but it has happened almost every time I add a new plugin the last few months. From looking at the log I saw an issue with Mod Updater then Steam Updater at the end so it lead me to believe mod updater was trying to update a mod that hadn't been installed yet. I moved mod updater to the end of my mod list and now its loading without a crash after installing 3 new mods but not sure how long that will last.

**Comment by peterhaneve** [comment]
Without a full log debugging the issue will be impossible, as it is probably a race condition specific to your device. Steam can especially pose a hazard for race conditions (even with the base game) as network conditions vary in different locations.

Mod Updater was unaffected by the Sweet Dreams update. Consider resetting its configuration to default in the settings menu if issues still occur.
