### ISSUE TITLE
Fast track breaks rocket renaming/rocket side screen string

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#279]
When Fast Track is installed (v0.9.14), rocket modules can't be re-named (the icon to rename it is missing) and the title label text for the rocket module side-screen is "MISSING." when a passenger module is selected. (see screenshot)
<img width="602" alt="Screenshot 2022-10-16 184042" src="https://user-images.githubusercontent.com/12467241/196071763-5d105fac-100e-4839-85bb-7f54c044290b.png">

## Expected Behavior

The Rocket Module side screen should say "Rocket Module" and there should be a 'rename' button on the capsule's Properties panel to the right.
<img width="932" alt="Screenshot 2022-10-16 185048" src="https://user-images.githubusercontent.com/12467241/196072527-90b8f845-5511-43a1-ab10-81fb8da492b2.png">

This is in spaced out, public release version.

## Current Behavior

When selecting any rocket capsule, the rocket module side screen lists "MISSING." as the title, and the "rename" icon is missing.

## Mod Versions

Local, v0.9.14

## Steps to Reproduce

1. Make a rocket platform
2. Add a passenger capsule.
3. Select the passenger capsule
4. Observe the rocket module side screen title and passenger module properties panel

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/9796267/Player.log)

Fast Track seems to be breaking Rocket renaming. I ran it with all mods disabled, and it works fine. I enable only Fast Track, and the ability to rename rockets breaks.

**Comment by peterhaneve** [comment]
While this is a real issue that has been fixed in 0.9.15 introduced by the recent hotfix, it does not meet the bar for an immediate release.
