### ISSUE TITLE
Wrangle by type

### ISSUE THREAD

**Issue by jmucchiello** [peterhaneve/ONIMods#28]
How hard would it be to do for wrangling what you did for sweeping? Sometimes you have a variety of hatches all jumbled together and while you can pause and hand select the specific hatches you are looking for. It would be easier, with such a mod, to just set "smooth hatchling", "stone hatchling", " hatchling" and "sand hatchling" and pull out all the babies, for example.

Thanks for all the cool mods.

**Comment by peterhaneve** [comment]
This would be out of scope for sweep by type, but wrangle by type would certainly be a feasible separate mod.

**Comment by jmucchiello** [comment]
That was the point. A separate mod.
