### ISSUE TITLE
Fast Track v0.9.16.0 Crash

### ISSUE THREAD

**Issue by medkg15** [peterhaneve/ONIMods#282]
Crash w/ Fast Track mod

## Mod Versions
v0.9.16.0

## Steps to Reproduce
Did not reoccur on the same save - unknown.

## Output Log

[Player-prev.zip](https://github.com/peterhaneve/ONIMods/files/9848079/Player-prev.zip)

**Comment by peterhaneve** [comment]
It looks like a Duplicant tried to drop off a suit at a full atmo suit checkpoint within 0.2 seconds of the last open suit locker being deconstructed. A fix has been added to main, but no new version will be pushed at this time.
