### ISSUE TITLE
Thermal Interface plate transfers very badly with cooling

### ISSUE THREAD

**Issue by survaaki** [peterhaneve/ONIMods#284]
## Expected Behaviour
Using Spaced Out DLC, default public build - not on any beta

Expected Behaviour
Heat or cool a coal generator via a thermal interface plate in a vacuum.

## Current Behavior
The coal generator will only heat up not cool down.

Examining the cold super coolant flowing in, the thermal interface plate transfers heat to the liquid in the radiant pipe but does not transfer it to the TI plate.

## Mod Versions
Steam subscription, mod updater confirms mod up to date.
Only Thermal Tooltips and Thermal Interface Plate active mods

## Steps to Reproduce
In a vacuum place an aluminium coal generator with an aluminium thermal interface plate on each lower corner and an aluminium radiant liquid pipe above each plate. Feed cold super coolant (-272 degrees C) to the left side, hot super coolant (400 degrees C) to the right hand side. Control the super coolant flow with two signal switches.

The coal generator will never cool down, it will only ever heat up.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/9997101/Player.log)

attached

**Comment by survaaki** [comment]
For reference I built in "space exposure" area and used graphite drywall.

Removing the thermal interface plates and replacing it with 200kg super coolant over the 3 wide tiles produced expected heating and cooling.

**Comment by survaaki** [comment]
Thermal Interface Plate v3.7.0.0 Monday, April 11, 2022 7:05 AM

**Comment by peterhaneve** [comment]
It appears that the base game does not support setting the temperature of the same building more than once per sim update. Therefore, it is currently impossible to have two thermal interface plates affecting the same target building - the base game simply picks one and ignores all the others. The building it chooses appears to remain consistent from frame to frame but is arbitrarily chosen on reload.

Batching building temperature updates across all thermal interface plates is the only real "solution" but introduces potentially worse issues with building deconstruction and race conditions from the game to the Sim. In addition, it would break compatibility with any other mod (and some entities from the base game like the Hot Tub) that also sets the building's temperature directly as those changes would be thrown out when the batch update occurs.

Given these limitations, it is likely best to avoid using multiple Thermal Interface Plates on the same target building.

**Comment by peterhaneve** [comment]
It looks like the new vanilla Conduction Plate suffers from the exact same bug. Without an update to the engine, this bug will not be fixable.
