### ISSUE TITLE
Weight plates appear to be rarely jamming in Fast Track

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#285]
It's really difficult to track this down, but I highly suspect it's due to Fast Track. 

I've been running my current colony for almost 900 cycles without fast track enabled. In it, I was using two pacu boxes (basically, the automated version from the mod development discord's tags.). For 900 cycles, they were functioning perfectly, despite me having a bunch of other mods installed. 

As the performance started to dip, I enabled Fast Track, and after a short period of time, a weight plate got stuck sending a red signal, despite it being set to "Below 4kg" as before, without changes. The end result is that the pacubox kill off the entire population in a generation, as it trapped all of the pacu in flopping animation, without replenishing the breeding pool as expected.

Unfortunately, it's not clear what's triggering this, whether it's getting stuck on load, or it's getting stuck during normal operation, but it only resets once something heavy has been dropped onto the weight plate again then removed. The broken state *does appear to persist across save/reload*.

## Expected Behavior

Weight plates don't get stuck in a Red state when nothing is on them, while set to "below 4kg"

This is in spaced out, public release branch.

## Current Behavior

Weight plate gets stuck at some point (unclear if across save/load or during gameplay at this time). A save stuck in that current state is attached. 

## Mod Versions

Local copy. Fast Track version 0.9.16

## Steps to Reproduce

1. Make a pacu box. 
2. Use the pacu box with fast track
3. Eventually it'll get stuck red, even with nothing on the weight plate (see attached save for an example)

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/10106492/Player.log)

[Delicate Beyond Cycle 1024.zip](https://github.com/peterhaneve/ONIMods/files/10106498/Delicate.Beyond.Cycle.1024.zip)

**Comment by peterhaneve** [comment]
I think that I have fixed all the remaining wrong-item location issues in 0.9.17. As this issue is nearly impossible to reproduce (I could not even reproduce it on your save with 0.9.16, pointing to a machine specific race) I have no way of verifying.
