### ISSUE TITLE
Workshop Profiles Request - (optional) append to the left of the Recipe / Work window. OR collapse Workshop Profile list

### ISSUE THREAD

**Issue by Lopeh** [peterhaneve/ONIMods#288]
## Current Behavior
Workshop Profiles append to the top of an operating building's recipes. With one or two other mods (eg: attribute-based workshop & daily routine), the list gets very tall/obstructive.

## Desired Behavior
If possible, to allow the Workshop Profiles UI to be collapsible or moved to the left.

## Mod Versions
2.3.0.0 (Steam subscription w/ mod updater)

## Output 
![image](https://user-images.githubusercontent.com/13429544/206265452-02ce8ee6-7554-4cee-9038-3de26281bd71.png)

**Comment by peterhaneve** [comment]
Moving the list to the left is not possible due to limitations in Klei's UI layout. Making sections collapsible is a bigger problem that is probably best solved with a separate mod as it is a problem not unique to Workshop Profiles.

**Comment by wilki24** [comment]
I play with the UI scale pretty high, and I end up with an unusable dialog.
![Like this.](https://github.com/peterhaneve/ONIMods/assets/8873894/322727e9-b58a-4390-be38-cce8abf07c39)

Is there any way to solve this other than adjusting the UI scale every time?
