### ISSUE TITLE
ONI mod Waste Not, Want Not - Dupes and sweepers putting food below freshness rating in food containers

### ISSUE THREAD

**Issue by Dormas01** [peterhaneve/ONIMods#289]
The Oxygen Not Included (ONI) mod "Waste Not, Want Not" (also known as NoWasteWant) is having food containers repeatedly accept food items below the freshness threshold of the container and then quickly drops them, causing the dup/sweeper to pick up the food item again and store it in the same container again, causing a repeated cycling.

## Expected Behavior

Food items below freshness setting should not see the container as a valid container for food items.

Using Spaced Out! DLC.
Not using any public preview branches.

## Current Behavior

Rapid cycling of container dropping food items and the food items being placed back inside.

## Mod Versions

Tested with Steam subscription (fully removed and re-added) and local copy

Installed Mod updater and forced update - no effect

## Steps to Reproduce

1. Food items below threshold, works best with multiple different foods as the container can take a second or two to drop the food
2. Two refrigerators next to each other
   a. Left refrigerator to store any food, set to priority 5, and set minimum freshness to 0%
   b. Right refrigerator to store any food, set to priority 6 and set minimum freshness to 50%
3. Allow duplicants or sweepers to store food.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/10199106/Player.log)

Saved game files available upon request.

**Comment by peterhaneve** [comment]
Some cases of this bug have been fixed in version 1.4, but not all cases are fixable due to how Oxygen Not Included batches fetch chores of nearby items. It is likely that you will need to use Mod Updater to receive the updated version.
