### ISSUE TITLE
[PLib] Game fails to load with latest update (Hot Shots Update)

### ISSUE THREAD

**Issue by glektarssza** [peterhaneve/ONIMods#291]
The game does not load when any mod using PLib is enabled.

## Expected Behavior

* Game loads to the main menu normally.

## Current Behavior

* Game stops at the "Oops-a-daisy" screen due to a fatal error during mod loading.

## Mod Versions

* Steam version of all mods.
* All mods update to date (at time of writing).
* Mod list: https://gist.github.com/glektarssza/931fd1fcb29936850b09bc67472469bf

## Steps to Reproduce

1. Launch the game with any mod that depends on PLib enabled.
2. Observe game does not make it to the main menu.

## Output Log

Log file: https://gist.github.com/glektarssza/ca2243ad4e21981c2e3fc6a536f846e0

Relevant outputs are at timestamp `20:39:53.991` or line `1026`

**Comment by The-Toblin** [comment]
Can confirm. I don't have any useful data to add to this, other than to confirm it does indeed happen to me as well.

**Comment by peterhaneve** [comment]
The failing mod here is No Manual Delivery, which is not maintained in this repository. Likewise, it looks like you have an outdated version of Rooms Expanded. Please take these issues up with the respective mod authors.
