### ISSUE TITLE
Null ref in RocketRestrictionSideScreen.UpdateButtonStates

### ISSUE THREAD

**Issue by anpilley** [peterhaneve/ONIMods#293]
Not sure if this is Fast Track or if it's a base game bug. Was launching a rocket, and hit this crash. I was viewing the rocket from the outside, but I'd recently selected the RCS on the inside, so it's possible there's some bad state between the two views.

## Expected Behavior
Rocket should launch without crashing. (Spaced out DLC)

## Current Behavior
See Player.log for crash

## Mod Versions
Locale Fast Track 0.10.0

## Steps to Reproduce
Not 100% sure the exact order.:
1. Hit launch on a rocket that can't launch yet (crew member off-world/inaccessible)
2. Select RCS inside rocket.
3. Switch to external view. 
4. Possibly remove a crew member from the rocket crew list (who was unable to get into the rocket due to being off world) 
5. 
6.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/10250898/Player.log)

**Comment by peterhaneve** [comment]
I am unable to reproduce the issue, and there is no Fast Track code in the crash. If I had to guess, it is probably a bug or compatibility issue in "Improved Rocket Controls".

**Comment by anpilley** [comment]
Hm. I haven't been able to repro it again either so far, either. But Improved Rocket Controls (my mod) doesn't touch that component of the RCS screen, the code that crashed is modifying the None/Ungrounded button states, which I didn't change. I suspect there's a race between switching from the interior RCS display and the exterior rocket controls when a rocket takes off.

I'll have to see if i can catch it again.
