### ISSUE TITLE
Queue for Sinks doesn't work anymore with Hot Shots update.

### ISSUE THREAD

**Issue by eponge240** [peterhaneve/ONIMods#295]
## Expected Behavior
Since the Hot Shots update, "Queue for Sinks" is no longer working.
Dupes that need to wash their hands should line up if the sink is already being used by another dupe.
No idea if this is also happening in Spaced Out! too, for me it's happening in Base Game.

## Current Behavior
If the sink is already in use, dupes are not stopping and are just passing by, like if the mod was not installed (back to default behavior)

## Mod Versions
3.8.0.0

**Comment by peterhaneve** [comment]
As this mod required a complete rewrite for U44-534889, the update has taken much longer than most other mods. Version 3.9 has now been tested and posted, but as usual Mod Updater will be required to receive the update as Steam does not auto-update mods.

**Comment by eponge240** [comment]
It is now working again with version 3.9, good job.
