### ISSUE TITLE
Fast Track 0.10.0 wont load

### ISSUE THREAD

**Issue by Avtera** [peterhaneve/ONIMods#296]
## Expected Behavior
Fast Track mod loaded and the game main menu loads up
I have Spaced Out! DLC installed

## Current Behavior
Cant load the mod and crash screen appear 

## Mod Versions
0.10.0

## Steps to Reproduce
1. Install the mod as the forum post told me to, installed at Klei/mods/local/
2. Open the game and move the Fast Track mod order to the top
3. Enable the mod and close the game
4. Open the game and the error shows up

## Output Log
[Fast Track 0.10.0 error.txt](https://github.com/peterhaneve/ONIMods/files/10267925/Fast.Track.0.10.0.error.txt)

**Comment by peterhaneve** [comment]
You are using the public previous version `U43-531669-S`. Fast Track 0.10.0 is only compatible with Hot Shots, build U44 and up. Due to the size of the mod, it is not feasible to support both builds with one mod.
