### ISSUE TITLE
Mod Updater - Crash when clicking "force update" button

### ISSUE THREAD

**Issue by UnderwearApp** [peterhaneve/ONIMods#297]
## Expected Behavior
Force update button checks for update, retrieves it or not, prompts restart if necessary
Spaced Out stable branch

## Current Behavior
Clicking on force update button either for individual mods or the red one at the bottom causes crash

## Mod Versions
Steam subscription. Same issue persists when trying to update Mod Updater

## Steps to Reproduce

1. Enter Mods menu in game
2. Click force update on any mod or at bottom if MU detects outdated mods
3. Crash/Black hole
4.

## Output Log
Log attached

[Player.log](https://github.com/peterhaneve/ONIMods/files/10289332/Player.log)

**Comment by peterhaneve** [comment]
You have an old version of Mod Updater. If verifying game files in the Steam client does not solve the problem, you will need a local install.
