### ISSUE TITLE
Game crashes when trying to repaint painting

### ISSUE THREAD

**Issue by kyradeters** [peterhaneve/ONIMods#298]
## Expected Behavior

Painting is cleared, duplicant repaints with selected painting.
(Using Spaced Out! DLC)

## Current Behavior

Painting is cleared, game crashes when duplicant tries to repaint.

## Mod Versions

Local copy of Fast Track (0.10.0)

## Steps to Reproduce

1. Place painting and let duplicant paint.
2. Select different style and clear painting.
3. Wait for duplicant to start task.
4. Instead of starting to paint, the game crashes.

## Crash Log
NullReferenceException

UnityEngine.Component.GetComponent[T] () (at <704cac2d02a9488e8e7e54f3a503296d>:0)
ArtableSelectionSideScreen.GenerateStateButtons () (at <d5307867edd5445aaf5c8b27a82cce98>:0)
ArtableSelectionSideScreen.OnRefreshTarget (System.Object data) (at <d5307867edd5445aaf5c8b27a82cce98>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <7273b301087c4ae79b7148cae73dd755>:0)
EventExtensions.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <7273b301087c4ae79b7148cae73dd755>:0)
Workable.CompleteWork (Worker worker) (at <d5307867edd5445aaf5c8b27a82cce98>:0)
Worker.CompleteWork () (at <d5307867edd5445aaf5c8b27a82cce98>:0)
(wrapper dynamic-method) Worker.Worker.Work_Patch0(Worker,single)
GameStateMachine`4+State+<>c__DisplayClass84_0[StateMachineType,StateMachineInstanceType,MasterType,DefType].<ToggleWork>b__1 (StateMachineInstanceType smi, System.Single dt) (at <d5307867edd5445aaf5c8b27a82cce98>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <7273b301087c4ae79b7148cae73dd755>:0)
Game.SimEveryTick (System.Single dt) (at <d5307867edd5445aaf5c8b27a82cce98>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U44-535842-S

**Comment by peterhaneve** [comment]
This is a base game bug: https://forums.kleientertainment.com/klei-bug-tracker/oni/artable-crashes-on-repaint-completion-r38062/
