### ISSUE TITLE
Large stuttering issues with Efficient Supply

### ISSUE THREAD

**Issue by Danice123** [peterhaneve/ONIMods#30]
Looks like since patch 393231 (Feb 5 2020) or 393722 (Feb 7 2020) Efficient Supply is causing stuttering issues. I have had consistent stuttering every couple seconds while playing a ~500 cycle base. Removing the mod fixes this issue.

**Comment by peterhaneve** [comment]
This issue was fixed in Efficient Supply 2.0.0.0. If Steam is still giving you an old version, try a local copy as described in the repository README.
