### ISSUE TITLE
Random crashes while using Waste Not Want Not

### ISSUE THREAD

**Issue by Captain-Seasick** [peterhaneve/ONIMods#300]
## Expected Behavior

There simply shouldn't be any crashes.

## Current Behavior

The game crashes seemingly at random (I've yet to detect a pattern in the crashes).

## Mod Versions

I'm using the latest version of both the game and the mod (U44-535842-V for the game, the unmarked 10th of december version of the mod).

## Steps to Reproduce

1. I start the game.
2. I load my existing save and play the game.
3. Something unknown (to me at least) happens and triggers a game crash.
4. Rinse and repeat, I guess?

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/10317409/Player.log)

**Comment by Captain-Seasick** [comment]
It's worth noting that Waste Not Want Not is the _only_ mod that I currently use for the game, and without it being loaded I don't get any crashed (as far as I've noticed).

**Comment by Carbohydron** [comment]
These crashes also started for me ever since the Hot Shots update.

**Comment by peterhaneve** [comment]
This is a base game bug: https://forums.kleientertainment.com/klei-bug-tracker/oni/artable-crashes-on-repaint-completion-r38062/

**Comment by Captain-Seasick** [comment]
That's both disappointing and relieving. Sorry for the (inadvertently) false report and have a happy New Year.
