### ISSUE TITLE
Unexpected crash when scrolling the view

### ISSUE THREAD

**Issue by The-Toblin** [peterhaneve/ONIMods#301]
## Expected Behavior
Non-reproducible crash when "just playing the game". Can't really give you an answer aside from "not crash" being expected behaviour.

Right when it crashed, I was attempting to build transport tubes and was dragging the view.

NO DLC installed.
Official release, no preview.

## Current Behavior

Sudden hard crash of the game, claiming "FastTrack" was the culprit.

## Mod Versions

Local install of FastTrack. All other mods are via Steam.

## Steps to Reproduce

Can unfortunately not do this. I was hoping the log would be helpful for your development. I've played for ~60 hours with your mod (and my other mods) and while it's "hitching" occasionally, it's been remarkably stable.

## Output Log

[Uploading k…]()
[Player.log](https://github.com/peterhaneve/ONIMods/files/10333428/Player.log)

**Comment by peterhaneve** [comment]
This is a base game bug: https://forums.kleientertainment.com/klei-bug-tracker/oni/artable-crashes-on-repaint-completion-r38062/
