### ISSUE TITLE
[Fast Track] Radiation disease

### ISSUE THREAD

**Issue by MegaJani** [peterhaneve/ONIMods#305]
## Current Behavior
With the "Disable disease" setting enabled, dupes can still be irradiated, but the Apothecary building is deprecated, so one can't make radpills.

## Mod Versions
Newest, local

## Steps to Reproduce
1. Disable disease -> check
2. Send dupe to high-rad zone
3. Gets radiation sickness

##
I checked the "Radiation rebalanced" mod for a possible conflict, but it does not change radiation sickness.

A possible solution would be to leave the Apothecary building enabled to manufacture radpills, or adding the radpill recipe to another building.

**Comment by peterhaneve** [comment]
Disabling disease is not supposed to disable radiation, or radiation sickness, but the missing rad pills is indeed an issue. The Apothecary will be re-enabled in future builds and limited to just rad pills on the DLC.

**Comment by MegaJani** [comment]
Much appreciated.

**Comment by peterhaneve** [comment]
Apothecary can be built again in Fast Track 0.10.3.
