### ISSUE TITLE
Additional details panel crash

### ISSUE THREAD

**Issue by Gertjanvandijk** [peterhaneve/ONIMods#309]
## Expected Behavior
Live branche with DLC active
When clicking on the additional details panel (properties) of an element it should open it.

## Current Behavior
It crashes the game instead.

## Mod Versions
Local copy, 0.10.5

## Steps to Reproduce
Start new colony, click oxygen tile, go to properties (additional details).

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/10535738/Player.log)

**Comment by peterhaneve** [comment]
This issue should be fixed in 0.10.6.

**Comment by Gertjanvandijk** [comment]
Thank you for the fix, love the mod!
