### ISSUE TITLE
UnityExceptions caused by FastSave mod

### ISSUE THREAD

**Issue by Marcoevich** [peterhaneve/ONIMods#31]
Hello,

I had reported some Exceptions in the logfile to Klei but they say it's from your mod. See the topic here: https://forums.kleientertainment.com/klei-bug-tracker/oni/several-unity-exceptions-in-logfile-r23930/

**Comment by peterhaneve** [comment]
This issue has been fixed in Fast Save 2.1. Looks like another casualty of the latest updates, as Unity is more strict about the fact that it is almost exclusively single threaded.

**Comment by Marcoevich** [comment]
Thank you!
