### ISSUE TITLE
Crash during normal gameplay, no clear cause

### ISSUE THREAD

**Issue by realcharletron** [peterhaneve/ONIMods#312]
Crash during normal gameplay, game blames Fast Track. I wasn't doing anything particularly unusual, just issuing deconstruct and build commands. I needed to move a ranch over a few tiles so was deconstructing and rebuilding the relevant buildings, tiles, etc. I have the DLC installed, and am on the main steam branch. Using Fast Track version 0.10.5

## Expected Behavior
Normal gameplay

DLC installed, on main steam branch

## Current Behavior
Crash

## Mod Versions
Local

## Steps to Reproduce
Unclear, crash seemed random, first ever with this mod. Apologies I can't be more specific, hopefully the output log will help
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/10541917/Player-prev.log)

**Comment by peterhaneve** [comment]
This is a base game bug that will be fixed in the next ONI release, whenever that might be: https://forums.kleientertainment.com/klei-bug-tracker/oni/validatetargetranchables-argumentoutofrangeexception-index-r38019/
