### ISSUE TITLE
Random crashes every few hours during normal (but heavily modded) gameplay.

### ISSUE THREAD

**Issue by The-Toblin** [peterhaneve/ONIMods#314]
"Random" crashes during normal gameplay. I have been unable to connect a particular behavior or event to these crashes, but the logs persistently report the same stack.

## Mod Versions
Local mod installed from here on Git.

Additional mods installed (From workshop) IDs:
1703611962
1717463209
1717499632
1722760223
1732534140
1822071175
1822160024
1835394161
1843965353
1844888487
1854895085
1855163252
1863275516
1872105871
1881925531
1897096779
1909037839
1959130035
1960947963
2053191586
2094698134
2169776807
2271373459
2435244304
2479475997
2549295369
2693850829
2815406414
2839508628
2841963310
2863383492
2880433226
2921809973

## Steps to Reproduce
This is where I run into problems. I have this crash maybe 3-4 times a session, always the same last line in the stacktrace. "Session" being anywhere from 3-8 hours of playtime.

## Output Log
```
mmap(PROT_NONE) failed
Caught fatal signal - signo:6 code:-6 errno:0 addr:0x3e8000de4f1
Obtained 17 stack frames.
#0  0x007ff28d3699e0 in (Unknown)
#1  0x007ff28d3b964c in (Unknown)
#2  0x007ff28d369938 in (Unknown)
#3  0x007ff28d35353d in (Unknown)
#4  0x007ff287a3e6c5 in (Unknown)
#5  0x007ff287a3e732 in (Unknown)
#6  0x007ff287a41898 in (Unknown)
#7  0x007ff287a41c65 in (Unknown)
#8  0x007ff287a41d84 in (Unknown)
#9  0x007ff287a42c30 in (Unknown)
#10 0x007ff287a45a83 in (Unknown)
#11 0x007ff287a45c5d in (Unknown)
#12 0x007ff287a18b56 in (Unknown)
#13 0x007ff2879cd8f7 in (Unknown)
#14 0x007ff2879cd95e in (Unknown)
#15 0x000000407a2d6f in (wrapper managed-to-native) object:__icall_wrapper_ves_icall_array_new_specific (intptr,int)
#16 0x0000004259e200 in PeterHan.FastTrack.UIPatches.LocTextAllocPatches/FilterInput_Patch:Prefix (LocText,string,string&)
```
That last line is always present. I have not been able to identify if it's because it clashes with another mod, if it's a function I can turn off to test or anything. I am, unfortunately, not very good at C# or the ONI logs.

If there's anything you want me to test, I will gladly oblige.

Log attached.
[Player.log](https://github.com/peterhaneve/ONIMods/files/10571091/Player.log)

**Comment by The-Toblin** [comment]
Addition: 
I am making a bug report here, largely out of ignorance. I am unable to pinpoint the cause of the crash, but since that last stack line is always present, something is causing your mod to crash. If it's a bug in your mod, or something else, I can't tell.

**Comment by peterhaneve** [comment]
It looks like your system is out of memory with a native code crash in allocation. Even if the OS reports that some memory is available, Unity (which is notorious for heap fragmentation) will fail if no more virtual address space is available.

Even if another mod or the base game actually leaks memory, the crash will only occur when new memory is allocated. As that patch runs on literally every text string displayed in the game, it is a very likely candidate to be blamed when memory is critically low.

Unfortunately, with so many mods installed, it will be impossible to find the leak (which may be a 2 or 3 way incompatibility too) without memory profiling tools that are unavailable to anyone but Klei themselves. As a workaround, you could try disabling nonessential mods, or increasing your swap file size/overcommit ratio.

**Comment by The-Toblin** [comment]
Brilliant answer, thank you. Gives me something to start digging for. Thank you!
