### ISSUE TITLE
Game Crashes after Loading

### ISSUE THREAD

**Issue by submatrix7** [peterhaneve/ONIMods#315]
MissingFieldException: Field 'FetchChore.tagBits' not found.

PeterHan.EfficientFetch.EfficientFetchManager.FindFetchTarget (FetchChore chore, ChoreConsumerState state, Pickupable& result) (at <3009486fd7ac4f2480013a0956d6188e>:0)
PeterHan.EfficientFetch.EfficientFetchPatches+FetchChore_FindFetchTarget_Patch.Prefix (FetchChore __instance, ChoreConsumerState consumer_state, Pickupable& __result) (at <3009486fd7ac4f2480013a0956d6188e>:0)
(wrapper dynamic-method) FetchChore.FetchChore.FindFetchTarget_Patch1(FetchChore,ChoreConsumerState)
FetchChore+<>c.<.cctor>b__44_0 (Chore+Precondition+Context& context, System.Object data) (at <1726ad14e928409087f7fe566b21e0ff>:0)
Chore+Precondition+Context.RunPreconditions () (at <1726ad14e928409087f7fe566b21e0ff>:0)
Chore.CollectChores (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded_contexts, System.Collections.Generic.List`1[T] failed_contexts, System.Boolean is_attempting_override) (at <1726ad14e928409087f7fe566b21e0ff>:0)
FetchChore.CollectChoresFromGlobalChoreProvider (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded_contexts, System.Collections.Generic.List`1[T] failed_contexts, System.Boolean is_attempting_override) (at <1726ad14e928409087f7fe566b21e0ff>:0)
GlobalChoreProvider.CollectChores (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded, System.Collections.Generic.List`1[T] failed_contexts) (at <1726ad14e928409087f7fe566b21e0ff>:0)
ChoreConsumer.FindNextChore (Chore+Precondition+Context& out_context) (at <1726ad14e928409087f7fe566b21e0ff>:0)
Brain.FindBetterChore (Chore+Precondition+Context& context) (at <1726ad14e928409087f7fe566b21e0ff>:0)
Brain.UpdateChores () (at <1726ad14e928409087f7fe566b21e0ff>:0)
Brain.UpdateBrain () (at <1726ad14e928409087f7fe566b21e0ff>:0)
MinionBrain.UpdateBrain () (at <1726ad14e928409087f7fe566b21e0ff>:0)
BrainScheduler+BrainGroup.RenderEveryTick (System.Single dt, System.Boolean isAsyncPathProbeEnabled) (at <1726ad14e928409087f7fe566b21e0ff>:0)
BrainScheduler.RenderEveryTick (System.Single dt) (at <1726ad14e928409087f7fe566b21e0ff>:0)
SimAndRenderScheduler+RenderEveryTickUpdater.Update (IRenderEveryTick updater, System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater.RenderEveryTick (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
Game.LateUpdate () (at <1726ad14e928409087f7fe566b21e0ff>:0)

Build: U44-537329-S

## Expected Behavior
Game should load
Using Spaced Out! DLC

## Current Behavior
Game crashes after loading

## Mod Versions
Using Steam subscription and have force updated the mod using Mod Updater

## Steps to Reproduce
1. Activate mod
2. Reload game
3. Load into game
4. Game crashes after load

**Comment by peterhaneve** [comment]
The version of Efficient Supply in this log is over five months out of date. If you have already tried Mod Updater (and manually clicked the force update button even if it is green! There is a bug where ONI lies about the installed version) you will need to install a local copy and manually update it after each game update.
