### ISSUE TITLE
Airlock door causes game to crash after load

### ISSUE THREAD

**Issue by AKYeti** [peterhaneve/ONIMods#316]
## Expected Behavior

Game shouldn't crash

None of the above

## Mod Versions

Steam subscription, have updated with mod updater

## Steps to Reproduce

1. Load ONI with Airlock door enabled and unpause
2.
3.
4.

## Output Log

NullReferenceException: Object reference not set to an instance of an object

PeterHan.AirlockDoor.AirlockDoorTransitionLayer.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <c794748993af425fb6500c7c59881825>:0)
TransitionDriver.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
TransitionDriver.BeginTransition (Navigator navigator, NavGrid+Transition transition, System.Single defaultSpeed) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
Navigator.BeginTransition (NavGrid+Transition transition) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
Navigator.AdvancePath (System.Boolean trigger_advance) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
TransitionDriver.UpdateTransition (System.Single dt) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
Navigator.SimEveryTick (System.Single dt) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
Navigator+States+<>c.<InitializeStates>b__5_2 (Navigator+StatesInstance smi, System.Single dt) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <7273b301087c4ae79b7148cae73dd755>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <7273b301087c4ae79b7148cae73dd755>:0)
Game.SimEveryTick (System.Single dt) (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)
Game.Update () (at <8de6cd11d86441fcb8d144b8d4b27c43>:0)

Build: U44-537329-V

**Comment by peterhaneve** [comment]
This version of Airlock Door still seems to be out of date, as Klei introduced this crash with the hotfix U43-526233 and the corresponding mod fix was in version 3.8. Without a full output log there is no way to know for sure, but it is likely that ONI is lying about the installed mod version due to another bug in the mod loader. You will need to force update both Mod Updater and the target mod again.
