### ISSUE TITLE
[FastTrack] Side panel crash

### ISSUE THREAD

**Issue by MegaJani** [peterhaneve/ONIMods#319]
## Current Behavior
Crashes when clicking on any building.

## Mod Versions
Local, newest

## Steps to Reproduce

1. Enter game
2. Click on building

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/10829831/Player.log)

**Comment by peterhaneve** [comment]
I realized that you closed the issue, but I believe that this crash is actually in "Hold Construction".
