### ISSUE TITLE
Fast Track: Critter sensor not working in a big room

### ISSUE THREAD

**Issue by TheRealestMVP** [peterhaneve/ONIMods#322]
I have a big Pacu breeding room of 410 tiles. Population and egg sweeping is controlled via critter sensor.

It worked fine before installing Fast Track. But now the critter sensor says "Outside of room", always sending red, and the room overlay says "Size: 410 Tiles, Maximum room size: 128 Tiles".

My guess is that Fast Track optimizes room calculations and limits room sizes to 128 tiles. That's useful for named/specialized rooms, but there's legit uses of a critter sensor outside of this limit, inside bigger rooms that are not a stable.

The only room related option i could find in the mod settings is "Background Room Rebuild", but disabling that doesn't fix the issue.

Current Live Version U45-546664, Spaced Out activated.

**Comment by peterhaneve** [comment]
This bug can be reproduced even with Fast Track disabled. If it is important to you, file a report on the [Klei Bug Tracker](https://forums.kleientertainment.com/klei-bug-tracker/oni/).
![image](https://user-images.githubusercontent.com/29011570/224892903-cf323bce-c5c5-4c6a-acc4-c3c8d9bbf43c.png)
![image](https://user-images.githubusercontent.com/29011570/224892936-525bba3c-9c90-4573-a3c0-9808428fa94d.png)

**Comment by TheRealestMVP** [comment]
Thanks for testing and your reply. I also did more testing and found some weird results.

### First, here is where I came from:

Actual colony, without Fast Track:
![sensor-1](https://user-images.githubusercontent.com/29225123/224989431-6b886189-3d5b-4b0f-be09-ffc31fe3e024.png)

Same save, with Fast Track:
![sensor-2](https://user-images.githubusercontent.com/29225123/224989610-15fb55df-8918-49da-982b-d754bd918f9e.png)
![sensor-3](https://user-images.githubusercontent.com/29225123/224989632-1df3cd22-0b8a-4b5c-b49f-297261407fc1.png)

It worked fine without Fast Track for ~2000 cycles, so I assumed this is a mod issue.

### Testing:

I did some sandbox testing (first **without Fast Track**) and found some weird behavior.

1. Created a room of 182 tiles, and added a critter sensor.
    - Room overlay reads "No room", and "Maximum room size: 128 Tiles"
    - Sensor reads "Outside of room"

This matches your results, so this is probably the test you did.

2. Add a critter to the room.
     - Room overlay now reads "Miscellaneous Room", "Room size: 128 Tiles", "Critters: 1"
     - Sensor works fine, detects one critter

Weird.

3. Remove the critter from the room.
    - Room overlay reads "Miscellaneous Room", "Room size: 128 Tiles", "Critters: 0"
    - Sensor still works, detects zero critters, and correctly sends green if I set it to "below 1"

Even weirder.

4. Out of curiosity, reload the game (without critter in the room)
    - Room overlay reverted to "No room", and "Maximum room size: 128 Tiles"
    - Sensor reads "Outside of room" again

So adding a critter makes the game consider it a room, and makes the sensor work. And even after removing the critter, it keeps considering it a room, and the sensor keeps working, until I reload the game which apparently resets the state to "No room".

This is definitely a game issue, and it happened to work in my colony "by accident" because there always were some Pacu and it never hit the "no critter, no room" state. It would have failed if I had reloaded the game with no Pacu in the room. This is very inconsistent behavior. I will report this to Klei.

I then did the same tests **with Fast Track**. For every of the steps above, the results were:

- Room overlay reads "No room", and "Maximum room size: 128 Tiles"
- Sensor reads "Outside of room", always sends red

So my takeaways from this are:
1. It's wonky in the base game, and only happened to work in my colony by accident (I built the automation with Pacu already in the room, and it never was zero).
2. The mod can only be blamed for behaving different from the base game. Instead of replicating the wonky behavior it consistently refuses to work. Good or bad? I don't know.

**Comment by peterhaneve** [comment]
Good sleuthing. For most reported Fast Track bugs I try to first reproduce it without the mod, and indeed I made the room first and added a critter sensor to it with no critters included.

It would be possible to allow rooms larger than the maximum room size to be evaluated by Fast Track in all cases (not just when critters are in them) by removing just one line of code, but doing so could cause a very noticeable performance loss when those rooms need to be rebuilt. As a room is rebuilt when any critters enter or leave, or when any building is built or demolished in it, very large rooms often are subject to frequent rebuilds that Fast Track tries to prevent.

**Comment by TheRealestMVP** [comment]
I don't know the code, so I'm just guessing here.

> As a room is rebuilt when any critters enter or leave, or when any building is built or demolished in it, very large rooms often are subject to frequent rebuilds that Fast Track tries to prevent.

I see, it's about the rebuilds. Could the rebuild check be bound to the presence of a critter sensor, instead of critters? Sensor presence could be a property of the room, like size, that qualifies that particular room for frequent rebuilds even if size>128.

So, might be a room if size<=128, OR if sensor present and size<=2048 (or some other sane value), in case someone builds a sensor in the open.

> could cause a very noticeable performance loss

When you say loss, do you mean back to vanilla performance, or even worse than vanilla?

If it's back to vanilla only, then how about a mod setting "Limit room size to 128 tiles", defaulting to on, so that affected players can turn off that particular optimization?
