### ISSUE TITLE
Fast Track: Misleading/wrong tooltip

### ISSUE THREAD

**Issue by TheRealestMVP** [peterhaneve/ONIMods#323]
In the mod settings, section "Duplicants", there's a checkbox named "Optimize Sensors", but the tooltip reads "Only check for locations to Idle, Mingle, or Balloon Artist when necessary".

Is this the correct tooltip? I can't make any sense of that, can't see a relation between sensors and dupes idling/ballooning.

**Comment by peterhaneve** [comment]
The code that checks for things like an Idle location is implemented by a class in the game called `Sensors`. Thus, the optimize sensors checkbox actually does optimize sensor classes fairly heavily.

Originally, this optimization fixed more things than just Idle and Mingle, but the optimizations were broken down across several options. Other `Sensor`s that are optimized are covered by things such as "Optimize Debris Checks" and "Cache Paths".
