### ISSUE TITLE
Mod Proposal: Bidirectional Single Pipe Flow

### ISSUE THREAD

**Issue by ayerix** [peterhaneve/ONIMods#325]
Problem: 

I'm not sure whether this is a good place to put a feature request, but seems you guys know game internal logic and proved to be experts and interested in writing new cool stuff. At least you know how to do it. So here it is )

My problem is following (and I'm hundred percent sure it's not only mine). Assume we have two storages of liquid or gas. What I'm trying to achieve is to pump all liquid/gas from one to another and back by pressing signal button. In other words upload to or download substance from main to reserve or back. But using single (!it's the essence) pipe to travel substance back and forth. Why single? I want my base to be integrated into environment and not hurt it too much by paving double-wide route for pipes (yes, it is easily may be done with two pipes: forward and reverse, but this is not perfect). So I prefer to lay pipes behind the stairs and logic tells me single pipe is enough to push liquid or gas in particular direction that may change to or from but this two possible states never mixed up. But this interconnection can't work this way since you should have both input and output on both ends of the network so you have 2 producers and 2 consumers on both ends. This doesn't work, this blocks all flow completely. But. Since this scheme is automated with blockators actually there is allways only one active(!) producer at a time simultaneoucly. The second one is disabled. But game doesn't understand this. It still doesn't work. So the problem for the scheme is that turned off blockator is still considered an output and blocks the flow everywhere connected anywhere. But it's turned off, it shouldn't be taken into account, it's disabled. 

What is supposed to do. The ideal solution here is unachievable, for sure ) it is to fix pipe flow algorithm to following consumers take the substance from the bordering cell, this one by chain this cell takes it to the folllowing and all way upper to the producer never visiting allready visited cells. There should be no pathes from producers to consumers at all, the concept is wrong initially. This would be correct but too costly, it's game core and overingineering. But. There are two options for light fix this:

Option A. the problem would be fixed if we just somehow disable the output of disabled liquid/gas blockator (receiving red signal). To somehow force function that enumerates all inputs/outputs when building pipe pathes skip (bypass) disabled outputs and build pathes if they had never been existed. Visible visually, but skipped when reconsidering plumbing inputs/outputs since logically disabled. On changing automatic signal from red to green and back - unlock and refresh the scheme

Option B. add some valve or something like this (new structure). This structure should point the direction of the pipe beneath it (only from top to bottom or vice versa) and proxy (mask) plumbing subnetwork with a single input or output port (i.e. separate pipes subnetwork with only one way in or out but automatically controllable). Similar to pipe bridge is doing. But with swappable in/out ports on red/green signal receiving respectively.

Both options solves the problem and seems to me as the very useful and desirable mod to be done. I tried to find some kind of this mod in the collection but not succeeded ) so I write here just in hope to be heard. Thanks in advance

**Comment by peterhaneve** [comment]
It would be better to post this idea on https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/ to reach a wider audience if someone is interested in coding this mod.

**Comment by ayerix** [comment]
Ok, thank you for advice, I'll follow it. Btw: I understood I was wrong in assumption that building pathes between producers and consumers was an eroneous idea. It's ok. My algo would work well if there is a substance to move, but it won't if no. Of course we can move negative amounts over the network, but this solution would eventually spread negative potentials in dead-ends without producers, so it's wrong idea. Better one is just to serve all active pathes, not only the shortest one. I.e. with producing producer and consuming consumer and normalize the final producer's value among all them to feed all consumers that want to. But generally to have all pathes on hands is correct, although it will grow drammatically if somebody would build a plumbing with a lot of cycles. But this is another problem and may be solved by limiting its count say with 1000 no more
