### ISSUE TITLE
Queue for Sinks - dupes don't wash hands

### ISSUE THREAD

**Issue by UlyanaLeyana** [peterhaneve/ONIMods#326]
## Expected Behavior

just basic game
## Current Behavior

sometimes dupes don't wash their hands if they're standing in queue and someone washed their hands before them, they will just walk by and not wash their hands
## Mod Versions

steam version 3.10.0.0
## Steps to Reproduce

1. 7 dupes in toilet room
2. 2 sinks
3. 
4.

**Comment by peterhaneve** [comment]
Reactions in general were broken in the base game by Klei a few patches ago in an attempt to fix Duplicants getting stuck in the eating animation, and are far less reliable than they used to be. Queue for Sinks is not immune to these changes. Unfortunately, without a base game fix, there is no way to solve this problem from a mod.

Possible workarounds could be to adjust scheduling or add a few more sinks to keep all Duplicants in line.

**Comment by peterhaneve** [comment]
An ugly workaround for this base game bug has been added to the latest version of Queue for Sinks that should drastically reduce instances of Duplicants getting by without washing. Some cases may still occur - report this bug to Klei if the fix matters to you.
