### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by kohonac** [peterhaneve/ONIMods#328]
## Expected Behavior

i am playing with DLC enabled and on stable branch
## Current Behavior

the game has been crashing at random time while doing multiple things. sometimes while in a rocket, others while watching a dupe eat, among other typical game play.
its been happening for a about a week, the only mod the game flags is FT. Im not even sure its a issue with FT but I am horrible at reading the log, so if its not FT relate if you could point me in the right direction it would be appreciated
ty in advance for all you do 
## Mod Versions

local and 0.10.9

## Steps to Reproduce

1.
2.
3.
4.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11027186/Player.log)

**Comment by peterhaneve** [comment]
Fast Track will be blamed for every crash even if not responsible. The log attached is not from the correct run of the game - logs must always be uploaded immediately after crashing.

**Comment by kohonac** [comment]
it was, i didnt restart the game after that crash till i made the ticket and uploaded it, i also know that fast track gets blamed a lot by the game. its the only thing that keep popping up tho which is why i made the ticket. if it not related to FT i will close this and try to find what is crashing the game.

Again ty for your time and effort in this and all the things you do for the community
