### ISSUE TITLE
Crash on bate U46

### ISSUE THREAD

**Issue by LimA0LiN** [peterhaneve/ONIMods#329]
Exception while loading mod PeterHan.FastTrack at C:/Users/limao/Documents/Klei/OxygenNotIncluded/mods/Local/FastTrack. 
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at PeterHan.PLib.Database.PLocalization.Register (System.Reflection.Assembly assembly) [0x00010] in <e4d362d5dcc1498b8f50369b1212a240>:0 
  at PeterHan.FastTrack.FastTrackMod.OnLoad (HarmonyLib.Harmony harmony) [0x0003c] in <e4d362d5dcc1498b8f50369b1212a240>:0 
  at KMod.DLLLoader.LoadDLLs (KMod.Mod ownerMod, System.String harmonyId, System.String path, System.Boolean isDev) [0x0028f] in /home/build/workspace/game/Assets/scripts/Mods/ModDLLLoader.cs:169 

UnityEngine.Debug:LogError (object,UnityEngine.Object)
Debug:LogError (object,UnityEngine.Object) (at /home/build/workspace/game/Assets/Plugins/Debug.cs:163)
DebugUtil:LogErrorArgs (UnityEngine.Object,object[]) (at /home/build/workspace/game/Assets/Plugins/Klei/util/DebugUtil.cs:217)
DebugUtil:LogException (UnityEngine.Object,string,System.Exception) (at /home/build/workspace/game/Assets/Plugins/Klei/util/DebugUtil.cs:227)
KMod.DLLLoader:LoadDLLs (KMod.Mod,string,string,bool) (at /home/build/workspace/game/Assets/scripts/Mods/ModDLLLoader.cs:185)
KMod.Mod:Load (KMod.Content) (at /home/build/workspace/game/Assets/scripts/Mods/Mods.cs:864)
KMod.Manager:Load (KMod.Content) (at /home/build/workspace/game/Assets/scripts/Mods/Mods.cs:1530)
Global:Awake () (at /home/build/workspace/game/Assets/scripts/game/Global.cs:419)
UnityEngine.Object:Instantiate<UnityEngine.GameObject> (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform)
Util:KInstantiate (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.GameObject,string,bool,int) (at /home/build/workspace/game/Assets/Plugins/Klei/util/Util.cs:254)
Util:KInstantiate (UnityEngine.GameObject,UnityEngine.GameObject,string) (at /home/build/workspace/game/Assets/Plugins/Klei/util/Util.cs:226)
LaunchInitializer:Update () (at /home/build/workspace/game/Assets/scripts/game/LaunchInitializer.cs:80)

Build: U46-548880-S

**Comment by peterhaneve** [comment]
Fast Track does not support public testing branches, as they change every few days. If Fast Track is important to you, consider staying on the stable branch for now.
