### ISSUE TITLE
needs to be updated for 2.2

### ISSUE THREAD

**Issue by McyD** [peterhaneve/ONIMods#33]

**Comment by peterhaneve** [comment]
Not sure which mod this is referring to, but consider installing Mod Updater (https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) and force updating any mods that are out of date.

**Comment by McyD** [comment]
Sorry, I did not realize your Github covered multiple mods.  Stockbugfix is broken in the latest hotfix and crashes the game on startup.
