### ISSUE TITLE
FastTrack crashes the game on third load of a save

### ISSUE THREAD

**Issue by Carterpersall** [peterhaneve/ONIMods#331]
## Expected Behavior
Spaced Out: installed
Build: U45-546664-5
Expected Behavior: Game doesn't crash

## Current Behavior
On the *third* time a save is loaded, the game crashes

## Mod Versions
Local Version: [Beta 0.10.9](https://github.com/peterhaneve/ONIMods/releases/tag/FastTrackBeta)

## Steps to Reproduce
1. Load any save file
2. Pause the game and load any save file
3. Repeat and game crashes while loading

## Output Log
[Player - Copy.log](https://github.com/peterhaneve/ONIMods/files/11083557/Player.-.Copy.log)

**Comment by peterhaneve** [comment]
```
D3D shader create error for vertex shader [0x80070057]
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
```

This log has multiple graphics-related issues which could be the cause of your problem. However the "Debug Console" mod disables logging from other mods to the file, making it impossible to debug the true root cause of any crash.

Try temporarily disabling DGSM, No Drop and DGSM and seeing if the problem goes away.

**Comment by Carterpersall** [comment]
> ```
> D3D shader create error for vertex shader [0x80070057]
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
> ```
> 
> This log has multiple graphics-related issues which could be the cause of your problem.

I have a GTX 750 Ti 2Gb so it's possible it's causing some issues

> Try temporarily disabling DGSM, No Drop and Debug Console and seeing if the problem goes away. Otherwise, add a new log with Debug Console turned off.

The issue still occurs with all mods disabled except FastTrack
[Player.log](https://github.com/peterhaneve/ONIMods/files/11084798/Player.log)

**Comment by peterhaneve** [comment]
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at FastReader.ReadBytes (System.Int32 length) [0x0000b] in <676c504a1fc44f1f988e436496061541>:0 
  at SaveGame.GetHeader (IReader br, SaveGame+Header& header, System.String debugFileName) [0x00040] in <8d3d5debc4074b28a2c8baaa0784686c>:0 
  at SaveLoader.LoadHeader (System.String filename, SaveGame+Header& header) [0x00026] in <8d3d5debc4074b28a2c8baaa0784686c>:0 
  at SaveGame.GetFileInfo (System.String filename) [0x00000] in <8d3d5debc4074b28a2c8baaa0784686c>:0 
```
This save file appears to be corrupt, or a mod that is unsafe to remove from a save was removed. Based on the log messages like `RockCrusherComplete removing missing recipe from queue: RockCrusher_I_Granite_O_CrushedRock_Sand`, it appears that the latter is more likely.

Fast Track does not affect save loading, so it is unlikely to be the cause.

**Comment by Carterpersall** [comment]
I created a new save file with only fast track active and observed the same issue ([Player.log](https://github.com/peterhaneve/ONIMods/files/11101718/Player.log)). I then deactivated the mod and the crashes went away ([Player.log](https://github.com/peterhaneve/ONIMods/files/11101729/Player.log)).

Here's my config file: [config.zip](https://github.com/peterhaneve/ONIMods/files/11101778/config.zip)

**Comment by peterhaneve** [comment]
This crash is a native code crash, which is impossible to debug as no log information is emitted. It is usually caused by memory or resource exhaustion.

It is nearly impossible to fix as it does not reproduce on other machines, but I did search for and fix a few resource and thread leaks. The latest version 0.10.10 may resolve your issue.
