### ISSUE TITLE
Crash after Update to U46-660759-5

### ISSUE THREAD

**Issue by Carterpersall** [peterhaneve/ONIMods#332]
## Expected Behavior
Spaced Out is installed

## Current Behavior
Game Crashes

## Mod Versions
Local Copy - v. 0.10.9.0

## Steps to Reproduce
1. Update to the most recent version of the game
2. Install and Enable Fast Track
3. Launch Game
4. Profit

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11116604/Player.log)

**Comment by Apprisco** [comment]
Seconded, crashing with fasttrack unfortunately. Can't wait for an update!
