### ISSUE TITLE
Version 10.10 crashes on latest update (Build U46-550759-5)

### ISSUE THREAD

**Issue by The-Toblin** [peterhaneve/ONIMods#333]
## Expected Behavior

Game should launch

SO is installed, no other mods active (though I did test with other mods and the behaviour is the same)

Game launches fine without FastTrack active.

## Current Behavior

Game crashes with the "Oops" screen.

## Mod Versions

Local install of FastTrack beta 10.10

## Steps to Reproduce

1. Install latest fasttrack
2. Launch game
3. Explode

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11119624/Player.log)

**Comment by Apprisco** [comment]
Update has been released. Although i'm about to post a bug report.

**Comment by peterhaneve** [comment]
It appears that a minor rename completely broke No Diseases. Normally the mod is not tested with this option enabled. This option has been fixed in 0.10.11.
