### ISSUE TITLE
FastTrack causes incredible shader bug mixed with debug ctrl F on latest

### ISSUE THREAD

**Issue by Apprisco** [peterhaneve/ONIMods#334]
Expected:
![image](https://user-images.githubusercontent.com/34324909/229083592-d78b7a18-a389-428e-bdb1-633c458adfa4.png)

Actual:
![image](https://user-images.githubusercontent.com/34324909/229083629-75fce853-4f11-4123-897c-7cc3116e1b69.png)

Seems to be an issue with control F, but disabling fasttrack fixes it. Unsure what could possibly be causing it. On latest version.

**Comment by Apprisco** [comment]
https://forums.kleientertainment.com/forums/topic/138444-beta-fast-track-performance-mod-for-oxygen-not-included/page/12/#comment-1627728

**Comment by Apprisco** [comment]
If it's any help, it's threaded tile updates that's causing this.
Additionally, in my case enabling control F and saving the game refreshed it enough to play, but switching planetoids or turning off control F brought the glitch back.

**Comment by peterhaneve** [comment]
Debug options like Ctrl+F are not officially supported with Fast Track and may cause unusual behavior. Nevertheless, version 0.10.11 now force flushes shader parameters when this option is toggled, which should make it more reliable.

**Comment by The-Toblin** [comment]
Uhm, this now happens even without debug mode on. I haven't run debug mode and I now have two planetoids completely without geometry. Liquids are showing, but nothing else.
