### ISSUE TITLE
FastTrack causes radbolt achievement impossible, option turned off.

### ISSUE THREAD

**Issue by Apprisco** [peterhaneve/ONIMods#335]
The radbolt 10km achievement will always remain at 0km with fasttrack enabled.
Could this be updated? It's not clear which option causes this, the ones that disable achievements are already disabled.

Latest version of fasttrack!

**Comment by The-Toblin** [comment]
I can confirm that on version 10.9, this does not occur as I just recently got that achievement myself.

**Comment by peterhaneve** [comment]
The achievement works fine in local tests. If sandbox or debug mode was used on the save where the achievements should be counted, make sure to set the `Disable Achievements` option to *Never*. If all else fails, consider resetting the mod options to default.

**Comment by Apprisco** [comment]
All of the options were set as told.
