### ISSUE TITLE
With update 10.11, several planetoids are completely missing geometry graphics. Liquids are showing, but nothing else

### ISSUE THREAD

**Issue by The-Toblin** [peterhaneve/ONIMods#336]
## Expected Behavior

The planetoids should render properly.

Spaced Out installed.

## Current Behavior

When loading three of the planetoids in my cluster, they show absolutely no geometry or other sprites. Liquids are visible, but everything else is rendered blank (aside from space and background tiles)

## Mod Versions

Locally downloaded copy of FastTrack version 10.11

## Steps to Reproduce

1. Install SO
2. Install 10.11 of Fasttrack (**and enable Threaded Tile Updates**)
3. Visit all planetoids
4. Observe some of them having no geometry

This does not occur with FastTrack disabled, or the FastTrack threaded tile updates disabled.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/11125677/Player.log)

**Comment by peterhaneve** [comment]
It looks like this issue only occurs on certain planetoid layouts, and not the test layout that was being used. A new version has been pushed that should fix all problems with planetoids.
