### ISSUE TITLE
Airlock mod broke before last update

### ISSUE THREAD

**Issue by Grimelord82** [peterhaneve/ONIMods#337]
My man! You don't read your steam pages..so... I've never used Github. Ping me at contra.mech@gmail.com if there's some details that will help, like a dump-log.
Airlock was a fantastic mod that I used on multiple colonies a year ago.
It broke sometime after Spaced Out, and we just got a small update for meteors. 
ONI crashes to desktop after disabling the mod. Issue seems very common based on steam comments.
Hope you're well.

**Comment by Dave247** [comment]
I saw the comments but can't say I personally have experienced any noticeable issues with the mod itself.

**Comment by peterhaneve** [comment]
Issues this old are usually caused by outdated mods, as ONI does not auto-update mods. If you are using the Steam version, you will need to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
