### ISSUE TITLE
Any tutorials on using Plib GUI functionality?

### ISSUE THREAD

**Issue by makotech222** [peterhaneve/ONIMods#34]
I'm having some trouble getting the GUI functionality working properly. Are there any full tutorials on using them?

My personal use case is to create a sidescreen for my building and just having some text inputs. My first issue is that when i set the text input on one instance of the building, the screens for all buildings get set as well. Second, there seems to be no way to programmatically set the text of the input after initialization.

Heres a screen of the constructor
![image](https://user-images.githubusercontent.com/4389156/77237167-ce13f380-6b93-11ea-9254-b4cd11e20deb.png)

**Comment by peterhaneve** [comment]
There is currently no full tutorial on GUI functions. For setting the text of a text field after initialization, save the realized game object (either through manually `Build` / `AddTo` on the input, or adding a callback to `OnRealize` that saves a reference to the game object). `PUIElements.SetText` can then be used to update the text field contents.

Side screens use a shared instance of the `SideScreenContent` class. The `SetTarget` method needs to be implemented to properly update the side screen display fields to match the selected object.
