### ISSUE TITLE
Started crashing as of today.

### ISSUE THREAD

**Issue by michaelboisjr** [peterhaneve/ONIMods#340]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by isochronous** [comment]
Give literally any information if you want this addressed. The form isn't optional.

**Comment by peterhaneve** [comment]
The form is not optional for a reason, there is no information on which mod may be affected or whether it is just an out of date version without an output log or some symptom of a crash. The Steam version of Oxygen Not Included does not auto-update mods in many cases.
