### ISSUE TITLE
Default value of Efficient Supply Mod

### ISSUE THREAD

**Issue by WoodyPampa** [peterhaneve/ONIMods#341]
It's not really an issue but a question, maybe a stupid question...

It's about the "Efficient Supply Mod",  you wrote that the minimum percentage (0 to 100) of the total material required is by **Default 25%**.
But...
- Is it 25% as default value set with this mod ?
- Or it is the default vanilla value in the game ?

Sorry again if it sound stupid...
I know that when I open the open the settings of the mod, I can change the value and that 25% is set by default, but what I don't know is if you set 25% by default because it's the same value in the Vanilla game, or not.
I tried to find the answer but I didn't found any valuable source.
 
 
 
 
PS: 
I would like to use this message as an opportunity to express my gratitude.
I'm using your Mods since a very long time now and so many of them was able to be in the game from the start (and the proof is that some of your mods have their features added to the game today :wink:

So a big Thanks you for all theses years, for your time and hard work on them, and to share all theses great Mods idea with us :sparkling_heart:

**Comment by peterhaneve** [comment]
25% is the default minimum fetch errand size set by this mod. The base game does not have any restriction on the minimum amount, a Duplicant could cross the entire asteroid to fetch 0.01 g of Iron for a 800 kg request, so the vanilla value is effectively 0%.

**Comment by WoodyPampa** [comment]
wooow, ok, that a huge improvement so, thank you for the fast answer! 👍
