### ISSUE TITLE
'Airlock Door' mod - duplicants unable to path through door no matter what

### ISSUE THREAD

**Issue by Thundercraft** [peterhaneve/ONIMods#342]
## Expected Behavior
If the player sets the permissions correctly in the menu accessible through the Airlock Door building, then the duplicants given said permission should be able to pass through the door - at least if going in the permitted direction.

BTW: Yes, I do have the Spaced Out! DLC installed and active.
No, I am *NOT* using any of the public preview branches. I'm using the current, public branch (Build 552078).

## Current Behavior
No matter what I do, there is currently no way to have duplicants successfully use this Airlock Door as a door - to pass through it! Yes, I did set the permissions in the menu to each of my duplicants to pass through this door. Yes, I set the permissions to pass in *both* directions. Yes, I made sure that my Airlock Door was powered with sufficient power. But even so, my duplicants absolutely refuse to pass through it.

I tried to force them to go through the Airlock Door with the "Move to" command, but the mouse cursor is a red "invalid" or "inaccessible" and won't allow me to click. I tried giving commands to make them go through, such as to sweep something or carry something, but they dropped whatever they're carrying and stand idle from having no path.

## Mod Versions
I tried using this through a Steam Workshop subscription.
Yes, I did try to force update using Mod Updater.
Moreover, I tried this with and without Mod Updater.
And I tried this mod without any other mod active.

## Steps to Reproduce
1. Build Airlock Door.
2. Supply Airlock Door with sufficient power through batteries and power cable/lines. The "no power" icon disappears...
3. Set permissions on Airlock Door such that all duplicants have permission to pass through from either direction. (I absolutely double and triple checked this...)
4. Try clicking on a nearby duplicant (with permission to pass) and in their menu, click the "Move to" button. Then try clicking on a location on the opposite side of the Airlock Door. Notice that the mouse cursor changes to a red "invalid" icon and clicking on a location becomes invalid because the game can not find a path.
5. Try giving a duplicant a job that would force them to use the Airlock Door to complete it. I tried a "sweep" command on a food item that should take them through the Airlock Door as it was the only path to the Refrigerator and Ration Box. But the sweep icon on said food item was red, indicating that there is currently no valid path to a storage that accepts said item. I also tried locking a duplicant in a room with the Airlock Door as the only exit. Then I gave a sweep command to an item in that room. The sweep icon was white, indicating that there was a storage that accepts the item. But the duplicant just stood idle as it did not seem to know a valid path exists.

## Output Log
Unfortunately, I've rearranged my mod list more than once since I tested this mod and I did not know at the time that I was supposed to save my log as I did not experience an error message.

**Comment by peterhaneve** [comment]
Without a log there will not be much to go on, but one of the most common mistakes is not having a location to stand while passing through the door. Make sure that there is a continuous floor under the entire door and a location to stand right next to the entry and exit. Duplicants sometimes have trouble waiting farther away and jumping into the door when it opens.
