### ISSUE TITLE
Abnormal food temperature

### ISSUE THREAD

**Issue by LimA0LiN** [peterhaneve/ONIMods#344]
Problem: After the version update, the food is circulating in the pipeline, and the temperature of the food is locked at 1 degree Celsius and will not decrease. Just like a picture.

Add: But the temperature of my metal brick is -31 degrees, and it will only recover after restarting the game. Known 12 versions do not have this issue.
![GWM@0G C(3{LM~` Y P~D%X](https://user-images.githubusercontent.com/32559936/232292826-d02110b3-7655-4b3f-8f9d-4287fc0acf4e.png)

**Comment by LimA0LiN** [comment]
Add some pictures：
![image](https://user-images.githubusercontent.com/32559936/232294468-8724a432-b725-47f4-8587-edc5ad7f5d12.png)
![image](https://user-images.githubusercontent.com/32559936/232294499-7edfc856-100d-46ca-bfe3-58c57cdb99c5.png)

**Comment by peterhaneve** [comment]
This is a [base game bug](https://forums.kleientertainment.com/klei-bug-tracker/oni/food-stuck-at-1-celsius-on-a-conveyor-until-reload-r37744/). Upvote the post on the Klei forums if you want to see it fixed!
