### ISSUE TITLE
The sandbox tools cause the game to crash.

### ISSUE THREAD

**Issue by 2638823706** [peterhaneve/ONIMods#346]
If it ' convenient for you,please fix the mod.THanks.

**Comment by peterhaneve** [comment]
There is no information here to debug the crash. The most likely cause is an outdated version, as Oxygen Not Included usually does not auto-update mods if using the Steam version. [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) will solve most update problems.
