### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alexander-cg** [peterhaneve/ONIMods#349]
Perhaps add an option to make the doors out of insulated material to help mitigate heat? Regardless, great mod. Thanks.

**Comment by peterhaneve** [comment]
Airlock doors must have some kind of drawback for their tech level, as they had to be early enough in the tech tree to become viable alternatives to liquid locks. A separate building might be viable, but changing existing airlocks is infeasible to avoid breaking saves.
