### ISSUE TITLE
Smart pumps broken

### ISSUE THREAD

**Issue by gouldjw** [peterhaneve/ONIMods#35]
Causes crash on game start in latest update.  Thanks!

**Comment by BierTier** [comment]
Can confirm, since the latest update, this mod is broken. Crash on start as the author states. Please fix, this mod is a life-saver / game-changer :)

**Comment by peterhaneve** [comment]
Try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update Smart Pumps to the latest version. If that still fails, download a [local copy](https://github.com/peterhaneve/ONIMods/releases/tag/ModsLatest).

**Comment by gouldjw** [comment]
Done.  Still crashes in newest update.  Almost all my mods crash if they haven't been updated since March 5 as ONI seems to have broken nearly all of them with the new version.  This hasn't been updated since February.

**Comment by stcarlso** [comment]
Smart Pumps was updated on 2/19 while the preview was still in beta, and is still compatible with the latest version of Oxygen Not Included. Does it crash if it is the only mod enabled?

**Comment by BierTier** [comment]
I tried it with only this mod. This is the only mod in my list that crashes the game.  I also uninstalled, and reinstalled it manually and via steam, same result.

**Comment by peterhaneve** [comment]
I cannot reproduce this issue. Please provide an output log (located in `%userprofile%\AppData\LocalLow\Klei\Oxygen Not Included` on Windows).
