### ISSUE TITLE
Feature Request for: SandboxTools

### ISSUE THREAD

**Issue by mgdav31** [peterhaneve/ONIMods#352]
Is it possible for DestroyParameterMenu.cs to set the state of the checkbox based on which overlay is open?

The OG deconstruct/cancel will choose "Power Wires" if the power overlay is open, and of course it does that same with the most other overlays.

Thanks! Great mods btw

**Comment by peterhaneve** [comment]
While this functionality is not exactly the same as Deconstruct (and it only works *without* Advanced Filter Menu installed), Sandbox Tools 3.8 now automatically switches the Destroy mode in a limited selection of overlays since 0cecf76.
