### ISSUE TITLE
Dupes Refrigeration

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#353]
It would be nice to be able to localize into another language.

**Comment by DarkEviL88** [comment]
And for some reason, disabled fridges in the settings are still displayed in the game.

**Comment by peterhaneve** [comment]
This repository is not the correct one for reporting issues with "Dupes Refrigeration". If you want to report an issue with [that mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2021324045), it needs to be done on the mod comments or directly with Ronivan.
