### ISSUE TITLE
Show Building Ranges crashes when selecting buildings that tthe mod shows ranges for.

### ISSUE THREAD

**Issue by zarquan314** [peterhaneve/ONIMods#354]
When I have Show Building Ranges enabled and I attempt to build an enclosed telescope (and many other buildings) in the Public Testing branch of the Spaced Out DLC, it crashes the game.

One thing to note is that autosweepers are not affected by this.  Every other building I tried that shows a range crashes the game.

## Expected Behavior

It should let me select the building and place it.

Spaced Out! and Testing Branch build U47-559761-SO.

## Current Behavior

The game crashes

## Mod Versions

I am using the Steam version and have forced an update.

## Steps to Reproduce

1.  Enable Show Building Ranges
2.  Select Enclosed Telescope or Gas pump or Deodorizer or probably many other buildings (not autosweepers though) from Build Menu
3.  Attempt to place the building

Alternatively:
1.  Find an existing building that shows a range (Enclosed Telescope or Gas pump or Deodorizer)
2.  Select it.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11643233/Player.log)

Stack Trace from crash:
TypeLoadException: Could not resolve type with token 010000ae (from typeref, class/assembly KAnim, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)

PeterHan.PLib.Buildings.ColoredRangeVisualizer.CreateVisualizers () (at <3e76e0f82f3f407686c424261d5371dc>:0)
PeterHan.PLib.Buildings.ColoredRangeVisualizer.OnCellChange () (at <3e76e0f82f3f407686c424261d5371dc>:0)
CellChangeMonitor.RenderEveryTick () (at /home/build/workspace/game/Assets/Plugins/Klei/util/CellChangeMonitor.cs:200)
Game.Update () (at /home/build/workspace/game/Assets/scripts/game/Game.cs:1367)

Build: U47-559761-SD

**Comment by peterhaneve** [comment]
There is no support for public testing branches until they launch to the live branch. If this mod matters to you, consider playing on the stable branch for now.

**Comment by zarquan314** [comment]
Yeah, but the testing branch is going to be the live branch, so I thought you should know.
