### ISSUE TITLE
Fast Track: Graphics glitch

### ISSUE THREAD

**Issue by pixelkritzel** [peterhaneve/ONIMods#355]
If a building is skinned by a Klei blueprint the duplicants are rendered on a z-layer beyond the building.

With Fast Track
![image](https://github.com/peterhaneve/ONIMods/assets/1437379/ec366ef0-2fe6-4307-8d2f-202756ece1ad)

Without Fast Track
![image](https://github.com/peterhaneve/ONIMods/assets/1437379/72399235-2813-4ee9-b6cf-00880487b257)

**Comment by peterhaneve** [comment]
This issue has already been fixed in development versions, but will not be released until the public testing branch goes live, as it was just a visual error and did not affect gameplay.

**Comment by pixelkritzel** [comment]
Thank you for the reply.
