### ISSUE TITLE
Fast Track: Clicking on a Metal Refinery crashes the game if "Reduce Allocations" is disabled while "Side Screens" is enabled 

### ISSUE THREAD

**Issue by Squ1dCake** [peterhaneve/ONIMods#356]
Running the latest stable Steam version of Spaced Out!. Using version 0.10.14 of Fast Track, locally installed.

Self-explanatory title. If the "Reduce Allocations" setting is disabled while the "Side Screens" setting is also enabled, opening the Metal Refinery UI crashes the game.

Steps to Reproduce:
1. Disable "Reduce Allocations" in the config.
2. Enable "Side Screens" in the config.
3. Create or load a save.
4. Build a Metal Refinery, and then click on it.

Crash Log:
[stacktrace.txt](https://github.com/peterhaneve/ONIMods/files/11671549/stacktrace.txt)

**Comment by peterhaneve** [comment]
This issue has been fixed in a6fc38219b3f6b68dacff082b1e07917b067793b. As this issue is due to an unusual combination of options, a new version will not be released until the public testing fixes go live anyways.
