### ISSUE TITLE
Gets stuck on one selected element and won't remember selecting "all"

### ISSUE THREAD

**Issue by alina-diana-muresan** [peterhaneve/ONIMods#36]
Since the latest update the mod has started to get stuck on one selected element and will not remember selecting "all" between game reloads. The only fix is to remove the mod, load the game, save and re-add the mod. Would love to have a proper fix. :)

**Comment by peterhaneve** [comment]
This issue has been fixed in 2.4. It turns out that the settings were saved when any particular entry was toggled, but *not when All was toggled*.
