### ISSUE TITLE
Crash in version 11472328

### ISSUE THREAD

**Issue by fudgeum** [peterhaneve/ONIMods#362]
## Expected Behavior

Spaced Out DLC Build ID 11472328, App ID 457140, no public previews
Windows 10

## Current Behavior

Game crashes after a few seconds on loading

## Mod Versions

Steam workshop version as updated 07th Jun 2023

## Steps to Reproduce

1. create an airlock door
2. dupe tries to pass through airlock door
3. game crashes and automatically disables this app

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11772610/Player.log)

**Comment by peterhaneve** [comment]
> Mod AirlockDoor initialized, version 3.9.0.0

You are not actually running the version from June 7th, which is 3.10. Oxygen Not Included has a bug where the wrong mod version will sometimes be displayed, even though the files failed to update. The most reliable workaround is [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
