### ISSUE TITLE
Suggestion: Atmo Sensor Tile Same As Thermo Sensor Tile

### ISSUE THREAD

**Issue by SonJeremy** [peterhaneve/ONIMods#363]
Can you make a version like Thermo Sensor Tile for Atmo Sensor. 

I Also try to [make one based on your mod](https://github.com/SonJeremy/SonJeremy-ONIMods/tree/main/TitleAtmoSensor) but it not change the ambient pressure value.

Regardless, great mod. Thanks ^^.

**Comment by peterhaneve** [comment]
There is no sense making an Atmo Sensor a tile - it would then scan its current tile, but that tile could never contain any gas.

Ideas for new mods probably belong in the [ONI forum](https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/) to reach a larger potential audience of modders.
