### ISSUE TITLE
Mod stopped working after a recent game update.

### ISSUE THREAD

**Issue by CementVoker** [peterhaneve/ONIMods#364]
After a recent game update, this mod stopped working and duplicants now just walk past a busy sink without having to queue.
Don't know what else to add so that's it

**Comment by CementVoker** [comment]
I'm talking about QueueForSink mod, I forgot to add this

**Comment by Cralis** [comment]
I'll confirm this. I saw a second duplicant run past a duplicant using the wash basin. So I set it up so that three would hit it at the same time and the second and third duplicant just ran by the wash basin, every time.

**Comment by peterhaneve** [comment]
Klei indeed broke the mod with U47-561558. Versions 3.12.0.0 and later have been updated to match the new game update. It is very likely that you will need to manually install the new version with [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
