### ISSUE TITLE
Airlock Doors broken

### ISSUE THREAD

**Issue by TheLagWizard** [peterhaneve/ONIMods#365]
Airlock doors crashes whenever a dupe tries to go through one. Spaced out, but this might be a problem without DLC too.

**Comment by MondeZA** [comment]
I can confirm that it happens with Classic and Spaced Out. A dupe can enter the airlock but as soon as they want to exit it crashes for me.

**Comment by db48x** [comment]
Use the ModUpdater mod to grab the latest version; it already has the fix. See commit be5098735196823ebc2307291e768bb784525f35.

**Comment by peterhaneve** [comment]
You have an outdated version of Airlock Door. Make sure to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force an update.
