### ISSUE TITLE
FastTrack does not update Reed Fiber resource count

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#366]
Reed Fiber in the resource count on the right side of the screen does not update properly.

In the attached save, 22xFiber Reed is marked for sweeping in the rocket. It'll be delivered to a storage bin on the planetoid, but the resource count for the planetoid will still show 0, even after other resource counts have already been updated.

I've reproduced this with only the FastTrack mod active, default configuration, version 0.11.0 downloaded from the releases.

[a.zip](https://github.com/peterhaneve/ONIMods/files/11785928/a.zip)

**Comment by peterhaneve** [comment]
While I could reproduce your exact issue, even with this save, one of the most common causes (the base game bug of pickupable cached cell corruption when leaving a rocket) has a workaround in 0.11.1.
