### ISSUE TITLE
Smart Pumps Config

### ISSUE THREAD

**Issue by damiendier** [peterhaneve/ONIMods#367]
Please can you add a config to be able to change the consumption and the speed of the pumps ?

**Comment by peterhaneve** [comment]
It looks like you could use [Customize Buildings](https://steamcommunity.com/sharedfiles/filedetails/?id=1818138009) to alter the pumps, as it supports most mods.

**Comment by damiendier** [comment]
Thanks, I didn't even know this mod existed.
