### ISSUE TITLE
0.11.1 not compatible with Spaced Out!

### ISSUE THREAD

**Issue by lyzzidc** [peterhaneve/ONIMods#368]
I have installed Fast Track 0.11.1 into the local mods folder, load the game, go to enable mod but it says it's not compatible with Spaced Out.

## Expected Behavior
I should be able to enable it with Spaced Out activated
Spaced Out is installed

## Current Behavior
Mod not compatible with Spaced Out

## Mod Versions
local copy from Klei forums

## Steps to Reproduce

1. Download mod from Klei Forum https://forums.kleientertainment.com/forums/topic/138444-beta-fast-track-performance-mod-for-oxygen-not-included/
2. install mod in local mod folder following the instructions on the forum page
3. open game with Spaced Out activated
4. Open Mods Menu in Main menu
5. scroll to Fast Track mod, it cannot be selected

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/11810585/Player.log)

**Comment by peterhaneve** [comment]
Fast Track is not correctly installed - the log shows `FastTrack_0_11.1` which means that Fast Track is nested one folder level too deep. The `FastTrack.dll` file must be in the `mods/local/FastTrack` folder, and not inside a secondary inner folder.
