### ISSUE TITLE
Stock Bug Fix crash caused by instant-building a tile on top of a pre-existing one, then painting over said tile with vacuum, then deconstructing it

### ISSUE THREAD

**Issue by Squ1dCake** [peterhaneve/ONIMods#370]
Running the latest stable Steam version of Spaced Out!, version U47-562200-SD. Using the latest version of Stock Bug Fix, v3.21.0.0, downloaded via the Steam Workshop.

Self-explanatory title. Instant-building a new tile over a pre-existing one, and then using the sandbox tool to paint a vacuum onto it, and then deconstructing it causes the game to crash.

Steps to Reproduce:
1. Build a tile, any tile.
2. Instant-build over that tile with any other tile (besides a mesh/airflow tile. The tile can even be the same type of tile as the first, just built out of a different material). The tile then becomes a ghost tile, which gases and liquids can pass through freely.
3. Paint a vacuum inside of it.
4. Deconstruct it.
5. Congratulations, you have crashed the game!

Output Log:
[Player.log](https://github.com/peterhaneve/ONIMods/files/11857373/Player.log)

**Comment by peterhaneve** [comment]
This appears to be a sandbox only crash relying on already bugged behavior in the base game. Nevertheless, I have suppressed the assert in Stock Bug Fix 3.22.
