### ISSUE TITLE
Fast Track

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#372]
I didn't do anything the game just crashed and disabled Fast Track. sometimes the crash happens as soon as I check the sweep only box in the stock settings. v. 0.11.1.0

[Player.log](https://github.com/peterhaneve/ONIMods/files/11877603/Player.log)

IndexOutOfRangeException: Index was outside the bounds of the array.

PathGrid.GetCost (System.Int32 cell) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
PathProber.GetCost (System.Int32 cell) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
Navigator.GetNavigationCost (System.Int32 cell) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
Navigator.CanReach (System.Int32 cell) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
ClimbableTreeMonitor+Instance.FindClimbableTree () (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
ClimbableTreeMonitor+Instance.UpdateHasClimbable () (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
ClimbableTreeMonitor+<>c.<InitializeStates>b__2_0 (ClimbableTreeMonitor+Instance smi) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
GameStateMachine`4+State+<>c__DisplayClass56_0[StateMachineType,StateMachineInstanceType,MasterType,DefType].<ToggleBehaviour>b__0 (System.Object obj) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
ChoreConsumer.RunBehaviourPrecondition (Tag tag) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
ChorePreconditions+<>c.<.ctor>b__50_37 (Chore+Precondition+Context& context, System.Object data) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
PeterHan.FastTrack.GamePatches.ChoreComparator.RunSomePreconditions (Chore+Precondition+Context& context) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
PeterHan.FastTrack.GamePatches.ChoreComparator.Collect (Chore chore) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
PeterHan.FastTrack.GamePatches.ChoreComparator.CollectNonFetch (System.Collections.Generic.IList`1[T] chores) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
PeterHan.FastTrack.GamePatches.ChorePatches+ChoreProvider_CollectChores_Patch.Prefix (ChoreConsumerState consumer_state, ChoreProvider __instance, System.Collections.Generic.List`1[T] succeeded) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
(wrapper dynamic-method) ChoreProvider.ChoreProvider.CollectChores_Patch1(ChoreProvider,ChoreConsumerState,System.Collections.Generic.List`1<Chore/Precondition/Context>,System.Collections.Generic.List`1<Chore/Precondition/Context>)
ChoreConsumer.FindNextChore (Chore+Precondition+Context& out_context) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
Brain.FindBetterChore (Chore+Precondition+Context& context) (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
Brain.UpdateChores () (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
Brain.UpdateBrain () (at <2bfc01d3c011441f99eda7da2f70c2dc>:0)
PeterHan.FastTrack.PathPatches.BrainScheduler_RenderEveryTick_Patch.UpdateBrainGroup (PeterHan.FastTrack.PathPatches.AsyncBrainGroupUpdater inst, System.Boolean asyncProbe, BrainScheduler+BrainGroup brainGroup) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
PeterHan.FastTrack.PathPatches.BrainScheduler_RenderEveryTick_Patch.Prefix (BrainScheduler __instance) (at <bfe8a69bc8f749278d07799c68999a4f>:0)
(wrapper dynamic-method) BrainScheduler.BrainScheduler.RenderEveryTick_Patch1(BrainScheduler,single)
SimAndRenderScheduler+RenderEveryTickUpdater.Update (IRenderEveryTick updater, System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater.RenderEveryTick (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
(wrapper dynamic-method) Game.Game.LateUpdate_Patch0(Game)

Build: U47-562200-S

**Comment by DarkEviL88** [comment]
Sometimes the crash happens when I make duplicates sweep a bunch of garbage on the highest priority, the game disables Fast Track, ThermalTooltips and Better Info Cards.

**Comment by peterhaneve** [comment]
This issue is a base game bug, as discovered in #327. It is more likely to occur with Fast Track installed as Fast Track increases game performance, making it more likely that the race condition will be hit.

If you want to see this issue fixed, report a base game bug against Klei (see the details in the linked issue).

**Comment by peterhaneve** [comment]
It looks like this issue is being hit often enough to merit a workaround. As of version 0.11.2, Fast Track patches the base game to fix the potential race condition.

**Comment by DarkEviL88** [comment]
It seems to me that Fast Tack conflicts with the NoDrop by Oni mod. I had so many crashes today that it pissed me off, I looked at the crash log and there was fast track and nodrop, I disabled NoDrop and the crashes stopped. I am using the latest version of Fast Track. But without the NoDrop mod, Duplicants bore me with dropping cargo on ladders. And sometimes strange things happen: duplicants pick up the load and immediately drop it, and so on endlessly sometimes the game crashes if you try to stop them, but after a while everything seems to work fine. Maybe the consequences of disabling NoDrop. Does the order in which mods are loaded make any difference?

**Comment by peterhaneve** [comment]
Recent versions of No Drop might be incompatible with Fast Track. But as Ony's mods do not have source code available, adding compatibility will be impossible.

Ony is the only one who can fix the issue, as Fast Track code is available here for her reference.
