### ISSUE TITLE
Game crash when a Dupe takes off their suit at the same time as the Atmo Suit Checkpoint is disabled.

### ISSUE THREAD

**Issue by blake-sc** [peterhaneve/ONIMods#375]
Base game (no Spaced Out)
Fast Track 0.11.1.0

The log locates the crash in Fast Track code.

## Steps to Reproduce

1. The Checkpoint is not disabled
2. The Checkpoint is ordered to be disabled
3. The Duplicant starts taking off their suit at the Checkpoint
4. The Checkpoint is disabled simultaneously with the Duplicant is taking off their suit.

Note: This is what happened when the crash occurred. I don't know if a crash will _always_ occur.

## Output Log

[Player.zip](https://github.com/peterhaneve/ONIMods/files/11956074/Player.zip)

**Comment by peterhaneve** [comment]
It looks like the base game can try to take off the same suit twice if the animation finishes on the exact same frame as disabling the checkpoint. While nearly impossibly rare, a workaround has been added to the latest version of Fast Track.

**Comment by peterhaneve** [comment]
Link to the base game bug: https://forums.kleientertainment.com/klei-bug-tracker/oni/atmo-suit-bug-r38617/

Upvote this bug if you want a real fix, as it is a base game issue.
