### ISSUE TITLE
Fast Track causes a crash with Space Scanner near map edge

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#376]
It seems that FastTrack causes a crash when a space scanner is built close enough to a map edge for its range to reach outside of the map. My save loaded with only vanilla game finishes building the shown scanner fine, adding only FastTrack crashes. Latest FastTrack version from the download section.

## Steps to Reproduce
1. Load the saved game.
2. Wait few seconds for the space scanner build to finish.
3. Crash.

## Output Log
[Dreamland - scanner crash.sav.zip](https://github.com/peterhaneve/ONIMods/files/11961773/Dreamland.-.scanner.crash.sav.zip)
[Player.log.txt](https://github.com/peterhaneve/ONIMods/files/11961775/Player.log.txt)

**Comment by peterhaneve** [comment]
This crash is Linux specific and does not reproduce on Windows. However, as one of the methods on the way was also terribly optimized, a new optimization has been added that also includes a bounds check to hopefully mitigate the issue.
