### ISSUE TITLE
BackgroundRoomRebuild counts plants incorrectly

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#379]
If FastTrack's option BackgroundRoomRebuild is enabled, plants in rooms may be counted incorrectly.

Current FastTrack version from the download section.

## Steps to Reproduce
- Load the attached game, positioned over a nature reserve with hatches.
- Switch to room overlay.
- Hover mouse over the nature reserve, tooltip says 7 plants.
- Deconstruct and construct again a door of the room.
- Tooltip now says 6 plants, which is incorrect.
- Switch to planetoid Abundial.
- Tooltip for the room with a lake (below the bedroom) says miscellaneous room and no plants, even though there are plants. If BackgroundRoomRebuild is disabled, it says no room and does not provide plant info.

[Player.log.txt](https://github.com/peterhaneve/ONIMods/files/11985005/Player.log.txt)
[Dreamland - plants.sav.zip](https://github.com/peterhaneve/ONIMods/files/11985001/Dreamland.-.plants.sav.zip)

**Comment by llunak** [comment]
NOTE: I actually can no longer reproduce the incorrect plant count, it's either a race condition or it somehow depends on another mod (I originally tested with also other mods enabled, while testing without I accidentally lost my mod configuration and now I cannot reproduce the incorrect count one way or another).

But here's a related problem:
- Instead of rebuilding a door as described above, build a new one in the middle of the room, downstairs from the critter drop-off. This will split the nature reserve into two rooms, both of which should be at least parks, but after the door is built, one of the rooms will not become a park.

**Comment by peterhaneve** [comment]
Building the door downstairs splits the room, but the room on the right is too big for a park; Parks can only be 64 tiles, but it is 78.

The room below the bedrooms on the other planet is larger than the default maximum room size. Whether the room shows up as a miscellaneous room or no room when loading depends on a base game race condition, but plants will not be counted on rooms that are over-sized by Fast Track.
