### ISSUE TITLE
Bulk Move To / Move To By Type functionality

### ISSUE THREAD

**Issue by TexanMD** [peterhaneve/ONIMods#381]
Howdy, thanks for all your mods.

I thought this would fit well in *maybe* the Settings Change Tool, but probably the Sweep by Type mod so thought I'd post here before suggesting it on the forums.

 With the new "Move To" command on debris, I've often found myself wanting to order a move for all of a specific item on a tile (with several types of debris in the same location) or all of a specific item in an area to a different location.    In my mind something like the Sweep by Type with an extra click post selection to set the destination.

**Comment by peterhaneve** [comment]
Please post suggestions for entirely new mods on the Klei forums.

This is not really a good fit for Settings Change Tool as it does not involve changing settings on existing buildings, and Settings Change Tool has already maxed out the number of options supported in the base game's tool option menu. It makes a little sense for Sweep by Type, but it probably should be its own mod.

**Comment by TexanMD** [comment]
Thanks Peter
