### ISSUE TITLE
Annotate FastTrack reimplementations as low priority patches

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#382]
Please annotate FastTrack patches that reimplement game code as [HarmonyPriority(Priority.Last)].

I've been trying to prefix BreathabilityTracker.UpdateData() to fix a problem (avoiding false breathability warnings e.g. when entering a rocket, not really relevant here). It didn't work, because FastTrack replaces the game function using a prefix and FastTrack's prefix was executed first. That's not really wanted, as conceptually FastTrack's patch is rather a replacement than a real prefix. Any FastTrack reimplementation should let prefixes from other mods run first.

Marking such FastTrack replacements as the last priority would keep mods prefixing such methods working. I expect there should be more mods prefixing these functions, so this should keep such mods working seamlessly.

**Comment by peterhaneve** [comment]
Changing every single Fast Track patch (all 1200+ of them) would be swatting a fly with a sledgehammer, and could cause other unexpected compatibility issues. Can the conflicting mod simply use `AboveNormal` priority?

**Comment by llunak** [comment]
> Can the conflicting mod simply use `AboveNormal` priority?

My mod can do that (and indeed it already does), but this is not about my mod, this is meant as a suggestion how to save work, both yours and of developer of other mods. How much time do you spend on every 'FastTrack mod broken with mod X'? It's your mod, so your choice, but in my one case finding the problem probably wasn't less time than it would be to adjust FastTrack's priorities.

> Changing every single Fast Track patch (all 1200+ of them) would be swatting a fly with a sledgehammer, 

I don't see why you consider this to be a sledgehammer, dealing with problems on one by one basis seems ultimately way more work and complexity than a basically mechanical change that can be scripted (or is that the problem? I can do that).

> and could cause other unexpected compatibility issues.

I know what unexpected means, but still, what do you expect could possibly break? The order of applying patches of the same priority is already sort of arbitrary, so FastTrack's should generally already work if they go last. I don't see how making that defined should make anything worse.

**Comment by peterhaneve** [comment]
`Last` is absolute; there is no way to go after it. `BelowNormal` or `Low` would be reasonable for some Fast Track patches. But this is actually the first conflict that would be resolved merely by a low priority on the patch - almost always, explicit compatibility is required from both ends to make conflicting mods work together with Fast Track, often detecting the other mod by name and using a different patch with custom code.
