### ISSUE TITLE
Crashed when removing from an empty queue.

### ISSUE THREAD

**Issue by Oterzone** [peterhaneve/ONIMods#383]
I received the below error when my queue was empty and I held L shift and clicked anyway. It then crashed.

NullReferenceException: Object reference not set to an instance of an object

Ony.OxygenNotIncluded.ResearchManager.ResearchManager.MoveUp (Tech tech) (at <c993d3d1d74e4367b6fbb402781761d1>:0)
Ony.OxygenNotIncluded.ResearchManager.ResearchManager.SetActiveResearch (Tech tech, System.Boolean clearQueue) (at <c993d3d1d74e4367b6fbb402781761d1>:0)
Ony.OxygenNotIncluded.ResearchManager.Research_SetActiveResearch.Prefix (Tech tech, System.Boolean clearQueue) (at <c993d3d1d74e4367b6fbb402781761d1>:0)
(wrapper dynamic-method) Research.Research.SetActiveResearch_Patch3(Research,Tech,bool)
PeterHan.ResearchQueue.ResearchQueuePatches.OnResearchCanceled (Tech targetTech) (at <92914efaf6d04a41a55f5c70f7e652ea>:0)
PeterHan.ResearchQueue.ResearchQueuePatches+ResearchEntry_OnResearchCanceled_Patch.Prefix (Tech ___targetTech) (at <92914efaf6d04a41a55f5c70f7e652ea>:0)
(wrapper dynamic-method) ResearchEntry.ResearchEntry.OnResearchCanceled_Patch2(ResearchEntry)
Util.Signal (System.Action action) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KToggle.Click () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KToggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U47-562984-S

## Expected Behavior
 I'd assume Nothing.

I have it. I don't have the previews.
## Current Behavior
 It crashed.

## Mod Versions

Steam. I have Mod updater, but I'm set to whatever the default is. I just started this game 5 days ago for the first time.

## Steps to Reproduce

I had a queue set, and wanted to add more. I clicked to do so, but it was removed from the current queue. I kept trying, and when the queue was empty, I tried again, and it crashed.

## Output Log

I have no Log file at that location.

**Comment by peterhaneve** [comment]
You have both Research Manager and Research Queue active; the error occurred in Research Manager. This issue should be reported on Ony's mod.
