### ISSUE TITLE
FastTrack prevents sweeter than honey achievement

### ISSUE THREAD

**Issue by Apprisco** [peterhaneve/ONIMods#387]
## Expected Behavior

With FastTrack enabled, dupes should be able to empty the hives and result in the sweeter than honey achievment.

## Current Behavior
No achievement is reported with fasttrack enabled.

## Mod Versions
Latest FT, local.

## Steps to Reproduce
Self-explanatory.

**Comment by peterhaneve** [comment]
An output log is required to debug almost any issue.

If you have used Debug or Sandbox modes, achievements will be disabled as you would not be able to earn them on Steam anyways. If you care about achievements even in these modes, there is an option in the mod settings to always enable achievements, which are often a substantial impact to frame rate.

**Comment by Apprisco** [comment]
This is not the case. It's very specifically fast track that's preventing the achievement.

**Comment by peterhaneve** [comment]
I cannot reproduce this issue with Fast Track enabled and the _Disable Achivements_ option set to _Never_. Either another mod is conflicting, or you are experiencing a machine specific bug:
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/b10c24db-aebd-49c1-ae61-cbaace05dda2)
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/660bc8ff-1c21-4d9f-a406-cf3471db3f1f)
