### ISSUE TITLE
Clean Drop causes deadlock

### ISSUE THREAD

**Issue by purpleposeidon** [peterhaneve/ONIMods#39]
Start a new world, order some digging to happen, and, well, bad times.

**Comment by peterhaneve** [comment]
I cannot reproduce this issue. Please provide an output log (located in `%userprofile%\AppData\LocalLow\Klei\Oxygen Not Included` on Windows).

**Comment by purpleposeidon** [comment]
This is on Linux.

[Log](https://gist.githubusercontent.com/purpleposeidon/80b0ba4b467dac98ac338bb9ce4dc1f5/raw/958f29deabc4724ff0a0fff13a9e38ecec337b19/gistfile1.txt). In fact, here's [stdout](https://gist.githubusercontent.com/purpleposeidon/d0b8e9a5729fab656bcd3fdf49144443/raw/a3a2424e299fab557293a6bbf6120a663ec279fa/gistfile1.txt). Uh, not really a deadlock, more "crashes the VM"

**Comment by peterhaneve** [comment]
I fixed a memory leak in 1.1 that may resolve your issue. However, nothing else in the stack trace seems remotely related to Clean Drop, and may be a quirk of Mono that will be extremely difficult to reproduce on another system.
