### ISSUE TITLE
FastTrack mod not working.

### ISSUE THREAD

**Issue by dynam1c-afk** [peterhaneve/ONIMods#390]
I downloaded the mod, placed it in mods/local folder and i get this acreen![20230808_204651.jpg](https://github.com/peterhaneve/ONIMods/assets/141769046/9a62f1b5-24c7-43d2-b710-2d239fd95bd0)

The DLL file is inside the folder, along with other 2

**Comment by peterhaneve** [comment]
Please follow the directions in the forum post; it needs to be in the `mods/Local/FastTrack` folder, not in the local folder directly.

**Comment by dynam1c-afk** [comment]
It is placed in that folder, and game detects it, but every time i get this error

**Comment by peterhaneve** [comment]
With no output log file it will be impossible to diagnose the error. Please follow the directions in the issue template.

It is likely that the issue is outside of Faat Track if the crash screen is completely blank.

**Comment by dynam1c-afk** [comment]
Ok, tomorrow i will try to attach the crash log file
