### ISSUE TITLE
Fasttrack and rockets 

### ISSUE THREAD

**Issue by damnlord** [peterhaneve/ONIMods#391]
Hi, 
Thank you for the mod.

I think this is a bug, can you pls check it out if you have the time.
I'm using Space Out, public version , Fast Track 0.12, no other mods.
When the mod is enable and you have a rocket in orbit and you are using Liquid spacefarer port to dump some dirty water , the water accumulate on top of the ship and on the bottom of the map (the map with the space ship) and off gases. You can place mop  (the dups can't get to there) command but then the game crashes . If you are not using the mod, when you use the same port the water disappear immediately

## Steps to Reproduce

1. build spaceship  
2. send dirty water out of if.

[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/12298068/Player-prev.log)

**Comment by peterhaneve** [comment]
You are probably hitting [this base game bug](https://forums.kleientertainment.com/klei-bug-tracker/oni_so/rocket-in-orbit-affects-grounded-rockets-spacefarer-ports-r36649/). Upvote it and provide the save to Klei if you want it fixed!

**Comment by damnlord** [comment]
well without the mod , everything is working fine, if you want i will send you the save file or put some screenshots and logs
