### ISSUE TITLE
NoWasteWant is no longer working as of Song of the Moo update

### ISSUE THREAD

**Issue by SteveFelker** [peterhaneve/ONIMods#393]
## Current Behavior
Game crashes on boot.   A black hole ate my game...  Before even getting to the ONI menu.

## Mod Versions
I subscribed to your mod in the steam workshop.  I unsubscribed, confirmed it was gone, then resubscribed.  Still no luck.  I do not know how to force an update, but I can see your code hasn't been updated in 5 months, and it broke a week ago with the update, so I don't think it's on my end.

## Steps to Reproduce
Add mod,  Start game.  Game crashes on boot.  You don't even get to start or load a game.  It doesn't matter if running Spaced out or Vanilla.  Although vanilla has been broken for a while.  I just started playing again in late June and it didn't work in vanilla.  Worked back then in spaced out.  Since last update, spaced out doesn't work either

## Output Log
Let me work on this and edit....  I accidentally tapped enter while entering the title, so issue is already created....
  
[Player.log](https://github.com/peterhaneve/ONIMods/files/12331695/Player.log)

**Comment by peterhaneve** [comment]
Yes, due to a bug in ONI's Steam mod support, the base game can install any older version of a mod, even one that is months or years old.
