### ISSUE TITLE
Sandbox Tools - Cant spawn oil Resevoir

### ISSUE THREAD

**Issue by Schorch55** [peterhaneve/ONIMods#394]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by peterhaneve** [comment]
Please fill out the template with actual information.

Nevertheless, the Oil Reservoir can now be spawned again in version 3.10. It is likely that this version will need to be manually updated with [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) as Steam does not auto-update mods.
