### ISSUE TITLE
[Feature Request] Waste Not, Want Not:  fix the stupid tree

### ISSUE THREAD

**Issue by jrmoserbaltimore** [peterhaneve/ONIMods#396]
The dupes eat food before it goes bad but the tree doesn't aghhhh!!!

**Comment by peterhaneve** [comment]
Any changes affecting the tree will not be released until https://forums.kleientertainment.com/klei-bug-tracker/oni_so/severe-memory-leak-in-experiment-52b-r42092/ is fixed and released

**Comment by peterhaneve** [comment]
Versions from 1.6 onwards will now cause Experiment 52b to prioritize stale food.
