### ISSUE TITLE
Fast Track: Optimize debirs collection preventing delivery to tasks

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#398]
## Expected Behavior

Duplicants should deliver items to pending builds or requesting buildings

Spaced Out is active, live branch

## Current Behavior

Tasks for the oxygen diffuser and ladder segment in the attached save do not have delivery tasks for duplicants

## Mod Versions

0.12.0, local install

## Steps to Reproduce

1. Load the attached save with Fast Track on default config
2. See how the oxygen diffuser and ladder segment build have no delivery tasks
3. Go back to main menu
4. Disable "Optimize debris collection" in Fast Track options
5. Load game again
6. See the deliver tasks on aforementioned buildings

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/12476578/Player.log)

##Save File
[Galaxy Brain.zip](https://github.com/peterhaneve/ONIMods/files/12476568/Galaxy.Brain.zip)

**Comment by peterhaneve** [comment]
This issue is a mod incompatibility with Priority Zero - you have a Priority 0 storage bin holding algae, which is confusing Fast Track's fetch logic and making it think that no other items are available.

An explicit compatibility workaround has been added in Fast Track 0.12.1.0.
