### ISSUE TITLE
Radiation Tweaks Causes Materials Study Terminal to Collide Radbolts

### ISSUE THREAD

**Issue by mystiana** [peterhaneve/ONIMods#399]
White the terminal is in use, I am firing radbolts at it from a chamber.  If the impact of the radbolts is > 1, the terminal stores the radbolts long enough that the next volley collides with the first.  This causes nuclear fallout.

I also get nuclear waste when the radbolts collide with doors.

![radbolts](https://github.com/peterhaneve/ONIMods/assets/19842595/c6343931-a863-486f-8766-875503346d6d)

**Comment by peterhaneve** [comment]
The precise frame and location where the radbolt is released has been adjusted in 0.12.2 to avoid collisions on exit.
