### ISSUE TITLE
Soft crash/game error when killing critter

### ISSUE THREAD

**Issue by justin-barfield** [peterhaneve/ONIMods#40]
Issue can be easily reproduced by setting a duplicant to attack a critter. Upon the critter's death, the game will freeze and close or display an error on screen asking for the game to restart. The error will disable all mods. The freeze and close does not. Some suggestions in a Discord server recommended disabling this mod and trying to reproduce. Before disabling the mod entirely, I tried to enable the popups for critter behaviors. On testing the game still crashed. Disabling the mod entirely allows the attack action to be performed.

## Expected Behavior
Critter death.

## Current Behavior
Game freeze/crash on attacking and death (unsure of death caused by age) of a critter.

## Mod Versions
Steam subscription
mod updater not installed

## Steps to Reproduce

1. Load game
2. Select attack
3. Attack critter
4. Critter death causes crash

## Output Log

[Game freeze and close](https://github.com/justin-barfield/ONI-Mods/blob/master/output_log_4-8_11-28.txt)
[Game freeze and error](https://github.com/justin-barfield/ONI-Mods/blob/master/output_log_4-8_11-28.txt)

First link is of the game freezing and closing on its own when a critter death by attack occurs.

Second link is of game freezing and causing error in mod when critter death by attack occurs.

**Comment by peterhaneve** [comment]
The issue should be fixed by c509c6b in Popup Control 1.4. Thank you for providing good logs!
