### ISSUE TITLE
Sweep by type not showing tooltip allowing me to filter.

### ISSUE THREAD

**Issue by 11548518** [peterhaneve/ONIMods#401]
## Expected Behavior
  When I click on the sweep tool, or press K a tooltip should pop up allowing me to select what materials I want to sweep up.
 I do have the DLC and not on the public branches.

## Current Behavior
 No filter appears, I can still sweep. I have tried starting new games and had the same issue. I also restarted the game to see if that would help.

## Mod Versions
 I am using Steam. 
 I uninstalled the mod and reinstalled it. I was unable to find the force mod update option.

## Steps to Reproduce

1. Start ONI, start new game.
2. Mine materials
3. click on sweep button on bottom left of screen. 
4. See no filter option or tool tip to select

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/12593167/Player.log)

**Comment by peterhaneve** [comment]
Mods must be enabled through the MODS screen in the main menu after subscribing to them. Otherwise, their content will not be loaded.
