### ISSUE TITLE
Fast Track conflicts with 'High Precision Temperature' and 'Truthful Thermal Conductivity'

### ISSUE THREAD

**Issue by Carterpersall** [peterhaneve/ONIMods#402]
It seems that Fast Track causes the mods 'High Precision Temperature' and 'Truthful Thermal Conductivity' to stop working.

## Expected Behavior

High Precision Temperature shows the temperature of stuff to a higher level of precision and Truthful Thermal Conductivity increases the precision of the shown thermal conductivity of materials (Abyssalite no longer shows 0 conductivity)

Spaced Out is installed

## Current Behavior

The mods don't work when Fast Track is installed. The game doesn't crash, but the mods seem to do nothing.

## Mod Versions

The mods were up to date. Fast Track was on version 0.12.0.0 in the logs, but I have confirmed the bug on the most recent version.

## Steps to Reproduce

1. Install 'High Precision Temperature' and/or 'Truthful Thermal Conductivity'
2. Install Fast Track
3. Mods don't work
4. Open Colony
5. Check if temps and thermal conductivity readings show a higher precision
6. Disable Fast Track
7. Open Colony again
8. Confirm mods are working

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/12624036/Player.-.Copy.2.log)

**Comment by peterhaneve** [comment]
Compatibility workarounds for High Precision Temperature have been added in version 0.12.2. The Truthful Thermal Conductivity behavior for tiles makes a lot of sense, so it is now the default when Fast Track is enabled, with a smart check to avoid displaying more decimal places than required.
