### ISSUE TITLE
[Feature Request] PLib - Options to take into account [EnumMember] on enums.

### ISSUE THREAD

**Issue by nidaren** [peterhaneve/ONIMods#403]
## Edit

I have proposed a "fix" here: #404 

## Expected Behavior

I would like to propose a small addition to the Options generation system.

`Newtonsoft.Json` allows for serializing enums as their custom string names, by using `StringEnumConverter` and tagging enum options with `EnumMember` from `System.Runtime.Serialization`.

It would be awesome, if Options in PLib would also take this into account for display if present - ie.

```cs

[JsonConverter(typeof(StringEnumConverter))]
public enum ModTimeFormat
{
    [EnumMember(Value = "24-hour")]
    TwentyFour,

    [EnumMember(Value = "12-hour")]
    Twelve
}
```

would get displayed as the values given  in `EnumMember`

Currently it serializes it correctly in file however in options the old string values are still used for display.

```json
{
  "Status": 1,
  "TimeFormat": "24-hour"
}
```

## Current Behavior
Enum options are displayed as their string values.

![image](https://github.com/peterhaneve/ONIMods/assets/13212762/3ee78901-1fd0-44a0-a22a-4f9afb7e7212)

**Comment by peterhaneve** [comment]
Further discussion will occur in #404
