### ISSUE TITLE
Game crash with ONI blaming Fast Track

### ISSUE THREAD

**Issue by nepp95** [peterhaneve/ONIMods#405]
The game crashed with ONI blaming fast track, but since fast track covers a lot of ONI features, it might not be the root cause. I do not know exactly what I was doing at that moment except for just playing the game.

## Expected Behavior
It should not crash.

Yes, I have the spaced out DLC installed, using the default branch for ONI, the latest stable version.

## Current Behavior
It did crash.

## Mod Versions
I am using a local copy of Fast Track 0.12.0

## Steps to Reproduce
Unknown.

## Output Log
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/12689550/Player-prev.log)

**Comment by peterhaneve** [comment]
This does not look like a Fast Track issue, as some other mod is creating an invalid chore and Fast Track will just be blamed for every crash. While there is also error spam from Material Color, that mod does not create chores and is also unlikely to be the cause.
