### ISSUE TITLE
Game Crash During Startup Only Fast Track Enabled

### ISSUE THREAD

**Issue by babyblasphemy** [peterhaneve/ONIMods#409]
Game crashed during startup with only the Fast Track mod enabled.

## Expected Behavior
Game loads to main menu without crashing.

## Current Behavior
Game crashes without making it to main menu.

## Mod Versions
0.12.2.0
Game Version: U49-575720-5D

## Steps to Reproduce

1. Disable all mods besides Fast Track.
2. Launch Game
3. Game Crashes after loading for a bit.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/12822771/Player.log)

**Comment by peterhaneve** [comment]
Fast Track will generally only work on one version of the game. Version 0.12.3 has been released with compatibility for U49-575720.

**Comment by babyblasphemy** [comment]
Confirmed that V0.12.3 works, thanks!
