### ISSUE TITLE
ModUpdater Crashes in October 2023 QoL

### ISSUE THREAD

**Issue by mayday6971** [peterhaneve/ONIMods#410]
New October 2023 QoL update is live and this mod now crashes the game.

## Expected Behavior
1. If Mod is enabled, game should load the mod.

## Current Behavior
1. Enable Mod
2. Restart
3. Game Crashes

## Mod Versions
Steam, but I did unsub and resub.

## Steps to Reproduce
1. Enable Mod
2. Restart
3. Game Crashes
4. Game unchecks mod
5. Game loads okay

## Output Log
MissingFieldException: Field 'KMod.Mod.file_source' not found.

(wrapper dynamic-method) KMod.Manager.KMod.Manager.Subscribe_Patch1(KMod.Manager,KMod.Mod,object)
KMod.Steam.UpdateMods (System.Collections.Generic.IEnumerable`1[T] added, System.Collections.Generic.IEnumerable`1[T] updated, System.Collections.Generic.IEnumerable`1[T] removed, System.Collections.Generic.IEnumerable`1[T] loaded_previews) (at <8962180363a94bf7bd897569e6298675>:0)
PeterHan.ModUpdateDate.SteamUGCServiceFixed.Process () (at <f0d664dd0de34361bfff6041220fd91f>:0)
PeterHan.ModUpdateDate.ModUpdateDatePatches+SteamUGCService_UpdatePassive_Patch.Prefix () (at <f0d664dd0de34361bfff6041220fd91f>:0)
(wrapper dynamic-method) SteamUGCService.SteamUGCService.Update_Patch1(SteamUGCService)

Build: U49-575720-S

**Comment by peterhaneve** [comment]
Your copy of Mod Updater itself is out of date. You can try starting the game up with it disabled and seeing if ONI will update the mod for you, as mods are not updated until the main menu is loaded _successfully_. If not, you may need to [manually update](https://github.com/peterhaneve/ONIMods/blob/main/README.md#local-downloads) the mod.
