### ISSUE TITLE
Fast Track Crash

### ISSUE THREAD

**Issue by Superstarlex42** [peterhaneve/ONIMods#412]
## Expected Behavior

Spaced out
## Mod Versions
Local Mod
0.12.3.0

## Steps to Reproduce
no clue, just happened out of nowhere

## Output Log

[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/12887399/Player-prev.log)

**Comment by Superstarlex42** [comment]
oop
Mod Version
0.12.3.0
Steps to Reproduce
just happened out of nowhere
Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/12887369/Player.log)

**Comment by peterhaneve** [comment]
Without reproduction steps it will be impossible to debug, but early signs from the log point towards a vanilla crash introduced in a recent update or a mod incompatibility, as other users without Fast Track on the discord have reported the same error symptoms. If the crash persists, consider filing a bug on the Klei Bug Tracker.
