### ISSUE TITLE
SmartPumps, please add second output

### ISSUE THREAD

**Issue by ShyLionTjmn** [peterhaneve/ONIMods#414]
Please, add second output, whith will output anything, NOT matching selection.

**Comment by peterhaneve** [comment]
Adding this output would be contrary to the purpose of Smart Pumps. The intent of this mod was to only ever pump a particular element in the first place, and leave the others behind.

If you want to set up a pump to separate materials, the vanilla Liquid Filter or one of the community vanilla builds to filter materials in pipes will already satisfy your use case without any mods required.
