### ISSUE TITLE
The Waste Not mod crashes the game after the October 2023 update.

### ISSUE THREAD

**Issue by aantono** [peterhaneve/ONIMods#415]
The Waste Not mod crashes the game after the October 2023 update.

[Player.log](https://github.com/peterhaneve/ONIMods/files/13261009/Player.log)

**Comment by peterhaneve** [comment]
It looks like Steam has downloaded an outdated version of this mod. Mod Manager is not always sufficient to update mods, the only consistent fix is [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).

Note that a recent bug in the base game frequently lies about the installed version. Mods may need to be force updating even if the game is claiming that they are up to date.
