### ISSUE TITLE
Fast Track causes the game to freeze

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#416]
Spaced Out! DLC installed.
Latest steam version of the game.

With included mods Fast Track when smelting large amounts of metal the game starts to freeze, it is worth canceling the order as everything comes to normal, while freezes can and when the duplicate is not near the Metal Refinery. After restarting the game smelted 99 metal ore frieze is not, but it is worth to run another 99 as friezes begin to gradually appear and become stronger and stronger. The game one second works one second freezes and so until you put on pause or cancel the order of smelting. With other machines happens the same thing, but the freeze is not so strong and almost not noticeable. 
I tried playing without Fast Track and there was no problem with the game freezing. Mod settings are set to default, maybe I should disable some option to stop these freezes, but I have no idea which option can cause this problem?

Fast track latest version.

[Player.log](https://github.com/peterhaneve/ONIMods/files/13264354/Player.log)

**Comment by peterhaneve** [comment]
Your log is being spammed with `[WARNING] ViewMode 0x5B313A82 has no StatusItemOverlay value` which suggests a compatibility issue with one of your many other mods.

While this issue has been reported before, it has so far been impossible to reproduce, as it has been difficult to determine which mod (possibly multiple) is conflicting. Possible candidates include Customize Buildings, Daily Routine and AI Controlled Rockets.

**Comment by DarkEviL88** [comment]
I used to play without Customize Buildings and there were freezes, but I already had AI Controlled Rockets, is there any way to find out because of what mods spam? Only disable mods and look at the log? I don't have the Daily Routine installed. I will disable AI Controlled Rockets and see what happens.

**Comment by DarkEviL88** [comment]
What is interesting, now frequent freezes only when the duplicant at the machine and the machine drains coolant, maybe the Smelter mod affects this, as it has a setting for reusing coolant and throwing coolant into the atmosphere when overheating. When running on the same coolant, freeze occurs, but rarely.

**Comment by DarkEviL88** [comment]
Turned off the option to reuse coolant, now there is no freeze when draining coolant, but a small rare freeze still remains when using Metal Refinery.

**Comment by DarkEviL88** [comment]
And my log file is still spammed with the message: [WARNING] ViewMode 0x5B313A82 has no StatusItemOverlay value

**Comment by DarkEviL88** [comment]
The only thing left is to disable mod after mod and smelt a ton of ore to find the conflicting mod, I don't see any other way.

**Comment by peterhaneve** [comment]
Random short freezes are due to memory pressure - if some code frequently allocates memory, the game will constantly pause to reclaim the memory due to Unity's ancient 20 year old garbage collector algorithm. Fast Track significantly reduces memory allocations in the base game, but code from another mod might interact poorly with these optimizations and make the problem worse.

Instead of mass disabling mods, one idea would be to re-enable all mods again, then disable every setting in the Fast Track options and enabling them one by one until the freeze returns. It is infeasible to try and reproduce an issue with 100 mods enabled, but it might be possible to find the naughty mod if one particular option can be singled out.

**Comment by DarkEviL88** [comment]
I have 32GB of RAM, but for some reason when playing ONI the system swap file becomes huge, and if I play ONI long enough, such applications as Chrome and Discord crash, giving messages about lack of memory, while all RAM is not used.

**Comment by peterhaneve** [comment]
If this is the case, it looks like the base game, or some mod, is leaking memory. Frequent pauses would be caused by the garbage collector trying (and failing) to collect and free memory. Since Fast Track does not do this on all machines, there must be some other incompatible mod that leaks memory, either by itself or with Fast Track installed.

**Comment by DarkEviL88** [comment]
Apparently it is the game itself at a late stage so behave begins, because I started a new colony without mods with sandbox mode, opened 2 asteroids completely and the game began to rarely very short freeze, while I am not engaged in smelting metals. On a clean game the swap file is no longer increasing. Some mod makes the situation worse. I wouldn't call the late game 150 cycle a late game though. I think I need to check all mods that have not been updated for a very long time. There are mods from 2021-22 years have not been updated, although the game has already undergone many changes. I use an old mod that allows you to build drywall behind the tiles, as the author of the mod says that this mechanic was already in the game, but it was cut, perhaps the return of this mechanic returns and some bugs. Because of this mod, texture seams appear on the background without drywall, but yesterday I had the same problem on a clean game. I may have expressed it wrong somehow, because I don't know all the terms in the game industry. Thanks for answering me and giving me hints and ideas.

**Comment by DarkEviL88** [comment]
NullReferenceException: Object reference not set to an instance of an object

ObjectLayerListItem.Refresh (System.Int32 new_cell) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
ObjectLayerListItem.Update (System.Int32 cell) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
Pickupable.OnCellChange () (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
PeterHan.FastTrack.GamePatches.FastCellChangeMonitor+EventEntry.CallCellChangedHandlers () (at <f7b10c126701469288f805e42bf76df5>:0)
PeterHan.FastTrack.GamePatches.FastCellChangeMonitor.Update () (at <f7b10c126701469288f805e42bf76df5>:0)
PeterHan.FastTrack.GamePatches.CellChangeMonitor_RenderEveryTick_Patch.Prefix () (at <f7b10c126701469288f805e42bf76df5>:0)
(wrapper dynamic-method) CellChangeMonitor.CellChangeMonitor.RenderEveryTick_Patch1(CellChangeMonitor)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U49-577063-S

Maybe it's not the fast track, but the second mod. I enabled the second mod to move the geysers to convenient locations.
![image](https://github.com/peterhaneve/ONIMods/assets/50534207/52404515-e167-4c0d-8170-7d3ab06acf32)

[Player.log](https://github.com/peterhaneve/ONIMods/files/13320937/Player.log)
