### ISSUE TITLE
Shinebug reactor tweaks for FastTrack

### ISSUE THREAD

**Issue by jrmoserbaltimore** [peterhaneve/ONIMods#418]
Potential ideas for shinebug-reactor-specific tweaks, particularly detecting reactors and doing all computations in one step.

## Expected Behavior
Shinebug reactors don't strain the engine.

## Current Behavior
Shinebug reactor causes megalag.  FastTrack helps if you disable lighting effect stacking.

## Mod Versions
Latest version, since game always crashes if you use old fasttrack after an update.

## Steps to Reproduce

1. Breed shinebugs.
2. Build conveyor system.
3. Stuff them all in a single tile.
4. MASSIVE SUN.
5. MASSIVE LAG.

## Suggested approach

When detecting a shinebug variant, check if they can move in any direction.  If not:

1. Check that tile for all shinebugs in the tile, and ID them.
2. Put them into a group (internal to the simulation, not saved).  If a group exists at that tile, add the shinebugs to the group.
3. Attach that group to the 4 cardinal tiles around them, particularly that if any of those change (water mopped up, tile unbuilt, altered, etc.), recheck for mobility, and if the change has granted mobility then disband the group.
4. Count the number of shinebugs.
5. Calculate decor, lighting, radiation, lighting effects, etc. for *one shinebug*, amplified by the total count of shinebugs.
6. Skip doing any pathing or anything for any grouped shinebugs.

This means, for example, that when a shinebug is detected and a group of shinebugs exists at that tile position, that shinebug is added to the group.  (Does it actually make sense to check that tile for all non-grouped shinebugs, or just catch them lazily?)  Its pathing and AI are disabled.

When a duplicant rebuilds a block, demolishes a block, etc., or when a glob of liquid spills into the next tile (or into the tile with the shinebugs, which will free them to get out of the liquid), this triggers a check to see if the group is mobile; if so, the shinebugs start behaving normally again.  Enjoy the lag.

The shinebugs become one entity producing rads, lighting, effects, and so forth.  These aren't repeatedly calculated and stacked.  Things like aging and calories *are* computed per bug.

An option to adjust the maximum lighting effect intensity of a shinebug reactor would also be nice, so you can have a sun, but not a giant one, unless you want it.

I'm hoping this will make shinebug reactors computationally cheap, but I really don't know how the innards work.  This treats a 1x1 tile entrapping shinebugs differently than anything else in the game, so it's extremely specialized to a single use case.  Having 5 shinebug reactors roughly equal 5 shinebugs for computational intensity purposes would be nice though.

**Comment by peterhaneve** [comment]
This suggestion would involve one of two approaches:

- Completely rewriting multiple subsystems of the game, including decor, path finding, radiation and creature brains, to skip shinebugs in these conditions. Such a massive change would frequently break across updates and be incompatible with many other mods.
- Destroying all the shine bug entities and creating a combined entity in their place. This change would cause all the shine bugs to disappear if Fast Track is uninstalled. It would also involve dozens of difficult conditions to check with hundreds of edge cases.

Note that the path cache and unstacking lights already speeds up shine bug reactors by over *5 times* compared to vanilla. If your shinebug reactor strains the game even with Fast Track installed, consider rethinking your build to use systems that are better optimized for such a scale such as the Research Reactor.

One potential alternative may be [Shinebug Reactor](https://steamcommunity.com/sharedfiles/filedetails/?id=2699868121) if it still works. [Decor Reimagined](https://steamcommunity.com/sharedfiles/filedetails/?id=1892161928) also has an option to disable the decor score of critters, which can be a noticeable impact to their performance.

**Comment by jrmoserbaltimore** [comment]
Fair enough, I don't know the innards of the game but this sounds much more difficult than I'd considered.
