### ISSUE TITLE
Waste Not Feature Request: Prefer spoilables to non spoilables of same quality

### ISSUE THREAD

**Issue by Guinaro** [peterhaneve/ONIMods#419]
Would it be possible that Dupes first eat spoilable food before touching non spoilables of the same quality?

## Expected Behavior
If there is e.g. Meal Lice to be eaten, duplicants will eat that before touching a Nutrient Bar or Hexalent Food.

This is another way to avoid waste spoilables, as the unspoilables can and should be saved as a last resort.

**Comment by peterhaneve** [comment]
Unfortunately, adding this change will impose a significant performance penalty. The base game assigns food a freshness score, _always giving non-spoilables zero_, and then sorts food (after distance and quality) using freshness from highest to lowest. Waste Not, Want Not reverses the behavior, sorting food by least fresh, but that has the unfortunate side effect of forcing non-spoilable food to the top.

Adding another check to see if the food is spoilable will cause a very noticeable penalty to frame rate, as the condition is checked *thousands of times per frame* in large colonies.

**Comment by Guinaro** [comment]
I found it myself how to easily do it. And I do not think it will have a major impact on the game either.
I patched FetchManager.FetchablesByPrefabId AddPickupable
With the following code:
```
Edible component = pickupable.GetComponent<Edible>();
if ((Object)component != (Object)null)
{
    Rottable.Instance smi = pickupable.GetSMI<Rottable.Instance>();
    if (smi.IsNullOrStopped())
    {
        FetchManager.Fetchable newData = new FetchManager.Fetchable()
        {
            pickupable = __instance.fetchables.GetData(__result).pickupable,
            foodQuality = __instance.fetchables.GetData(__result).foodQuality,
            freshness = int.MaxValue,
            masterPriority = __instance.fetchables.GetData(__result).masterPriority,
            tagBitsHash = __instance.fetchables.GetData(__result).tagBitsHash
        };
        __instance.fetchables.SetData(__result, newData);
    }
}
```

All I do is set the Freshness to the Max Level an int can have.
Since your code inverses the picking to prefer less fresh items, unspoilables get picked last now.
Problem solved.
Need to test this in a full running game yet, but it certainly works.

**Comment by peterhaneve** [comment]
This patch as written is incompatible with Fast Track and Efficient Supply, but a slightly different version should work!
