### ISSUE TITLE
Clean Drop Crash

### ISSUE THREAD

**Issue by antonioltg91** [peterhaneve/ONIMods#42]
When i start a game with this mod on as soon the save is loaded the game crash

## Expected Behavior
- Not to crash

## Current Behavior
- Keep crashing

## Mod Versions
Linux
Steam version 1.1.0.0

## Steps to Reproduce
Load the mods
Restart the game
Load the save
Crash

## Output Log
https://pastebin.com/xgVBx3Wn

**Comment by peterhaneve** [comment]
While I do not have a Linux machine to reproduce the issue (it is Linux only), I found the most likely cause and it should now be fixed.
