### ISSUE TITLE
[Feature Request : Decor Reimagined] Walls block wires/pipes decor

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [peterhaneve/ONIMods#420]
There is a good mod that implements this feature from shelena_malk, but due to the decor system changes in your mod, this is incompatible.  An option to have walls block the negative decor from wires and pipes would be a nice feature.

**Comment by peterhaneve** [comment]
Compatibility by name has now been added with this mod. Decor Reimagined since 4.12 now has a new system for tracking drywall that will activate automatically if Block Decor Effects Behind Walls is enabled.

**Comment by TheGoodIdeaFairy** [comment]
Oh, fantastic!  Awesome work on the mod[s].
