### ISSUE TITLE
NoSensorLimits lacks support for the Light Sensor

### ISSUE THREAD

**Issue by flaming-couches** [peterhaneve/ONIMods#422]
Was trying to build a setup for an automated Shine Bug reactor control system using light sensors and tried your NoSensorLimits mod to see if it would help me increase the cap on its ability to detect Lux. However, it seems the mod hasn't been updated in a while and doesn't feature updates for that sensor.

## Expected Behavior
Using Spaced Out DLC. When configuring a Light Sensor with the NoSensorLimits mod installed, I would expect to be able to increase the sensor threshold beyond the game's default cap of 15,000 lux, by typing a larger number manually into the box.

## Current Behavior
The 15,000 lux cap on the building's configuration remains in place.

## Mod Versions
Using a fresh install of the Steam Version downloaded today. Mod Updater is installed, and the mod does not appear to have any available updates. Steam says the latest workshop version is 2.2.0.0.

## Steps to Reproduce
1. Install NoSensorLimits
2. Open a sandbox world
3. Place a Light Sensor
4. Try to type in a number greater than 15000
5. Watch the game reset the number to 15000

## Output Log
I don't believe Output log is necessary for this issue.

**Comment by peterhaneve** [comment]
As of 2.3.0.0 the Light Sensor, if available, will be supported. Note that support will not extend to the modded Light Sensor, only the base game version.
