### ISSUE TITLE
 When FastTrack mod is enabled, game crushes when press on the material information tab[F4]

### ISSUE THREAD

**Issue by NiaSai** [peterhaneve/ONIMods#423]
## Expected Behavior

Optimizes the performance of Oxygen Not Included and increase the frame rate (currently playing the vanilla version) 
## Current Behavior

Whenever I enable the FastTrack Mod, the game crushes in a few minutes or crushes instantly when I press on the material information tab(F4), I have the [Buildable Dirt Tile](https://steamcommunity.com/sharedfiles/filedetails/?id=1837883076) and [Bigger Camera Zoom Out](https://steamcommunity.com/sharedfiles/filedetails/?id=1717463209) enabled other than FastTrack, not sure if they are conflicting. Wasn't crushing at earlier stage of game, started to crush occasionally around 600 cycles and now crushing really fast at 646 cycles. 
## Mod Versions

Was using the older version, games crushes and downloaded the newer version 0.12.4 update uploaded on Nov 10th, still crushes. 
## Steps to Reproduce

1. Launch Oxygen Not Included
2. Enable the Fast Tract Mod
3. Start playing the game
4. Press the material information tab[F4]

## Output Log

Sorry I don't know the output log for this one but this is the information on the screen after game crushes, not sure wether that would hep

NullReferenceException

KBatchedAnimController.SetLayer (System.Int32 layer) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
KAnimControllerBase.SetLayer (System.Int32 layer) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
KBatchedAnimController.SetLayer (System.Int32 layer) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
OverlayModes+Mode.AddTargetIfVisible[T] (T instance, Vector2I vis_min, Vector2I vis_max, System.Collections.Generic.ICollection`1[T] targets, System.Int32 layer, System.Action`1[T] on_added, System.Func`2[T,TResult] should_add) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
OverlayModes+TileMode.TryAddObject (PrimaryElement pe, Vector2I min, Vector2I max) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
OverlayModes+TileMode.Update () (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
OverlayScreen.LateUpdate () (at <d1b7643456214f4e8c00f70e3a2b4469>:0)

Build: U49-577063-V

**Comment by peterhaneve** [comment]
There is no Fast Track code in this crash, and it will be impossible to debug without a full output log. However, this crash strongly suggests a base game bug.
