### ISSUE TITLE
[FastTrack] Auto-sweeper cannot supply from storage tiles

### ISSUE THREAD

**Issue by oxalica** [peterhaneve/ONIMods#425]
## Expected Behavior

Auto-sweeper should be able to move from storage tiles to machines that require it, as in vanilla game.

## Current Behavior

It does nothing.

## Mod Versions

ONI U50-581979-S, Spaced Out! DLC enabled, with local installed FastTrack 0.12.5.0 enabled, default mod options, no other mods enabled.

## Steps to Reproduce

1. Build some kilns, a storage tile and a auto-sweeper. Make sure that kilns and storage tiles are in the range of the auto-sweeper.
2. Spawn a duplicant to fill the storage tile with enough coal, then delete the duplicant.
3. Queue a coal->refined carbon task in the kiln.
4. Nothing happens, and the kiln reports "Waiting for materials".

![image](https://github.com/peterhaneve/ONIMods/assets/14816024/97a38f75-3c4a-437d-91d2-05c1d82645f8)

![image](https://github.com/peterhaneve/ONIMods/assets/14816024/8feabab0-d0f2-4347-861c-1242b954b72d)

## Output Log

No relevant output in log.

**Comment by peterhaneve** [comment]
I built your build exactly to the tile and could only reproduce the issue initially.
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/1d10c4a2-7b19-4275-b55a-8deda9c2ea4f)
However, I figured it out - it only occurs if there are _no living Duplicants (at all)_. Although this will never happen in a real survival game, I have added a special case in sandbox only to minimize performance degradation in actual playthroughs.

**Comment by oxalica** [comment]
> However, I figured it out - it only occurs if there are _no living Duplicants (at all)_. Although this will never happen in a real survival game, I have added a special case in sandbox only to minimize performance degradation in actual playthroughs.

I did run into this issue in my survival base, through the setup is slightly different. It seems that auto-sweeper can use it from top (can either move into or from) but not from bottom. In the screenshot below, the top kiln can be delivered while the bottom ones cannot. I double checked that the coal inside is enough (>125kg), and all dupes are locked out from this area.

![image](https://github.com/peterhaneve/ONIMods/assets/14816024/fc06bbeb-cae6-4de4-b742-e49a1d3281c7)

![image](https://github.com/peterhaneve/ONIMods/assets/14816024/184aab94-9c2d-424e-8db1-266752c247de)

**Comment by peterhaneve** [comment]
Even in the exact same positions, the second issue also does not reproduce (with or without any Duplicants living)
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/e80a03ea-e4b4-44ce-8a7a-35b6f2822968)
