### ISSUE TITLE
Mods not working with latest build

### ISSUE THREAD

**Issue by yosraz80** [peterhaneve/ONIMods#426]
![Uploading Uten navn.png…]()
These mods are not working:

- Better info cards
- Skills and stats progress
- Food supply tooltip
- Always show capacity

MissingMethodException: UnityEngine.GameObject SimpleInfoScreen.get_StoragePanel()

(wrapper dynamic-method) SimpleInfoScreen.SimpleInfoScreen.RefreshStorage_Patch1(SimpleInfoScreen)
(wrapper dynamic-method) SimpleInfoScreen.SimpleInfoScreen.OnSelectTarget_Patch1(SimpleInfoScreen,UnityEngine.GameObject)
TargetScreen.SetTarget (UnityEngine.GameObject target) (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
DetailsScreen.OnTabActivated (System.Int32 newTab, System.Int32 oldTab) (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
KTabMenu.ActivateTab (System.Int32 tabIdx) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
(wrapper dynamic-method) DetailsScreen.DetailsScreen.Refresh_Patch1(DetailsScreen,UnityEngine.GameObject)
RootMenu.Refresh () (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
RootMenu.OnSelectObject (System.Object data) (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
(wrapper dynamic-method) SelectTool.SelectTool.Select_Patch1(SelectTool,KSelectable,bool)
SelectTool.OnLeftClickDown (UnityEngine.Vector3 cursor_pos) (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <76ef63103ae5408a8dbffd2c8c54e743>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KInputController.Dispatch () (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KInputManager.Dispatch () (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
KInputManager.Update () (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
GameInputManager.Update () (at <b24a2fcffac74a77ad1a0ba877a47699>:0)
Global.Update () (at <76ef63103ae5408a8dbffd2c8c54e743>:0)

Build: U50-581979-V

**Comment by peterhaneve** [comment]
The image failed to upload, but Always Show Capacity, Skills and Stats Progress and Better Info Cards are not part of this repository. Please report this issue to the authors of those mods. Food Supply Tooltip is not part of that stack trace, but will be blamed because it uses a method farther down.
