### ISSUE TITLE
[FastTrack]: Burrowed Hatches are Confined+Miserable

### ISSUE THREAD

**Issue by meekay** [peterhaneve/ONIMods#427]
Starting with U50 (Packed Snacks), hatches that are burrowed are showing as Confined + Miserable. I verified this goes away with Fast Tracks disabled. Not sure whether or not this actually results in a depressed reproduction rate. 

## Mod Versions
Fast Tracks 12.5.0, local

## Steps to Reproduce
I've got a hatch centered in the attached save file.

[Unfortunate Canning.sav.zip](https://github.com/peterhaneve/ONIMods/files/13420671/Unfortunate.Canning.sav.zip)

![image](https://github.com/peterhaneve/ONIMods/assets/590046/e215ccb2-4abc-4770-9e2e-0464b9b9ef47)

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/13420682/Player.log)

**Comment by peterhaneve** [comment]
This issue appears to have been introduced with the latest patch. Version 0.12.6.0 will fix the behavior.
