### ISSUE TITLE
No Sensor Limits not working for Motion Sensors

### ISSUE THREAD

**Issue by S-zombie** [peterhaneve/ONIMods#428]
No Sensor Limits does not seem to do anything for the Duplicant Motion Sensor, despite being one of the sensor listed in the mod description on Steam. Other sensors do work as expected.

## Expected Behavior
Expand Sensor's threshold
I do have Spaced Out!

## Current Behavior
Nothing seems to change for the Motion Sensor

## Mod Versions
Steam version 2.3.0.0. Mod Updater says everything is up-to-date.

## Steps to Reproduce
Start a new game with sandbox, place a Motion Sensor, nothing is changed. The only active mods, other than MSL, are Mod Manager and Mod Updater.

## Output Log
It says nothing useful, as far as I can see, but I'll add one regardless.
[Player.log](https://github.com/peterhaneve/ONIMods/files/13451765/Player.log)

It can be that I don't understand what the mod is supposed to do with the Motion Sensor, it is listed in the mod description on Steam, but is not quite clear, but, at least in my game, does not seem to do nothing at all.
![Oxygen Not Included 23_11_2023 16_50_15](https://github.com/peterhaneve/ONIMods/assets/59321010/66746c8c-6b80-40aa-afe0-9e25c0a49d72)

**Comment by smaurine82** [comment]
I am having the same issue.

**Comment by peterhaneve** [comment]
No Sensor Limits originally did do something to the Motion Sensor, but after a Klei change during the sensor's development, the functionality no longer works and there is no useful way to re-enable it. Thanks for the catch, I will remove the sensor from the Steam description.
