### ISSUE TITLE
Mismatched Wire Finder Translation

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#429]
I would like to ask you to add the possibility to localize this very useful mini mod.

Here are the translated strings:
public static LocString FIND_PIPE = "Найти соединённые " + STRINGS.UI.FormatAsLink("трубы", "LIQUIDPIPING") + " из другого материала";
public static LocString FIND_WIRE = "Найти соединённые " + STRINGS.UI.FormatAsLink("провода", "WIRE") + " с другой максимальной " + STRINGS.UI.FormatAsLink("мощностью", "POWER");

public static LocString FIND_PIPE = "Найти несоответствия";
public static LocString FIND_WIRE = "Найти несоответствия";

**Comment by peterhaneve** [comment]
Is this localization for the `ru` locale?

**Comment by DarkEviL88** [comment]
Yes
