### ISSUE TITLE
Feature Request: Fast Track:  Power Overlay  -->Need for optimization

### ISSUE THREAD

**Issue by youwi** [peterhaneve/ONIMods#433]
## Expected Behavior
< Power Overlay>Need for optimization 
## Current Behavior
my game FPS too low at  Power Overlay.    when  too many building .
 i found that  : OverlayModes.Power.Update()   too  slow.   
too many useless call() , 

so , i think FaskTrack should do something for that.
## Example Code:
     [HarmonyPatch(typeof(OverlayModes.Power), "Update")]
     public class OverlayModes_Power_Update_Patch
     {
         static float tickSecond = 0;
         public static bool Prefix()
         {
             if (Time.realtimeSinceStartup - tickSecond > 2) //  2 second update
             {
                 tickSecond = Time.realtimeSinceStartup;
                 return true;
             }
             return false;
         }
     }

**Comment by peterhaneve** [comment]
This overlay should really be optimized in a different way.
