### ISSUE TITLE
Plib may made Game Translate fail.

### ISSUE THREAD

**Issue by youwi** [peterhaneve/ONIMods#434]
Plib may made Game Translate fail.    (zh_cn Chinese )
at

- Db.Get().traits
- CustomGameSettingConfigs.cs
- RoomConstraints.cs
GameSetting UI 游戏设置 界面
![image](https://github.com/peterhaneve/ONIMods/assets/5918054/faef6074-fff7-4dc2-9c22-1c40ec4a1880)

I'm not quite sure if the problem is caused by Plib

i   use only one Mod (with plib) ,then my translate fail.

**Comment by peterhaneve** [comment]
Which mod are you using? Due to bugs in the base game, referencing specific classes at all in a mod too early will break translations, and Klei created several more of these broken classes in the recent updates.
