### ISSUE TITLE
How to fix queue for sinks :3

### ISSUE THREAD

**Issue by bumbeen** [peterhaneve/ONIMods#435]
Dupe will pause at the sink for half a second while the first dupe finishes then they both continue without the second dupe washing hands.

## Expected Behavior
Yes i have spaced out, but I observed the behavior on a standard map. 

## Current Behavior
They just pause at the sink and think while the first dupe is washing hands, when the bar completes they both continue.

## Mod Versions
steam copy, i uninstalled and reinstalled the workshop mod

## Steps to Reproduce
1. install queue for sinks
2. start game
3. game restarts
4. activate mod
5. game restarts
6. load map
7. build two toilets and one sink
8. have two dupes use toilet
9. when they leave toilet one dupe will wash hands while other dupe pauses
10. when first dupe finishes washing hands both dupes continue past the sink

## Output Log
idk how to do this sorry :)

**Comment by peterhaneve** [comment]
Without the output log it is impossible to say for sure, but it looks like you have a version from over six months ago. Due to bugs recently introduced in the base game, you really do need to use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
