### ISSUE TITLE
More of a question about Waste not, Want not. 

### ISSUE THREAD

**Issue by Etrit1** [peterhaneve/ONIMods#436]
So, the mod page on Steam says that food chunks less then 10 grams will just vanish and not turn into rot piles.

I just want to make sure that all of the food I've over produced (or am not using right now due to food changes) that is stored in fridges and deep freeze ration boxes will STILL produce rot piles.  

I'm guessing so but thought I'd ask.

Thanks! :-)

**Comment by peterhaneve** [comment]
The rule only applies to tiny chunks of under ten grams, which are commonly created due to rounding errors in the game. It also only applies when the food would rot normally, so food in deep freeze under ten grams will be unaffected.
