### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by BreakshadowCN** [peterhaneve/ONIMods#438]
## Expected Behavior
Game would run normally.
I'm running latest U50 ONI public branch installed with no DLC.

## Current Behavior
Game would crash after 1 ingame days or 2 days regardless of what I would do. I reproduced it with my mods on(Free Resource Building, Debug Buttons), Fast Track on / my mods on, Fast Track+Fast Save on / my mods on, Fast Save on, and "Debug Buttons" disabled with no Fast Track nor Fast Save.
Launch any rocket will make this progress faster.

## Mod Versions
For every mods other than Fast Path I use Steam subscription system and these are all latest version.

## Steps to Reproduce
1. Just Play
2. Maybe launch a rocket
3.
4.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/14080349/Player.log)

**Comment by BreakshadowCN** [comment]
Save file in case dev need it: 
[My second home Cycle 917.zip](https://github.com/peterhaneve/ONIMods/files/14080553/My.second.home.Cycle.917.zip)

**Comment by peterhaneve** [comment]
> with no Fast Track nor Fast Save

If this crash occurs without Fast Track or Fast Save active, file a bug on the [Klei Bug Tracker](https://forums.kleientertainment.com/klei-bug-tracker/oni/).
