### ISSUE TITLE
....RANDOM CRASH AFTER GAME BEING PAUSED FOR TOO LONG

### ISSUE THREAD

**Issue by robotnikkkk** [peterhaneve/ONIMods#439]
......HAPPENS EVERY TIME ON WHATEVER VERSION........ANNOYED ME AF ALREADY.........

.....WHAT EXACTLY HAPPENS........LIKE I'D LIKE TO BUILD STUFF AND THINKING THROUGHLY.....SO OFTEN IT'S FOR AN HOUR OR SO........OR MORE THAN THAT

......AND LIKE.....AFTER A BIT OF TIME MORE THAN HOUR OF PAUSING, THE GAME STARTS TO FREEZE.....AND ALL GASES AND LIQUIDS TURNING BLACK , COLORS INVERTING AND STUFF........SO GAME JUST DOESNT GO LIKE ANYWHERE

......SOMETIMES IT CRASHES IF INITIAL FREEZING HAPPENED........ SO THE GAME WRITES "OOPS THE GAME CRASHED" AND UNCHECKS THE MOD......

.........BY THE WAY, STILL, A HUGE THANKS FOR MOD BC IT'S HELPING ME TO MOVE SOMEWHERE BC OTHERWISE ITCS UNPLAYABLE DUE TO SHINE BUG REACTOR ON 90,000 RADS/CYCLE AT CENTER........

... _*HOW TO RECREATE??*_ == *JUST PAUSING GAME FOR SEVERAL HOURS* , MUST HAPPEN EVENTUALLY

........IF THE ISSUE DOESNT BEEN RE CREATED, THEN OK IT'S FAULT OF SHINE BUG REACTOR......... BUT *STILL* CAN U EXPLAIN WHY IT DOESNT HAPPEN AT ONCE, THO?........ AND IT *DOES* NEED SOME TIME OF GAME BEEN PAUSED..........WHAT HAPPENS AND HOW AFK TIME AFFECTING THE FREEZE TO TAKE PLACE?....LIKE THERE'S SOME CALCULATIONS STILL HAPPEN WHEN GAME IS PAUSED?OR IT'S ABOUT SOMETHING ABOUT HOW MOD DOES WORK NORMALLY SO IT IS *UNAVOIDABLE* ??

........OKKKKK , WROTE........ BY THE WAY IT HAPPENS ON ALL VERSIONS, AND WHEN SHINE BUG REACTOR WAS AROUND 30,000 RADS/CYCLE AT CORE IT ALREADY WAS HAPPENING

**Comment by BreakshadowCN** [comment]
It will be much helpful if you attach your save file and mods list here. A log is even better, like the player.log from "%USERPROFILE%\Documents\Klei\OxygenNotIncluded\mods\Local" (it's under your "Documents" folder).

**Comment by robotnikkkk** [comment]
.............OKKKK FIGURED HOW TO COPY

NullReferenceException

KMonoBehaviour.get_transform () (at <1e2b7d5db95c4d6b84eabb7ca0270927>:0)
PeterHan.FastTrack.PathPatches.DeferredTriggers.Process () (at <2d5e6b86a54b4a71b24651aa0e1212f4>:0)
PeterHan.FastTrack.World_LateUpdate_Patch.Postfix () (at <2d5e6b86a54b4a71b24651aa0e1212f4>:0)
(wrapper dynamic-method) World.World.LateUpdate_Patch2(World)

...........................

**Comment by peterhaneve** [comment]
If the game starts to freeze and liquids/gases turn black, a memory leak is causing the game to run out of memory. The base game already leaks memory fairly quickly, but some other mods can also contribute. Fast Track reduces the rate that memory is allocated, but the higher frame rate usually causes other leaks to add up more quickly as the game is doing more calculations per second.

Either increase the amount of virtual memory available to the game (increase page file size on Windows, or tune overcommit settings in Linux), or add more physical memory to the device.

**Comment by 1265578519** [comment]
fast Track 这个实测有一丢丢用，可以提高5帧左右，但是要低于30帧的时候才会启用
