### ISSUE TITLE
Using this mod crashes the game on the current beta branch (404823).

### ISSUE THREAD

**Issue by faltonico** [peterhaneve/ONIMods#44]
## Expected Behavior
Play normally.

## Current Behavior
Game crashes.

## Mod Versions
Latest steam release (using mod updater).

## Steps to Reproduce
Open a save with the mod enabled, in the current beta branch of the game. Play for a couple minutes. Game eventually crashes.

## Output Log
PeterHan.SweepByType.FilteredClearTool.OnDragTool (System.Int32 cell, System.Int32 distFromOrigin) (at <2b33cdf273b44a4480e9c7258a8319c8>:0)
DragTool.OnLeftClickUp (UnityEngine.Vector3 cursor_pos) (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/scripts/game/InterfaceTools/DragTool.cs:206)
PlayerController.OnKeyUp (KButtonEvent e) (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/scripts/game/PlayerController.cs:309)
KInputHandler.HandleKeyUp (KButtonEvent e) (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:164)
KInputHandler.HandleKeyUp (KButtonEvent e) (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:174)
KInputHandler.HandleEvent (KInputEvent e) (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputHandler.cs:131)
KInputController.Dispatch () (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputController.cs:309)
KInputManager.Dispatch () (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputManager.cs:63)
KInputManager.Update () (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/KInputManager.cs:52)
GameInputManager.Update () (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/input/GameInputManager.cs:62)
Global.Update () (at D:/JenkinsWorkspace/Preview_Simgame_Windows/game/Assets/scripts/game/Global.cs:648)

ps: many of the mods i was using before didn't need to be updated to play the current beta branch.

**Comment by peterhaneve** [comment]
Most mods in this repository are not yet supported on the beta branch. The code in this branch is subject to change, and is very likely to break again before the code goes live.

Thank you for pointing the issue out for future reference, although it would be preferable to include the entire log (use attachment or pastebin if necessary) in the future.
