### ISSUE TITLE
Rest for the Weary+Smart Pumps - Translation

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#441]
Rest for the Weary - Russian translation
[ru.zip](https://github.com/peterhaneve/ONIMods/files/14273126/ru.zip)

**Comment by DarkEviL88** [comment]
Smart Pumps - Russian translation
[ru.zip](https://github.com/peterhaneve/ONIMods/files/14273231/ru.zip)

**Comment by peterhaneve** [comment]
Thank you for contributing translations! They will be added to the mods closer to the upcoming Quality of Life update.

**Comment by DarkEviL88** [comment]
Thank you, for your beautiful mods. In the Smart Pumps mod, the vacuum pump makes the sound of a gas pump, not a gas mini pump.
