### ISSUE TITLE
Fast Track and Translate Fix 翻译修正

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#446]
I have Fast Track first in the order of loading mods, and after it comes <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3105273056">Translate Fix 翻译修正</a> mod, and some functions of Fast Track stop working. For example: I turned off in-game tutorials with Fast Track, but they still appear after I enabled the Translate Fix 翻译修正 mod.

The author of the mod Translate Fix 翻译修正 says that localizations in the game are broken because the mods are loaded ahead of the game, and with the help of this mod the game is loaded first, and then all the other mods. That's probably why not all Fast Track features work correctly. Is there any way to solve this problem?

**Comment by peterhaneve** [comment]
This mod force calls `Localization.Initialize` and a few other functions before they would normally be executed. However, Fast Track and many other PLib mods use the call for this method to perform specific tasks. If this mod is loaded before Fast Track, the method will be called before Fast Track can be loaded, and Fast Track cannot go back in time to undo what has already been done.

While this mod does work around bugs in several other mods that refer to static fields (either directly or unintentionally through transitive loading) which break localization, it will never be compatible with Fast Track.
