### ISSUE TITLE
Decor reimagened crash

### ISSUE THREAD

**Issue by litelesslive** [peterhaneve/ONIMods#449]
Random crash while ingame

## Mod Versions
Latest available. 

## Steps to Reproduce
Just happened while messing on new map.

## Output Log
IndexOutOfRangeException: Index was outside the bounds of the array.

GameUtil.GetDecorAtCell (System.Int32 cell) (at <1a8bba13569349b99ce84dc6ff18815b>:0)
ReimaginationTeam.DecorRework.DecorReimaginedPatches+DecorMonitor_Instance_Update_Patch.Prefix (DecorMonitor+Instance __instance, System.Single dt, Klei.AI.AmountInstance ___amount, Klei.AI.AttributeModifier ___modifier, System.Single& ___cycleTotalDecor) (at <cc032b43166c48b599d92865c2149b62>:0)
(wrapper dynamic-method) DecorMonitor+Instance.DecorMonitor+Instance.Update_Patch1(DecorMonitor/Instance,single)
DecorMonitor+<>c.<InitializeStates>b__1_2 (DecorMonitor+Instance smi, System.Single dt) (at <1a8bba13569349b99ce84dc6ff18815b>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <3ca21dc18eae422d87255277091f8593>:0)
Game.SimEveryTick (System.Single dt) (at <1a8bba13569349b99ce84dc6ff18815b>:0)
Game.Update () (at <1a8bba13569349b99ce84dc6ff18815b>:0)

Build: U51-596100-SD

[Player.log](https://github.com/peterhaneve/ONIMods/files/14453798/Player.log)

**Comment by peterhaneve** [comment]
The changes in today's patch to prevent Duplicants and Rovers from discovering the Water planetoid on load appears to potentially cause a crash. A guard has been added in version 4.14.
