### ISSUE TITLE
模组过时了，怎么还不更新啊

### ISSUE THREAD

**Issue by 1265578519** [peterhaneve/ONIMods#451]
模组过时了，怎么还不更新啊
![image](https://github.com/peterhaneve/ONIMods/assets/6442439/e7d9e1c1-a543-4f6c-9620-a51a3c95955c)

**Comment by 1265578519** [comment]
![image](https://github.com/peterhaneve/ONIMods/assets/6442439/9872ae20-e04f-4fb6-861a-c9fd46d54e0b)

缺氧更新u51后MOD不兼容提示模组过时的手动强制刷新版本解决办法
删除这两个文件夹，删除完成后，然后重开steam进游戏，会重新下载最新版的模组文件
C:\Program Files (x86)\Steam\steamapps\workshop
%userprofile%\Documents\Klei\OxygenNotIncluded\mods

谁帮忙试试，好的话我发教程出去

**Comment by peterhaneve** [comment]
The message showing indicates that Thermal Tooltips is outdated, and it is - the version on Steam is 3.4.0.0, but your version shown in the mod menu is 3.3.0.0. If verifying game files does not solve your issue, try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283). It looks like you found another solution too.
