### ISSUE TITLE
........NEWEST FASTTRACK MESSING WITH AUTO SWEEPERS!!!!!!!

### ISSUE THREAD

**Issue by robotnikkkk** [peterhaneve/ONIMods#452]
..........SIMPLY AS THAT..........AT **_CURRENT_** MOD'S VERSION,OKAY????????L...........

.............LIKE MY BASE IS JUST **_LITTERED_** WITH ETHANOL DISTILLERS ,THAT ARE WORKING AT ENCLOSED SPACE SO NO DUPES DO INTERFERE...............HOW MANY???????.........LET'S SAY THE TOTAL NUMBER OF **_FIFTEEN_** PETROL GENERATORS ARE WORKING SIMULTANEOUSLY,OKAY???????......................ABOUT HOW MUCH AUTO SWEEPERS DO WORK AT ONCE, HEHEHEHE

............SOOOO......I LEFT BASE AFK FOR SOME TIME AND DO YOU KNOW WHAT I SAW WHEN GOT BACK???????LIKE ALMOST ALL ETHANOL DISTILLERS STOPPED WORKING, LIKE THERE WERE AUTO SWEEPERS THAT JUST DIDNT REACT ON DISTILLERS' NEEDS........SOME WERE STILL WORKING, BUT THIS WAD AN EXCEPTION

.............. _**SOME WORKING SOME NOT**_ .......I'M TRYING TO SAY...............

=MAYBE THERE WERE SOME OTHER AUTO SWEEPERS,BUT BECAUSE DUPES WERE HAVING DIRECT ACCESS I DIDNT SEE, SO PROBLEMIS **NOT** EXACTLY ABOUT ETHANOL DISTILLERS,BUT HOW AUTO SWEEPERS SEE STUFF...........MOST LIKELY OPTIMIZATION WAS PERFORMED NOT IDEALLY, SO THE MOD DISABLED WRONG STUFF

................ **DID I TRY RELOAD THE GAME???** ---YESS, NO EFFECT

=SO..... I **DISABLED** MOD AND IT ACTUALLY _**WORKED**_ , THAT'S HOW I FIGURED WHAT'S WRONG AND WHERE THERE WAS AN ISSUE.........

...........SO......MAYBE YOU'LL CHECK OUT THE PART OF CODE ABOUT AUTO SWEEPERS, ARE YOU???

=AND YES, THE PROBLEM IN PREVIOUS PATCH WAS NON EXISTENT, BUT AT **THIS** TIME THE VERY STRUCTURE OF HOW GAME DOES CALCULATIONS WAS REWRITTEN, ISNT THAT

..............ABOUT WHAT FILES OR LOG FILES TO GIVE I DONT KNOW........JUST TRY SPAMMING AUTO SWEEPERS IN SANDBOX AND U'LL GET THIS IF U WANT TO REPLICATE.................BUT THIS IS GAME BREAKING BUG, NO DOUBT,IMPOSSIBLE TO PLAY WITH THAT.....AND I DOUBT PROBLEM AT THIS TIME AT MY SIDE.........

**Comment by peterhaneve** [comment]
There is no actionable information here to actually fix the bug. I have test colonies that I always run with new Fast Track releases, and Auto-Sweepers work normally in them.

Please do not ignore the default template, it specifies how to attach any relevant logs.
