### ISSUE TITLE
Automation Expanded MOD CTD after last Klei update

### ISSUE THREAD

**Issue by alexander-cg** [peterhaneve/ONIMods#453]
Hi

I have a CTD with the "[automation expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2014558219&searchtext=automation+expanded)" mod enabled. Here are the details:

Mod version: 2.2.0.0
Mod Updater: Used, no effect.
Local download: Yes, still CTD
Mod Conflict: All other mods disabled, still CTD
Game version: Spaced Out! DLC
Game build: U51-596666-5D
Steam game file integrity check: Yes, performed steam game file integrity check, all files verified.
ONI Splash Screen Error Message AND player.log file at this [link](https://file.io/6gMm9kzIZUwP).

Note: 
I'm not sure if you are the  correct person to contact, however, this is the message at the mod page.

> Problems/Help
> If there are problems with the mod please reach out on the (un)official Oxygen Not Included Discord where we hang around on the modding channels as @test447, @peterhaneve, and @Hexicube.
> We probably won't pay full attention to steam comments.

I  tried the discord server, their mod page and Hexicube github but haven't gotten a response.

**Comment by peterhaneve** [comment]
This repository is not the right place to file issues with Automation Expanded. As Hexicube owns the mod on Steam, only they can update it no matter who else is listed as contributors.

**Comment by alexander-cg** [comment]
OK Thanks for the quick reply.
