### ISSUE TITLE
Non specfic (Workshop Profiles) - Selection overflows offscreen

### ISSUE THREAD

**Issue by ECHOSUD** [peterhaneve/ONIMods#460]
## Issue
When viewing a building that can be operated, multiple mods that add options will push each other vertically offscreen.

## Feature Request
Add a check to dynamilly limit the number of items listed of a scrollalble list, or some other compromise like manually moving or resizing the window.

<details><summary><h2>Example</h2></summary>
<img src="https://steamuserimages-a.akamaihd.net/ugc/2526029898159486420/D653E5BD8A6BA9735103B7EBF342DC0853D31151/">
Likely mods installed contributing to issue:<ul>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2433887112">Workshop Profiles</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2829258387">Attribute-based Workshop Restrictions</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3204497859">Better Rebuilding</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2047308624">No Manual Delivery</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2963257205">Delivery Temperature Limit</a></li>
<li><a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2863383492">Daily Routine</a></li></ul>
In this example, I am unable to select/view ~3 duplicants in the Workshop Profiles section.
</details>

<details><summary><h2>Technical details</h2></summary>
<ul><li>Vanilla (no Spaced Out! DLC installed)</li>
<li>Default branch (U51-600112-V, March 27th)</li>
<li>Steam subscription (2.5.0.0, 1708069255)</li>
<li>Mod Updater (2.15.0.0, 1709111606)</li>
<li><a href="https://github.com/peterhaneve/ONIMods/files/14814677/Player.log">Player.log</a></li></ul>

**Comment by peterhaneve** [comment]
This issue is a base game bug, as it can even occur without mods on a large enough UI scale or small enough screen. Adding a scroll bar to this screen would break other mods, as Unity scroll panes have issues with being nested.

If you want to see this fixed in a more portable way, consider filing a [bug report](https://forums.kleientertainment.com/klei-bug-tracker/) to Klei.
