### ISSUE TITLE
Item grab issues

### ISSUE THREAD

**Issue by Darkerowl** [peterhaneve/ONIMods#461]
## Expected Behavior: Not exactly sure, but I feel the Dupes should grab recources close to the build area not from the farthest source.
 grab materials close
 yes I have DLC, no beta tests

## Current Behavior
The Dupes will grab Material from far away sources even though there is that exact material very close by to my build area? The material I noticed them doing this was with seeds and Copper. I have a deep side shaft in my game and the Dupes keep climbing down it to the bottom and grabbing the Copper even though I have a 14T pile of Copper next to my buildings I want built. Now they don't get stuck in a loop if they drop the material from low O2 they will go to another source, but they do go to the farthest one more common then not.

## Mod Versions
 Steam SUB
Yes

## Steps to Reproduce

1.build a area 
2. make a 100 block deep shaft
3.put material at the bottom, put material next to build.
4.see what the dupes do more commonly do they climb down even though you have some near?

## Output Log

[Oxygen Not Included.zip](https://github.com/peterhaneve/ONIMods/files/14880474/Oxygen.Not.Included.zip)

**Comment by peterhaneve** [comment]
If this is a request for a new feature altogether (as the base game does not consider the distance to the build area, but the distance to where the Duplicant is currently standing when they acquire the chore), you may have better luck trying the [Klei Bug Tracker](https://forums.kleientertainment.com/klei-bug-tracker/oni/) or the [Mods and Tools forum](https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/)
