### ISSUE TITLE
Invalid temperature [NaN]

### ISSUE THREAD

**Issue by kuxynator** [peterhaneve/ONIMods#462]
## Expected Behavior
Does not crash the game.

## Current Behavior
crashes the game.

## Mod Versions
- 3.9.0
- using Steam subscription
- force update the mod using Mod Updater? yes 

## Steps to Reproduce
- build a termal interface plate, as usual

This is the first time I have seen this error. I can reproduce it in this game. It has worked in other games so far. 

## Output Log
![image](https://github.com/peterhaneve/ONIMods/assets/66268429/17279958-d672-4ab6-b74e-a6bd09b0636e)
[Player.log](https://github.com/peterhaneve/ONIMods/files/14945777/Player.log)

**Comment by peterhaneve** [comment]
This crash log is impossible in Thermal Interface Plate 3.9; it definitely is coming from 3.8 or earlier as `Sim200ms` no longer exists in the latest version. It looks like you may need to force update the mod again.
