### ISSUE TITLE
2 issues: Bad autosweepers, crash with FastReachability off

### ISSUE THREAD

**Issue by zivvel** [peterhaneve/ONIMods#464]
## Expected Behavior

Autosweepers should load igneous rock into bottom left sweeper, load pincha seeds into fish feeder and also some buildings in the top part of the pip ranch where the save is focused.

Playing with the SO! DLC

## Current Behavior

With only Mod Updater & Fast Track 0.13.4 enabled, the attached save game has some autosweepers that don't do their jobs.
I tried disabling FastReachability, and that results in this crash within seconds after the initial unpause.

## Mod Versions

Fast Track 0.13.4

## Steps to Reproduce

1. Attached are my save game and FT config.json
2. Load game
3. Unpause
4. Crash with below stack trace.

5. Re-enable FastReachability & restart
6. Load game
7. Unpause
8. Observe autosweepers avoid loading pincha seed into the fish feeder or igneous debris into the conveyor loader
![image](https://github.com/peterhaneve/ONIMods/assets/242258/f534e536-816d-434e-88e9-9f716343cc4e)
9. Tried same with Chore Optimizations disabled; autosweepers still avoided loading.
10. Disable Fast Track & restart, load game, unpause
11. Observe autosweepers do their jobs.

## Output Log
Stack trace:
```
IndexOutOfRangeException: Index was outside the bounds of the array.

MinionGroupProber.Occupy (System.Object prober, System.Int16 serial_no, System.Collections.Generic.IEnumerable`1[T] cells) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
SolidTransferArm.IncrementSerialNo () (at <3d436e4ec1d5455793674ec559b0cc77>:0)
PeterHan.FastTrack.GamePatches.SolidTransferArmUpdater.BatchUpdate (System.Collections.Generic.IList`1[T] entries) (at <24d1b8bb6099487dba2b15ea72092b2f>:0)
PeterHan.FastTrack.GamePatches.SolidTransferArm_BatchUpdate_Patch.Prefix (System.Collections.Generic.List`1[T] solid_transfer_arms, System.Single time_delta) (at <24d1b8bb6099487dba2b15ea72092b2f>:0)
(wrapper dynamic-method) SolidTransferArm.SolidTransferArm.BatchUpdate_Patch1(System.Collections.Generic.List`1<UpdateBucketWithUpdater`1/Entry<ISim1000ms>>,single)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <3ca21dc18eae422d87255277091f8593>:0)
Game.SimEveryTick (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U51-600112-S (FT-0.13.4.0)
```

[2024-04 Disco 756 weird 2.zip](https://github.com/peterhaneve/ONIMods/files/15133295/2024-04.Disco.756.weird.2.zip)
[config.json](https://github.com/peterhaneve/ONIMods/files/15133297/config.json)
[Player.log](https://github.com/peterhaneve/ONIMods/files/15133300/Player.log)

**Comment by zivvel** [comment]
I'm happy to provide any further help needed; just ping me on discord (same username there).

**Comment by peterhaneve** [comment]
It looks like you have some auto sweeper (not necessarily the pictured ones) very close to the edge of the map, which is seeing the objects that Klei moved into cell -1 in the latest patch to prevent scout rovers from falsely discovering new planetoids. This change required a ton of new valid cell checks in the base game, and it looks like Klei missed one in a method used by Fast Track, so a pre-test has been added.

After fixing this issue, the second issue does not reproduce with your exact save file. It may be that the issues were inter-related.
