### ISSUE TITLE
Fast Track crash

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#465]
Game version: U51-600112-S (Steam)
Fast Traсk version: 0.13.5.0

When duplicants communicate with Jorge this rare game crash happens, but after restarting, I haven't noticed this crash anymore. 
How it happens in my game:
I fulfill the conditions of getting a duplicant Jorge and after some time this crash happens. It can take a long time before the crash, or it can happen the first time the duplicate communicates with Jorge and the duplicate activates a positive reaction from Jorge's skill.

The game highlights Fast Track in red and disables it at this crash.

NullReferenceException

UnityEngine.Component.TryGetComponent[T] (T& component) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)
PeterHan.FastTrack.UIPatches.Chatty_OnStartedTalking_Patch.Prefix (System.Object data, Chatty __instance) (at <1f64286189364d7b9fc5956c06073077>:0)
(wrapper dynamic-method) Chatty.Chatty.OnStartedTalking_Patch1(Chatty,object)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <3ca21dc18eae422d87255277091f8593>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <3ca21dc18eae422d87255277091f8593>:0)
ConversationManager.DoTalking (Conversation setup, MinionIdentity new_speaker) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
ConversationManager.Sim200ms (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
SimAndRenderScheduler+Sim200msUpdater.Update (ISim200ms updater, System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <3ca21dc18eae422d87255277091f8593>:0)
Game.SimEveryTick (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

[Player.log](https://github.com/peterhaneve/ONIMods/files/15305158/Player.log)

**Comment by peterhaneve** [comment]
Fast Track will be blamed for every crash, regardless if it is at fault. It appears that the base game fails to unsubscribe Jorge's behavior when it is cleaned up, potentially causing a random crash on the next conversation depending on component update order.  A workaround will be added in the next Fast Track release.
