### ISSUE TITLE
Fast Track

### ISSUE THREAD

**Issue by vsjoke** [peterhaneve/ONIMods#467]
## Mod Versions
0.13.5.0

## Steps to Reproduce

1.
2.
3.
4.

## Output Log
KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
NavTeleportTransitionLayer.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
TransitionDriver.BeginTransition (Navigator navigator, Navigator+ActiveTransition transition) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
TransitionDriver.BeginTransition (Navigator navigator, NavGrid+Transition transition, System.Single defaultSpeed) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
Navigator.BeginTransition (NavGrid+Transition transition) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
(wrapper dynamic-method) Navigator.Navigator.AdvancePath_Patch0(Navigator,bool)
TransitionDriver.UpdateTransition (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
Navigator.SimEveryTick (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
Navigator+States+<>c.<InitializeStates>b__5_2 (Navigator+StatesInstance smi, System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <3ca21dc18eae422d87255277091f8593>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <3ca21dc18eae422d87255277091f8593>:0)
Game.SimEveryTick (System.Single dt) (at <3d436e4ec1d5455793674ec559b0cc77>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U51-600112-S (FT-0.13.5.0)

**Comment by peterhaneve** [comment]
There is no Fast Track code in this crash and no steps to reproduce it or output log. If this issue can be reproduced without Fast Track installed, please file a bug on the [Klei Bug Tracker](https://forums.kleientertainment.com/klei-bug-tracker/oni/).
