### ISSUE TITLE
Critter sensor shows incorrect value for a moment on game loading with Fast Track

### ISSUE THREAD

**Issue by searingblow** [peterhaneve/ONIMods#468]
Critter sensor shows incorrect value for a moment on game loading with Fast Track

## Expected Behavior
Critter sensor ouputs consistent signal on game loading

## Current Behavior
Critter sensor counting less number than actual critter number in room during game loading

## Mod Versions
Fast Track 0.13.5.0

There was [a same bug in vanilla game](https://forums.kleientertainment.com/klei-bug-tracker/oni/critter-sensor-activating-on-load-r38531/). but it's fixed in [recent update](https://forums.kleientertainment.com/forums/topic/154523-game-update-february-2024-quality-of-life-596100/#comment-1700870). Somehow it still exists when Fast Track is enabled.

**Comment by peterhaneve** [comment]
It looks like this issue only reproduces in specific configurations depending on the order in which events are processed on load, which was masked in the base game because the base game room prober is so much slower. A workaround has been added in version 0.13.6.0.
