### ISSUE TITLE
Falling Sand Mod is currenntly broken

### ISSUE THREAD

**Issue by Finn090** [peterhaneve/ONIMods#47]
Since the Last Update the Mod is broken. Game crashes on startup. I tested out disabling all other mods and game still crashes with only this mod enabled.

I would be super cool if you could fix that. :)

**Comment by stcarlso** [comment]
You are most likely being served an old version of the mod, as the latest game update required changes to the code. Try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update the mod as suggested in the issue template.

**Comment by peterhaneve** [comment]
You are most likely being served an old version of the mod, as the latest game update required changes to the code. Try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update the mod as suggested in the issue template.
