### ISSUE TITLE
Smart Pumps: Vacuum Pump Melts at 319.7F

### ISSUE THREAD

**Issue by TheGrey01** [peterhaneve/ONIMods#470]
## Expected Behavior
Was not expecting the Vacuum Pump to melt at the temperature of plastic, I was expecting it to melt at the temperature of the refined metal it was using.  Might want to reverse the primary and secondary resources (IE make the refined metal as primary)

Installed and running Spaced Out.

## Current Behavior
Pump melted at 319.7F causing liquid Naptha on the floor.  (was trying to use vacuum pump to remove high temperature steam from a room with limited space)

## Mod Versions
Steam subscription, I have used mod updated to force update the mod, with no change.

## Steps to Reproduce

1. Create a Vacuum pump in a room with steam that is higher than the melting point of plastic
2. Watch pump quickly heat up and instead of breaking, it melts instantly.
3. See Step 1
4. repeat step 1 for same result.

## Output Log
No log, it wasn't a crash the pump just instantly melted instead of overheating, primary resource should be the refined metal with plastic being the secondary resource.

**Comment by peterhaneve** [comment]
The Vacuum Pump is based off of the vanilla Mini Pump, and thus has the same primary material order. Unfortunately, swapping the order of the materials would cause crashes with Vacuum Pumps on existing saves.
