### ISSUE TITLE
"No Sensor Limits" suport for the "Resource sensor" mod.

### ISSUE THREAD

**Issue by faltonico** [peterhaneve/ONIMods#476]
This mod doesn't support "Resource Sensor" mod. https://steamcommunity.com/sharedfiles/filedetails/?id=2911545239

## Expected Behavior
You should be able to input any value in the resource sensor.
Using the stable release with DLC.

## Current Behavior
The resource sensors cap at 100 k units

## Mod Versions
I am using a local copy, copied from steam.
I use mod updater and it deems it as updated.

## Steps to Reproduce
1. Install resource sensor and no sensor limits mods.
2. Input any value at the resource sensors.
3. See how it doesn't go past 100 k .

## Output Log
No crash, no error in the log.

**Comment by peterhaneve** [comment]
This mod adds a cloned copy of the capacity control side screen, so it will not receive a patch for increased limits. If Resource Sensor wants to support expanded sensor limits, it should implement support on its end.

A conditional patch for No Sensor Limits to detect the mod and patch it at runtime is far more fragile and likely to break if either mod updates, but can be done if the other mod cannot make these changes.

**Comment by faltonico** [comment]
Welp, he thought the fix would be easier on your end, I'll take him the message.
Thank you.

**Comment by peterhaneve** [comment]
Since No Sensor Limits needed to be updated anyways as the new beta rolls out, I went ahead and added an explicit compatibility patch by name for this mod.
