### ISSUE TITLE
Cant build wire if the airlock is constructed first. 

### ISSUE THREAD

**Issue by eblieb** [peterhaneve/ONIMods#477]
Can't finish the airlock wiring if the airlock is built first. 2 possible fixes are to move the airlock power outlet to the outside of the airlock instead of middle (can rotate it to flip what side the power is on) or to allow the airlock to work in manual just as a normal manual airlock  (gasses and liquids can pass) so that the dupes can finish with the power.

**Comment by peterhaneve** [comment]
Unfortunately, moving the power outlet to the outside will break all existing builds with doors. Allowing manual operation at all will be a full rewrite of the mod state machine for very little gain.

Consider building the wires first, and then the door.
