### ISSUE TITLE
Destroy Filter is extremely frustrating to use.

### ISSUE THREAD

**Issue by piisfun** [peterhaneve/ONIMods#478]
Every time the liquid, gas, or power overlays open, the tool sets itself to only affect those items.

While this makes sense, it creates an issue: selecting certain buildings to place automatically selects these overlays, which results in the filter being constantly reset if building arrays of pumps or power plants.

Ideally, the filter should store the setting prior to opening the data view, then revert to that filter after the overlay closes.
This is what the game does for the deconstruct tool.

## Mod Versions
Steam: 3.11.0.0

**Comment by peterhaneve** [comment]
This feature is now enabled, but will only be available when the Frosty Planet Pack update goes live (it might also work on the public testing branch, but remember there is no support for mods on this branch).

The mod does not store a stack of menu values or a set per overlay (as this is contrary to the original feature request), the previously selected values will only be restored when exiting all overlays.
