### ISSUE TITLE
Queue for Sinks Mod is currently broken

### ISSUE THREAD

**Issue by Finn090** [peterhaneve/ONIMods#48]
The Mod currently leads to the game to crash on startup. It is the same Issue as the Falling Sand Mod.
It also crashes if only this mod is enabled.

I would be very grateful if you could fix that :)

**Comment by stcarlso** [comment]
You are most likely being served an old version of the mod, as the latest game update required changes to the code. Try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update the mod as suggested in the issue template.

**Comment by peterhaneve** [comment]
You are most likely being served an old version of the mod, as the latest game update required changes to the code. Try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update the mod as suggested in the issue template.
