### ISSUE TITLE
Forbid Items - Localization

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#486]
I understand that you have a lot of things to do because of the recently released dlc, if you have free time please add the possibility of localization to this mod.

Ru
ForbidItemsStrings.MISC.STATUSITEMS.FORBIDDEN.NAME = "Предмет запрещён";
ForbidItemsStrings.MISC.STATUSITEMS.FORBIDDEN.TOOLTIP = "Дубликанты и автосборщики не могут подобрать этот предмет;
ForbidItemsStrings.UI.USERMENUACTIONS.FORBIDITEM.NAME = "Запретить предмет";
ForbidItemsStrings.UI.USERMENUACTIONS.FORBIDITEM.NAME_OFF = "Разрешить предмет";
ForbidItemsStrings.UI.USERMENUACTIONS.FORBIDITEM.TOOLTIP = "Запретить подбирать этот предмет";
ForbidItemsStrings.UI.USERMENUACTIONS.FORBIDITEM.TOOLTIP_OFF = "Разрешить подбирать этот предмет"

**Comment by peterhaneve** [comment]
How does this po file look? You can unzip it into the mod folder (local or Steam) and the translations should be applied automatically: [translations.zip](https://github.com/user-attachments/files/16326404/translations.zip)

**Comment by DarkEviL88** [comment]
thx
I just couldn't find a template for the translation.
Forbid Item has a missing letter in the translation field. “Запретить предме” It should be ”Запретить предмет”

**Comment by peterhaneve** [comment]
This change will be pushed live on the next update of this mod. Thank you for contributing!
