### ISSUE TITLE
Show building range crashes after telescope rework

### ISSUE THREAD

**Issue by tamnguyenswe** [peterhaneve/ONIMods#488]
## Expected Behavior
Should not crash and show buildings' ranges like expected

## Current Behavior
Game crashes after load **if there is a telescope on the map**

## Mod Versions
3.5.0.0

## Steps to Reproduce

1. Get a save file with a telescope, either vanilla or DLC enabled
2. Load the save file
3. The game will crash

**Comment by peterhaneve** [comment]
Please attach an output log, as this error does not reproduce locally

**Comment by peterhaneve** [comment]
It looks like this can only happen if you load an old, migrated save, last saved with very old versions of this mod. I have uploaded a new version with a workaround to migrate very old saves to the latest version.
