### ISSUE TITLE
help? fast track specific

### ISSUE THREAD

**Issue by anata1** [peterhaneve/ONIMods#490]
I've downloaded the local mods zip file a few times since the most recent update, but when I open it, whether I just open, or extract and open, I can't find fast track in it. as in I read the whole list and nothing is called fast track, nor can I find either of those words when searching the folder. FastSave is right before FinishTasks when I sort them alphabetically. I'm assuming this is just an error on my end, but I have no idea what, nor how to fix it! and I have barely figured out how to download anything at all from github, so please don't expect me to understand complicated tasks here ^^; I can screenshot the folder I have if that would help though?

## Expected Behavior
fast track should be in the folder

## Current Behavior
I'm really hoping I'm just blind or something, but I see no signs of the file anywhere at all, and am not aware of any other way to get this mod

**Comment by peterhaneve** [comment]
Fast Track is not part of the local mods zip file. You probably want the [dedicated Fast Track release](https://github.com/peterhaneve/ONIMods/releases/tag/FastTrackBeta) tag instead.

**Comment by anata1** [comment]
Thank you so much!
