### ISSUE TITLE
PeterHan.StockBugFix.PlantIrrigationFixPatches:ExtendPlant_Postfix(GameObject)

### ISSUE THREAD

**Issue by bodyboarder2528** [peterhaneve/ONIMods#495]
I get this error
DetourException: Unable to find growing on type TreeBud
 
PeterHan.PLib.Detours.PDetours.DetourField[P,T] (System.String name) (at <76cc4a41439d430d8224825b28f48d8e>:0)
PeterHan.StockBugFix.PlantStatusMonitorFixed..cctor () (at <76cc4a41439d430d8224825b28f48d8e>:0)
Rethrow as TypeInitializationException: The type initializer for 'PeterHan.StockBugFix.PlantStatusMonitorFixed' threw an exception.
UnityEngine.GameObject:AddComponent()
EntityTemplateExtensions:AddOrGet(GameObject)
PeterHan.StockBugFix.PlantIrrigationFixPatches:ExtendPlant_Postfix(GameObject)
EntityTemplates:EntityTemplates.ExtendPlantToFertilizable_Patch1(GameObject, ConsumeInfo[])
BasicSingleHarvestPlantConfig:CreatePrefab()
EntityConfigManager:RegisterEntity(IEntityConfig)
EntityConfigManager:LoadGeneratedEntities(List`1)
LegacyModMain:LoadEntities(List`1)
LegacyModMain:Load()
Assets:CreatePrefabs()
Assets:OnPrefabInit()
KMonoBehaviour:InitializeComponent()
KMonoBehaviour:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
Util:KInstantiate(GameObject, Vector3, Quaternion, GameObject, String, Boolean, Int32)
Util:KInstantiate(GameObject, GameObject, String)
LaunchInitializer:Update()
 
Build: U52-622509-SCD

**Comment by peterhaneve** [comment]
Please attach a complete output log. From the looks of this crash log, you are still using the previous version of Stock Bug Fix. Consider using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
