### ISSUE TITLE
[StockBugFix] Crash when switching between saves

### ISSUE THREAD

**Issue by Glampi42** [peterhaneve/ONIMods#498]
## Expected Behavior
Crash shouldn't occur
I have both Spaced Out! and Frosty Planet Pack DLCs installed and enabled; game version is U52-623711-SCD

## Current Behavior
When I load a save file after loading another one and then unpause the game, it crashes.

## Mod Versions
Steam subscription; tried force-updating, the mod's version is v4.1.0.0

## Steps to Reproduce
1. Start the game
2. Load first save file (Spaced Out! and Frosty DLCs enabled, screenshot below shows the world)
![oni_world1](https://github.com/user-attachments/assets/9a8a8f43-6ccf-4934-b02a-d1f2b44d25a5)
3. Upon loading, load another save file (Spaced Out! DLC enabled, tiny debug world, screenshot below shows the world)
 ![oni_world2](https://github.com/user-attachments/assets/2b166b50-6ed6-4caf-91c8-447da88a73ab)
4. Unpause the game

## Output Log
[Player.log](https://github.com/user-attachments/files/16424794/Player.log)

**Comment by dlebedev** [comment]
> [08:40:10.092] [1] [WARNING] Failed to find cluster clusters/TinyEmptyCluster including the scoped path, setting to default cluster name.
> [08:40:10.092] [1] [INFO] ClusterCache: clusters/SandstoneDefault,expansion1::clusters/ForestStartCluster,expansion1::clusters/KleiFest2023Cluster,expansion1::clusters/MiniClusterBadlandsStart,expansion1::clusters/MiniClusterFlippedStart,expansion1::clusters/MiniClusterForestFrozenStart,expansion1::clusters/MiniClusterMetallicSwampyStart,expansion1::clusters/MiniClusterRadioactiveOceanStart,expansion1::clusters/SandstoneStartCluster,expansion1::clusters/SwampStartCluster,expansion1::clusters/VanillaArboriaCluster,expansion1::clusters/VanillaAridioCluster,expansion1::clusters/VanillaBadlandsCluster,expansion1::clusters/VanillaForestCluster,expansion1::clusters/VanillaOasisCluster,expansion1::clusters/VanillaOceaniaCluster,expansion1::clusters/VanillaSandstoneCluster,expansion1::clusters/VanillaSandstoneFrozenCluster,expansion1::clusters/VanillaSwampCluster,expansion1::clusters/VanillaVolcanicCluster,dlc2::clusters/CeresClassicCluster,dlc2::clusters/CeresClassicShatteredCluster,dlc2::clusters/CeresSpacedOutCluster

Looks like your problem is there

**Comment by peterhaneve** [comment]
This looks like a race condition in the base game if room prober calls are not cleaned up between loads. A workaround has been added to the latest version of Stock Bug Fix.
