### ISSUE TITLE
Fluid Shipping mod doesn't actually update when mod loader tries to update it.

### ISSUE THREAD

**Issue by mooklepticon** [peterhaneve/ONIMods#500]
## Expected Behavior
Mod Loader sees that Fluid Shipping is out of date and updates it to the latest version.

## Current Behavior

When installing the fluid shipping mod, it installs as a version from 2022. Mod loader sees that the latest is 2024. ML tries to update it, reboots ONI, but it doesn't work. FS still shows 2022 version.

## Mod Versions
Steam version. Yes, I've tried ML to force an update of FS.

## Steps to Reproduce
1. Install Mod Loader.
2. Install Fluid Shipper
3. ML says reboot ONI because FS is out of date.
4. Reboot succeeds, ML says the same thing again.

## Output Log

[Player.log](https://github.com/user-attachments/files/16444019/Player.log)

**Comment by peterhaneve** [comment]
This log is not from a run where Fluid Shipping was actually updated, but from the synptoms it appears that Steam is failing to download Fluid Shipping, leaving it stuck in thr zero byte state. This is a [vanilla bug](https://forums.kleientertainment.com/klei-bug-tracker/oni/my-game-wont-start-anymore-r44821/?tab=comments).
