### ISSUE TITLE
FastTrack question

### ISSUE THREAD

**Issue by MissPotato** [peterhaneve/ONIMods#501]
Not really an issue, but does FastTrack change the behavior of fluid/gases movement? Actually, in general, I'm curious about the parity between this and vanilla. Personally, the performance gain is worth it, but it would be nice to know for when I follow guides and the such. 

## Expected Behavior
Yes I have Spaced Out

## Mod Versions
Local 0.0.14.0

**Comment by peterhaneve** [comment]
Liquid and gas movement is performed by a different part of the game, written in a faster natively compiled language, and is thus usually insulated from changes made by most mods. Fast Track does not currently make any native code mods to this part of the game.

**Comment by MissPotato** [comment]
Thank you for the quick response! Now that you mention it, I remember hearing about there being some binary basically untouchable by mods.
