### ISSUE TITLE
[StockBugFix] New fix request: Natural Gas Generator's gas output temperature

### ISSUE THREAD

**Issue by Sad-theFaceless** [peterhaneve/ONIMods#503]
Hello! I'm not really sure about what the procedure is, when asking for a new fix to be added to the StockBugFix mod, so I'm opening an issue.

The Natural Gas Generator is supposed to output CO2 at 110°C, like every other generator (Coal/Wood/Petroleum).

However, unlike the other ones, the Natural Gas Generator's CO2 output is made through a pipe. This induces a bug where the CO2 is outputed at the building's temperature, instead of 110°C.

This bug has already been reported twice, as far as I know:
[https://forums.kleientertainment.com/klei-bug-tracker/oni/natural-gas-generator-not-producing-output-at-the-correct-temperature-r43070/](https://forums.kleientertainment.com/klei-bug-tracker/oni/natural-gas-generator-not-producing-output-at-the-correct-temperature-r43070/)
[https://forums.kleientertainment.com/klei-bug-tracker/oni/natural-gas-generator-co2-output-r23484/](https://forums.kleientertainment.com/klei-bug-tracker/oni/natural-gas-generator-co2-output-r23484/)
But it looks like Klei doesn't even acknowledge it.

If this is the wrong procedure, please let me know how I can request a bug fix, or even better, if there is any documentation about how to implement a fix into this mod.

Thank you!

**Comment by peterhaneve** [comment]
There are probably numerous builds unintentionally relying on this bug. "Fixing" it could break people's colonies without warning.

If Klei does not react to the bug, it may be possible to add as an option, but since it must be disabled by default hardly anyone would know about or use the feature.

**Comment by Sad-theFaceless** [comment]
> There are probably numerous builds unintentionally relying on this bug. "Fixing" it could break people's colonies without warning.
> 
> If Klei does not react to the bug, it may be possible to add as an option, but since it must be disabled by default hardly anyone would know about or use the feature.

Yes that's true. Adding it as a disabled option by default seem smart. Even though the new DLC already broke a lot of people's colonies because of the temperature revamp...

On the other hand, fixing it would allow a pretty easy molten slickster ranching!

**Comment by peterhaneve** [comment]
The next release version (which will not be released until some other fix is needed) will contain this option.
