### ISSUE TITLE
Unrelated to your mods, but potentially useful for you: a rimworld mod Dub's Performance Analyzer

### ISSUE THREAD

**Issue by MissPotato** [peterhaneve/ONIMods#504]
I'm not a really a coder so I do not know how useful this will be for you, but I'm a guinea pig for some RimWorld modders. One of which is [Dub's Performance Analyzer](https://github.com/Dubwise56/Dubs-Performance-Analyzer) it is an open source GUI based performance analyzer built for RimWorld. The analyzer was designed in a way to be pretty agnostic to the actual game itself as rimworld has a lot of complete overhaul mods. Which is why I think it might be useful for you. Especially considering RimWorld is also a unity built game. If it isn't helpful just feel free to close this issue. (This is also why I sent you a friend request on steam a week ago, but I realized I can just tell you here.)

**Comment by peterhaneve** [comment]
Fast Track actually already has a rudimentary performance analyzer, although this mod definitely goes into more detail. The challenge is that analyzing performance itself adds a small calculation overhead, and RimWorld has a _vastly_ different scale than ONI - the base game can easily have **100 000** game objects updating per frame in a late game colony, numbers that RimWorld will never even approach. The approaches used by this mod will never scale to the levels that ONI would require.

That said, a few techniques from that source code might be useful to add in debug Fast Track builds. Unfortunately the mod itself as a whole will not work with the convoluted ONI mod loader.
