### ISSUE TITLE
[Fast Track] Crash when checking "sweep only" just before a non-sweep delivery happened.

### ISSUE THREAD

**Issue by isochronous** [peterhaneve/ONIMods#506]
## Expected Behavior
I had a bottle emptier set to request crude oil. Just as a duplicant was arriving to deliver a bottle, I checked the "sweep only" box. The duplicant should have either dropped the bottle or completed the delivery without issue.
Both DLCs are installed. I am not using any special branches.

## Current Behavior
The duplicant delivered the bottle, and the game immediately crashed.

## Mod Versions
Local copy v0.14.0.0

## Steps to Reproduce

1. Set a bottle emptier to request some liquid. Do not check "sweep only".
2. Let a duplicant get to the point of almost delivering a bottle.
3. Check the "sweep only" box.
4. Dupe should deliver bottle, game should crash.

## Output Log
https://gist.github.com/isochronous/001de69a2e023106e761ec64e23a03ce

**Comment by peterhaneve** [comment]
> `StormShark.BottleInserterComplete`

It looks like Fast Track is conflicting with another mod, possibly by the author "Storm Shark" or similar. Does the issue reproduce if this mod is disabled?

**Comment by isochronous** [comment]
It looks like that's the Fluid Shipping mod.  I'll give it a try and report back tomorrow.

**Comment by peterhaneve** [comment]
After some searching, this is probably one of the [many](https://forums.kleientertainment.com/klei-bug-tracker/oni_so/switching-bottle-emptier-to-sweep-only-during-the-errand-will-crash-the-game-r26708/) [vanilla](https://forums.kleientertainment.com/klei-bug-tracker/oni_so/bottle-emptier-does-not-always-obey-sweep-only-flag-r28035/) [bugs](https://forums.kleientertainment.com/klei-bug-tracker/oni_so/dupes-delivering-non-sweep-liquids-to-sweep-only-bottle-emptier-r28298/) with sweep only bottle emptiers.
