### ISSUE TITLE
Starting area is +1600K

### ISSUE THREAD

**Issue by HofNerd999** [peterhaneve/ONIMods#508]
## Expected Behavior
The starting biome is not too hot to survive.

Spaced Out installed: Yes.
Public preview branch: No.

## Current Behavior
The starting biome is +1600K on start.
![20240821124157_1](https://github.com/user-attachments/assets/9c881518-4ef7-4f27-917b-ff800172b6f8)

## Mod Versions
Steam workshop: Yes.
Force updated with Mod Updater mod: Yes, problem persisted.

## Steps to Reproduce
1. Start a new 100K-start game.
2. Wait dig out nearby sandstone.
3. Watch dupes die a horrible death by molten copper.

## Output Log
Log file: [Player.log](https://github.com/user-attachments/files/16690544/Player.log)

**Comment by peterhaneve** [comment]
It appears that a recent hotfix added a new temperature range. 100K Challenge (legacy) has been updated to move the 100 K range index farther up and outside the default ranges.
