### ISSUE TITLE
[Suggest] AirLock Door

### ISSUE THREAD

**Issue by roulito** [peterhaneve/ONIMods#51]
Leave the gases and liquids passed in the SAS and are sucked in an internal storage at the door or directly output for the gas and liquid with exits pipe.

If possible history of actually having a SAS and not just a door that blocks everything without interaction.

Thanks for reading me
Sorry english google translate.

**Comment by peterhaneve** [comment]
While I considered this suggestion initially, the current design makes it much easier to remember exactly where the gases came from, and where to send them back later.
