### ISSUE TITLE
[Mod Updater] How to make the auto-updater ignore local changes to mod files

### ISSUE THREAD

**Issue by kaedys** [peterhaneve/ONIMods#511]
For several mods, I've extracted the DLL from their bin file, decompiled it and modified some settings (such as tile cost or building power consumption or w/e) and/or fixed some small bugs in the code, the recompiled them and shoved them back in the bin.  For _most_ of the mobs I've done this with, Mod Updater either didn't even notice, or displays it as "a newer version is running locally".  However, for ONE mod, it displays instead as "an older version of this mod is running locally", though it displays identical timestamps in the mouseover.  Every time I start the game, it displays that mod as "Content changed" and wants to restart the game, yet doesn't actually change or update the local bin (thankfully) when I do so (it just wants to restart loop).

Now, I can escape past that restart prompt, but I'm wondering what the mod uses to determine newer vs. older, and if there's some change I could make to the local files to get it to see it as newer rather than older?  I tried changing the version in the `mod_info.yaml`, but that didn't seem to affect it.  I'm _just_ dipping my feet into ONI modding, so I'm not _super_ familiar with how mod versioning and such is done.

**Comment by peterhaneve** [comment]
Which mod are you changing? Mod Updater demotes the error to a warning (and allows you to continue without a dialog) if the mod version appears to be _newer_, but the concept of newer only applies to mods with versions in a specific format. Some mods use a mod version that does not conform to the format and cannot be parsed; Mod Updater must assume the worst in those circumstances.

**Comment by kaedys** [comment]
It's currently occurring for two of them, Microtransformer (which has a version line in the YAML of `version: "2.0.2"`) and Item Permeable Tile (which, weirdly, also has the exact same line, `version: "2.0.2"`).  In the case of the former, I didn't modify the version string (it's equal to what it was prior to me modifying the DLL), but in the latter, it was originally `version: "2.0.1"` and I incremented it to see if that would cause the updater to behave (which it did not).

Is it the quotes that's throwing it off?  I don't see them in some of the other mod_info files that are working, but I've not checked exhaustively (and I've only modified a handful locally anyway).

**Comment by peterhaneve** [comment]
The "content changed" decision is made by the base game, not by Mod Updater. It checks the available local content against the cached Steam ZIP file and sees if new DLLs/world gen/translation has been added. There are base game bugs in this department, but they cannot be fixed by Mod Updater as the methods are already on the call stack when mods are first loaded.

One way to avoid the issue completely is to copy the patched mod to the Local folder, and disable the Steam version. Mod Updater will not be enabled for local mods unless the author opts in.

**Comment by kaedys** [comment]
Ah, ok, noted.  May have to dig into the way the game checks it, but I suspect your solution is probably the best option.  When using the local folder, does that also get me around the need to push the recompiled DLL into a legacy.bin archive?  Because that would be extremely nice.
