### ISSUE TITLE
Roller Snakes Reborn Translation

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#512]
Could you please share the template for translating this mod if you have one, or make it possible to translate this mod. When I have a template, I will make a translation and share it with you. Thanks.

**Comment by peterhaneve** [comment]
The Roller Snakes Reborn POT is available at [rollersnake_template.zip](https://github.com/user-attachments/files/16956390/rollersnake_template.zip)

**Comment by DarkEviL88** [comment]
[ru.zip](https://github.com/user-attachments/files/16960020/ru.zip)

**Comment by DarkEviL88** [comment]
[ru.zip](https://github.com/user-attachments/files/16960508/ru.zip)

**Comment by peterhaneve** [comment]
Created commit https://github.com/peterhaneve/TestONIMods/commit/8b7485ec519a5df3ab8f13e81971d78da1ecbbb0 with this translation. Thank you for contributing!

(actual Steam release will come later once some other issues are resolved)
