### ISSUE TITLE
Oni Fast Track Morb emissions

### ISSUE THREAD

**Issue by SquarelyCircle** [peterhaneve/ONIMods#513]
If I'm not mistaken, morbs emit polluted oxygen based on movement. Something like releasing a toot every 5 steps or something (I don't recall the specifics). It seems that when decreased idling of critters is on, the morbs cease to release polluted oxygen. It's a hard thing to be sure about, but when this was on, my polluted oxygen pressure was down to 100-200 in a quarter of the tiles, but after turning it on for a few cycles, it was up to 600-700 in 3/4 of the tiles available.

## Expected Behavior

When morbs move, they release polluted oxygen at a specific rate. That rate should be maintained even if the morbs do not move.

I'm using the Spaced Out! DLC, but not the Frosty Pack. I also have dozens of mods.

## Current Behavior

Morb emissions appear to be down. It seems that they should be consistent regardless of movement.

## Mod Versions

Local copy of fast track

No, I only installed the mod a few days ago.

## Steps to Reproduce

1. Get an outhouse to the point that it needs a dupe to empty it.
2. Lock the door so dupes can't empty it.
3. Over time, morbs will spawn and build up.
4. The morbs should fill the area with polluted oxygen.
5. With the mod on, and critter idle movement improvements enabled, the morbs don't seem to produce as much polluted oxygen.

**Comment by peterhaneve** [comment]
If you enabled *Reduce Idle Movement* in the options, then Morb emissions are the least of your worries - this option also affects everything from "pez dispenser" designs to Saturn Critter Traps to Drecko scale growth. It is disabled by default for this reason, and tuning every behavior that it affects in the base game (let alone that in the many critter mods) one by one to behave identically is not worth the effort.

It is best to treat this option as a last resort, as it has fairly noticeable gameplay impacts.
