### ISSUE TITLE
Any hopes of an update for Efficient Supply? Or anyone want to fork it if it's ok with Peter if he is done with it? 

### ISSUE THREAD

**Issue by Etrit1** [peterhaneve/ONIMods#514]
I haven't played ONI in awhile and noticed Efficient Supply hasn't been updated since 23 and doesn't work even on the latest version of the base game. :-(

ES is a HUGE change to how the game works... 

Please please can we get an update?

Unless it's not needed anymore?

**Comment by peterhaneve** [comment]
Efficient Supply is up to date and has not needed updates since then. If you are experiencing an issue, the most likely solution is [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
