### ISSUE TITLE
Spanish Translations for many of your MODs - Traducciones al Español de muchos de tus MODs

### ISSUE THREAD

**Issue by edubistkrank** [peterhaneve/ONIMods#516]
Good morning to everyone! Sadly is not friday...

First of all sorry for my english (so funny talking about mods translations), I had a bit of free time and I translated many of your mods to Spanish. 

I really want to give you THANKS for all your works, I'm really new in ONI, MODS, GITHUB and verything, except life, I'm not new in life xD

So, no more words, here is a list with all my translations, I have take care of every detail and of of course make it match with the full game Spanish translation.

![ONI - ModsTransList](https://github.com/user-attachments/assets/84a50d47-6b1e-47a9-af68-a2d49e550107)

[ONI-MODSTRANSLATION.zip](https://github.com/user-attachments/files/17026617/ONI-MODSTRANSLATION.zip)

As I said I'm a noob in all of this, any issue or whatever let me know, hope this can help the people.

THANK YOU SO MUCH

.- edubistrank -.

**Comment by peterhaneve** [comment]
Thank you for contributing! I can only add translations to "Sandbox Tools", "Smart Pumps", "Sweep by Type" and "Waste Not, Want Not". Some of the mods in this list are not authored by me.

For "No Manual Delivery" and"Squirrel Generator" please contribute to https://github.com/SanchozzDeponianin/ONIMods

For "Backwalls" contribute to https://github.com/aki-art/ONI-Mods

For "Bubbles Bathtub", "Daily Routine", "Duplicant Stat Selector", "Mass Move To", "Paint your Pipes" and "Crown Moulding Skin" contribute to https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods

For "Advanced Flow Management" contribute to https://github.com/Glampi42/ONI-Mods

For "Planning Tool" contribute to https://github.com/Artorp/PlanningTool/

For "Tiny Door" contribute to https://github.com/davkas88/ModNotIncluded

For "Extended Building Width" contribute to https://github.com/pakvg85/ONIMods

For "Wall Pumps" contribute to https://github.com/DrFair/WallPumps and https://github.com/Pholith/ONI-Mods

For the other mods, please contact the authors on their Steam comments page.

**Comment by edubistkrank** [comment]
Thank you very much for your time, and sorry about my mistake ¬¬

I will try to contribute in every specific repository.

Thank again, so great job you did.
