### ISSUE TITLE
[StockBugFix] New fix request: Germ Source icon on actual germ sources

### ISSUE THREAD

**Issue by Sad-theFaceless** [peterhaneve/ONIMods#518]
Hi, it's me again.

As we all know, the Germ Source icons are missing on most germ sources, namely:
- Floral Scent germ sources: Bristle Blossom, Buddy Bud and Bammoth
- Zombie Spores germ sources: Sporechid
- Maybe the Radioactive Contaminants' "germ" sources: Research Reactor and Radbolt Engine

![image](https://github.com/user-attachments/assets/2eabb5e1-f476-431b-ac48-ece229b53668)

I just thought it would be nice to have a germ overlay actually indicating the germ sources, like it's supposed to.

The issue has been reported a few times, including:
https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-germ-source-indicator-on-plants-r42969/ (missing SO and FP elements)

Thank you!

**Comment by peterhaneve** [comment]
Visualizers have been added to most base game diseases sources in version 4.3.

**Comment by Sad-theFaceless** [comment]
New game's beta update supposedly implemented this fix in the actual game, gotta check if they didn't miss anything

**Comment by Sad-theFaceless** [comment]
![image](https://github.com/user-attachments/assets/5a65b4f3-ccd9-4981-af48-a89bf9bc35c3)

@peterhaneve  It does look like they added everything, this patch can be undone!
