### ISSUE TITLE
Stock Bug Fix breaks game localization

### ISSUE THREAD

**Issue by DarkEviL88** [peterhaneve/ONIMods#519]
Breaks game localization in the "CONSUMABLES" and "DATABASE" if Stock Bug Fix is enabled. The name and description of the food becomes in English.

With the mod disabled:
![image](https://github.com/user-attachments/assets/7cecb705-862d-42a7-b09c-0a43587a08a0)
After I enabled the mod:
![image](https://github.com/user-attachments/assets/c9982c78-7106-42ea-8eef-5c2d201f3f0b)

![image](https://github.com/user-attachments/assets/51f2bb81-60aa-45cb-be94-6c79e352d9c2)

My native language is Russian.

Just in case, here's the log file:
[Player.log](https://github.com/user-attachments/files/17148478/Player.log)

**Comment by peterhaneve** [comment]
This looks like a base game transitive string loading bug in the Bammoth and its dependencies. Any reference to it will cause completely unrelated strings to break.

A workaround has been added in Stock Bug Fix version 4.4.
