### ISSUE TITLE
Rescupt is NOT working

### ISSUE THREAD

**Issue by Sareya84** [peterhaneve/ONIMods#52]
Hi again!
I read your last comment and understand now that the dupe doesn't actually come to reculpt the item; however, it still doesn't change the fact that nothing happens when I click on the "Resculpt" button. The sculpture remains the same and does not resculpt. Should I be looking at other mods that may be interfering with it? I know other people people on the Steam forums have been having the same issue with Resculpt not working. If there is something I can do to help, let me know! Thank you for all your hard work and patience. =)
Sareya

**Comment by peterhaneve** [comment]
Did you start it while unpaused? Due to a limitation of how the sculpture code handles changing animations, Resculpt can be buggy if you resculpt while the game is paused. Does the issue reproduce (you can start a different save) if Resculpt is the only mod enabled?

**Comment by Sareya84** [comment]
Good morning!
OK, so I really went to work on this. Here are the things I've tried and their subsequent results:
1) Resculpting straight off loading into ONI with all mods in play: No resculpt
2) Resculpting on the pause screen with all mods in play: No resculpt
3) Resculpting right after restarting from pause with all mods in play: No resculpt
4) Resculpting straight off loading into ONI only with Resculpt loaded: No resculpt
5) Resculpting on the pause screen only with Resculpt loaded: No resculpt
6) Resculpting right after restarting from pause only with Resculpt loaded: No resculpt
7) Unsubscribing, then resubscribing to Resculpt with only Resculpt loaded: No resculpt
8) Starting from a different save with only Resculpt loaded: No resculpt; thus, the issue invariably reproduces with whichever save I'm using, with only Resculpt enabled
9) With all mods enabled and only with Resculpt enabled, I tried waiting about 5 minutes before attempting to resculpt with the same results. =/
I logged in and out of the game too many times to count to try to reset everything and get Resculpt to work, but nothing seemed to get it to do it's job. This is kind of bumming me out and I hate how frustrating it must be for you as well. If I knew anything about coding or mod making, I'd help. As it stands, I can only offer any other help I can give. Let me know if I can try anything else or assist in any other way. =)
Thank you so much for your time and patience! <3
Sareya

**Comment by peterhaneve** [comment]
Are you resculpting a sculpture type with more than one variant? Only variants available at the same tier as the initial sculpture design can be chosen, and most sculptures have only one variant at the quaint and abstract levels.

**Comment by Sareya84** [comment]
I had to double check and looked it up, but yes: I am resculpting a sculpture with more than one variant. Right now, I have both the Sculpting Block (2 high) and the Large Sculpting Block (3 high) with the mid-tier Art tree talent Aesthetic Design (Quaint artwork). From what I've seen, I should be able to resculpt at the very least 2 types of each Sculpting Block that I'm able to make (i.e. "Abstract" and Quaint); however, I don't see any changes when using the "Resculpt" button, as I've indicated in my previous post. I'm not far enough along to try the Metal or Marble Sculpting Blocks, but am I correct in assuming that I should see the change in sculpture from Abstract to Quaint and vice versa? Or does ONI only let you use the highest tier Art talent's design (i.e only the mid-tier options if I've put points in it)?
Thank you again for all of your help and understanding! =)
Sareya

**Comment by peterhaneve** [comment]
Both the **Sculpting Block** and the **Large Sculpting Block** have only one variant at art level 2. Resculpt cannot be used to upgrade or downgrade the tier of a sculpture or painting.

Most art objects in the game only have multiple variants at **Masterpiece** quality.

**Comment by Sareya84** [comment]
I just wanted to thank you for all the help! I'm so sorry for any inconvenience I may have caused. Stay safe and be healthy! =)
Sareya



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
