### ISSUE TITLE
REQUEST: Fast Track - "Disable tutorials: OFF" includes "Food has decayed"

### ISSUE THREAD

**Issue by MegaJani** [peterhaneve/ONIMods#520]
As the title says, the above option would ignore rotten food and "blank" rot piles spawning from Exuberant plants.
Some farms generate hundreds of these notifications every few cycles.

**Comment by peterhaneve** [comment]
This notification barely impacts game speed (most of the tutorials check the whole map for some condition every frame like *Unrefrigerated Food*, but the food decay notification only triggers when rot piles actually spawn), so it is outside of the scope of Fast Track. It would be better off as a separate mod or as part of an overall notification manager.
