### ISSUE TITLE
QUESTION: Is there any chance the "Turn Back The Clock" mod could be used with Spaced Out?

### ISSUE THREAD

**Issue by marckat9** [peterhaneve/ONIMods#521]
Basically the title, I'm sorry if this is the wrong place to ask this, but is there any change that Turn Back The Clock could be compatible with spaced out? It's understandable if this is not the purpose of this mod, but it's the only mod (so far) that I've found that can revert the diagonal debris/building changes made in patch 463187 and it's unfortunate that it isn't compatible with Spaced Out.

**Comment by peterhaneve** [comment]
Turn Back the Clock is meant for continuing older (legacy) colonies, and would take quite a bit of work to port to Spaced Out. It may be worth making a separate mod however.

**Comment by marckat9** [comment]
Thanks for the fast answer, I believe that mod has a lot of QoL potential on it's hand, and thanks for considering looking it over, hope it won't be too much of a hassle if you decide on it. :D That's all I wanted to know thank you once again for your time.
