### ISSUE TITLE
“Falling Sand” lose effectiveness

### ISSUE THREAD

**Issue by wuguo138428** [peterhaneve/ONIMods#524]
“Falling Sand” lose effectiveness

**Comment by peterhaneve** [comment]
There is no information in this bug on the affected version or symptom. Please fill out the template when filing an issue - the information is required to help fix your issue!

**Comment by peterhaneve** [comment]
Attach the full output log to allow us to understand your issue. This file is located at

* Windows: %userprofile%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log
* Mac: ~/Library/Logs/Unity/Player.log
* Linux: ~/.config/unity3d/Klei/Oxygen Not Included/Player.log
