### ISSUE TITLE
[FastTrack] Crash with 21 Nov major game update

### ISSUE THREAD

**Issue by simy1129** [peterhaneve/ONIMods#528]
## Expected Behavior
The game should start normally

## Current Behavior
I have installed only base game and SO DLC. The game consistently crashes while start up after the major update. I have tried to disable all other mods and only enable FastTrack. but the same error occurs.

## Mod Versions
0.14.0.0
Updated manually from GitHub

## Steps to Reproduce

1. Start game
2. Enable FastTrack
3. Restart game
4. Game crash

## Output Log

[Player.log](https://github.com/user-attachments/files/17867831/Player.log)

**Comment by dannypar** [comment]
"The game should start normally" as a expected behavior? No, since there are major changes in the game due to the update it is expected that mod will crash your game so turn mods off and patiently wait for fast track update from Peter, like we all do.

**Comment by mrkrook2012** [comment]
Can confirm, Have all DLC's and have the same issue. Here is my crash report. Thank you Peter, your mod allows me to play this game with my bad laptop.
[Crash_Report.txt](https://github.com/user-attachments/files/17873271/Crash_Report.txt)

**Comment by Naikocklas** [comment]
if someone have a solution to this problem pls lmk

**Comment by peterhaneve** [comment]
This is a major breaking game update. It will be at least a week, if not much more, to rewrite Fast Track to support it.

**Comment by yousa121380** [comment]
Anyway, thanks peter, ONI is more fun because of you

**Comment by darkcyde6666** [comment]
Klei should employ you to implement Fast Track into their code properly!!

**Comment by peterhaneve** [comment]
As Klei has already started a public preview of the Bionic Duplicant DLC, which changes some major game systems yet again, no update will be made until that branch goes live.

**Comment by Skullition** [comment]
> As Klei has already started a public preview of the Bionic Duplicant DLC, which changes some major game systems yet again, no update will be made until that branch goes live.

Thanks for Fast Track! I assume this means at least a Jan 2025 update for Fast Track at the earliest?

**Comment by Naikocklas** [comment]
> As Klei has already started a public preview of the Bionic Duplicant DLC, which changes some major game systems yet again, no update will be made until that branch goes live.

any news?

**Comment by MiserableGamer** [comment]
The dlc isn't released yet, it's still in testing, and Peter already said
he won't be doing anything until it releases

**Comment by SartisonVV** [comment]
The extension is out. We are all really waiting) We hope to finalize the mod as soon as possible. And we really appreciate Peter's work.

**Comment by dannypar** [comment]
Yeah but he's like human being just like me and you, surely got some commitments of his own so stop pushing for something he do completely free.

**Comment by peterhaneve** [comment]
I do not yet own the DLC. Nevertheless, I have made most of the required changes for the live branch without DLC.
