### ISSUE TITLE
cautious request? ^^; single feature of fast track related

### ISSUE THREAD

**Issue by anata1** [peterhaneve/ONIMods#532]
Is there any real possibility you could offer (in my case, the -no diseases- branch) bits of the mod separately? my computer is fine enough to play without actually needing fast track, but I personally hate diseases, but because the whole fast track mod is so twined together, even if no diseases is literally the only bit of it I've got activated, it's still crashing the game entirely, which is fine! things change and we're human, so no judgements from me. But if the one bit I'm interested in were available separately, it's possible it might crash less often, and be less affected by updates, I'm hoping ^^;

if possible, you would have a very grateful follower!
and if not, welp, I'm hoping it didn't hurt to try? ^^;

thanks so much!~

**Comment by peterhaneve** [comment]
Extracting "No Diseases" from Fast Track will be a lot of work, as it uses other features of Fast Track to achieve the performance improvement.

In the vanilla game, diseases have almost no impact other than their (surprisingly large) performance decrease. What part of them is so hated? You can set disease difficulty when creating a new game to *Total Immunity* which makes it impossible to contract any disease, or use [Modify Difficulty Settings](https://steamcommunity.com/sharedfiles/filedetails/?id=2962220957) to change them after creating a game.

**Comment by anata1** [comment]
Honestly, I'm autistic, and all the stupid numbers going up and up and up
and always breaking confinement really bother me, and break a lot of my joy
in the game, especially because my brain knows they're supposed to be a bad
thing.

But waiting for the full thing just gives me a push to try other games in
my backlog for a while, so it's all good!
Thanks so much!
