### ISSUE TITLE
[Airlock Door] Bionic duplicants treat the door as if it doesn't exist when it's powered

### ISSUE THREAD

**Issue by UroshN** [peterhaneve/ONIMods#533]
## Expected Behavior
Playing with SpacedOUT; Frosty pack and Bionic Duplicants DLC installed, no preview or beta branches. Bionic duplicants should behave like regular duplicants and stop in the middle of the door until the other side opens.

## Current Behavior
Bionic duplicants currently completely ignore Airlock doors and go through them like ghosts, as if the door isn't there. Classic duplicants are unable to pass through normally as before and wait for the door to open. This only happens when the door is powered, when the door has no power it will normally block Bionic duplicants.

## Mod Versions
Using the Steam subscription, force updated with Mod Updater twice for good measure.

## Steps to Reproduce
1. Choose a Bionic duplicant
2. Build an Airlock door in a position that the only path to the other side is through them
3. Connect the door to a power source and wait for at least 1000 J of charge.
4. Order a Bionic duplicant to "Move To" the other side

## Output Log

[Player.log](https://github.com/user-attachments/files/18136293/Player.log)

**Comment by peterhaneve** [comment]
I do not own this DLC and cannot verify any fixes to the issue. I did give it a shot in the latest version which also has a much requested improvement to allow building the Power wire after the door is completed.

**Comment by MicahZoltu** [comment]
This bug is still occurring for me.  I'm on 3.12.0.0 of the mod which appears to be the latest.

Epic Games install, fresh install, fresh game, all mods and DLCs activated.

**Comment by peterhaneve** [comment]
The latest mod version is 3.13.0.0, but the local mod ZIP used for the Epic Games store was only updated a week or so ago. Try the latest local version.
