### ISSUE TITLE
[Airlock Door] Duplicants get chilly surroundings debuff when passing through the door

### ISSUE THREAD

**Issue by UroshN** [peterhaneve/ONIMods#534]
## Expected Behavior
Running SpacedOUT, Frosty Pack and Bionics DLC, duplicants shouldn't get chilly surroundings unless they are moving into a cold area

## Current Behavior
The recent fix seems to have worked both for the wire building and for Bionic Duplicants, they now pass normally. However, everyone seems to get chilly surroundings debuff now when passing through the Airlock door without an atmo suit. This happens in the middle of my base where it's a comfy 30 degrees. The door temperature is also 30 degrees. Happens to both regular and bionic dupes, so I don't believe it's related to the bionic dupes. Could be related to Frosty pack though.

## Mod Versions
Using Steam mod, updated with Mod Updater to the latest version

## Steps to Reproduce
1. Build an Airlock door with around 30 degree temperature material in an area that's around 30 degrees
2. Order a dupe to move through without an atmo suit
3. The dupe will get chilly surroundings debuff in the middle tile of the Airlock door

## Output Log

[Player.log](https://github.com/user-attachments/files/18140220/Player.log)

**Comment by peterhaneve** [comment]
This issue is sadly impossible to fix without making the Airlock Door itself a thermal insulator, which would completely break its balance.
