### ISSUE TITLE
Fast Track Slows Down Dupe Errand Time

### ISSUE THREAD

**Issue by Germany08** [peterhaneve/ONIMods#538]
## Expected Behavior

Fast track causes dupes to take longer when selecting errands than without fast track. Below is a video of dupes with fast track(2nd video) and a video of dupes without fast track(1st video). I have all DLCs. 

## Steps to Reproduce

1.Load a late game save
2.Give dupes a task

## Output Log
>
[Player.log](https://git

https://github.com/user-attachments/assets/0de1d85d-5d22-44e4-ae7e-9518e614a1e5

https://github.com/user-attachments/assets/def37d68-b5cf-4eef-b892-7d9e08f72326

hub.com/user-attachments/files/18219286/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/18219287/Player-prev.log)

**Comment by Germany08** [comment]
Here is the 2nd video
https://github.com/user-attachments/assets/237f8e44-e5f7-4e60-9a98-38c25da1dc0e

**Comment by peterhaneve** [comment]
There is an inherent trade-off between chore processing throughput (which Fast Track prioritizes) and individual Duplicant chore latency. In the most recent hotfix, Klei shifted more towards reducing latency by prioritizing specific Duplicants in some cases and delaying all the others.

In a large enough colony this tradeoff may be noticeable. The most recent version of Fast Track has been updated to execute Duplicants that the base game *thinks* have priority in some cases.

**Comment by peterhaneve** [comment]
Yes, this is a trade-off of Klei's new method. If this matters to you, an option to use the old method (or to *deliberately* delay a precise amount of time) can be added.
