### ISSUE TITLE
Game.OnApplicationQuit() when reloading a save ingame

### ISSUE THREAD

**Issue by faltonico** [peterhaneve/ONIMods#539]
The game is closing to desktop when i reload certain saves ingame.
The is no error in the log that i can see, only Game.OnApplicationQuit() and fast track gets disabled.

The game should load the save to keep playing.
The game closes when loading the save file.
The save reloads without this mod on.

For context, i was trying to find out the cause of a poodle of water popping up out of nowhere, and i think it is materializing into the game! (i know it is very easy to miss something like a patch of steam or a water pipe breaking but this is not the case!).

I am using ver 0.15.1 current game version with all DLC

## Steps to Reproduce
1. start the game.
2. load a save file
3. start playing
4. load a save file within the game
5. game closes.

## Output Log
[Game.OnApplicationQuit() con fast track.log](https://github.com/user-attachments/files/18220741/Game.OnApplicationQuit.con.fast.track.log)

**Comment by faltonico** [comment]
i can't reproduce it anymore, so don't pay attention to this =S

**Comment by faltonico** [comment]
I can reproduce it reliably. 
More logs here.
[1Player.log](https://github.com/user-attachments/files/18240282/1Player.log)
[Player.log](https://github.com/user-attachments/files/18240288/Player.log)

Pretty much the same:

    start the game.
    load a save file
    start playing
    load a save file within the game
    game closes.

The usual crash image appears for an instant but the game hangs and becomes unclickable. For what it is in the logs, I am under the impression that the mod is being disabled before reloading the save.
Here is the save, it has many mods but only dupery fixed and "6 More Bionic Dupes (Double the cast!)" (https://steamcommunity.com/sharedfiles/filedetails/?id=3385429972) are necessary to be able to open it.

https://www.mediafire.com/file/to5mguo9qy666rc/Orgásmico+40+ACERO.sav/file

**Comment by peterhaneve** [comment]
This looks like an issue with your save file, long before Fast Track even executes:
```
Newtonsoft.Json.JsonSerializationException: No JSON content found and type 'SaveGame+GameInfo' is not nullable. Path '', line 0, position 0.
```
It could be caused by a compatibility issue, especially since the Epic Games Store does not auto-update mods; debugging the issue with 56 active mods will be nearly impossible. Make sure that your other mods are all up to date and working.

**Comment by faltonico** [comment]
All mods were all up to date, (I update manually from steam with mod updater.)
It crashed with only 2 more mods besides fast track, "dupery fixed" and "6 More Bionic Dupes (Double the cast!)"
[Player.log](https://github.com/user-attachments/files/18241319/Player.log)

I can't disable those in that save file.

**Comment by peterhaneve** [comment]
> Rocketry Expanded

This mod may not be safe to deactivate on an existing game. Do you have any automated rockets? The crash points to an object in an invalid "world" ID, so something is in a destroyed rocket interior or similar.

**Comment by faltonico** [comment]
I don't have any of those on this colony just yet, that is why the save can load fine without them (if one had AI cores it wouldn't load), reloading is the thing i cannot do if i have fast track enabled.
Should i notify Sgt_imalas of a possible mod conflict? for "dupery fixed" in this case.
