### ISSUE TITLE
Crashes game on enable

### ISSUE THREAD

**Issue by Maelyno123** [peterhaneve/ONIMods#540]
## Expected Behavior

Mod should open and run with program, yields additional sandbox features

I have Spaced Out! DLC.  It started crashing with it.
Added Frosty Planet Pack and Bionic Booster Pack DLC just today. Also crashes with them

## Current Behavior

Upon Enable and close back to main menu, the mod crashes the system.

## Mod Versions

Yes.  No change in function issues

## Steps to Reproduce

1.  From Main Open Mods Menu
2.  Enable Instant Sandbox Mod
3. Close Mods Menu - system crates error immediately
4.

**Comment by peterhaneve** [comment]
This is not the correct location for reporting issues with Instant Sandbox. It looks like the only location to report issues is on the mod's Steam comments.
