### ISSUE TITLE
[Rest for the Weary] Duplicants are performing Relocate tasks when in the Finish Up shift.

### ISSUE THREAD

**Issue by ManInTheMists** [peterhaneve/ONIMods#542]
When Duplicants enter the Finish Up shift and would normally go to the printing pod, they instead perform Relocate tasks until their sleep shift begins.

## Expected Behavior
Duplicants travel to the printing pod or recreation room when they finish a task.

## Current Behavior
Duplicants start performing Relocate tasks if there are any available, even if they have a priority of 1.

## Mod Versions
Steam subscription, forcing update did not fix the issue

## Steps to Reproduce
0. Set up various Relocate tasks, priority does not seem to matter.
1. Run the game as normal
2. When a set of duplicants are about to enter the Finish Up shift, focus on one of them.
3. Observe the list of errands available to that duplicant.

## Output Log attached
[Player.log](https://github.com/user-attachments/files/18274214/Player.log)

**Comment by peterhaneve** [comment]
_Relocate_ chores are not flagged by the base game as _Work_ chores, and thus can be performed by default during downtime, sleep time or any other time (if you start a new game, avoid building a rec room and set a schedule of all downtime slots, Duplicants will perform Relocate chores even without any mods active). Therefore, Rest for the Weary will not prevent them from being performed.

If you want Duplicants not to perform these chores, file a Klei Bug Report to classify Relocate chores as work chores (like Fetch and so forth).

**Comment by peterhaneve** [comment]
A temporary workaround has been applied to the latest version of Rest for the Weary to prevent these tasks from being started in Finish-Up time.
