### ISSUE TITLE
the mod appears to be broken [smart pumps]

### ISSUE THREAD

**Issue by tonimark** [peterhaneve/ONIMods#57]
after I updated some mods and loaded my saved game (saved without problems) the game encounters an error (as an error screen happened) it said that only the smart pumps mod was responsible. when I removed the mod the save loaded property without this error proving that is smart pump's fault
## Expected Behavior

the save would load without errors
## Current Behavior

after loading an error screen shows up :https://steamcommunity.com/sharedfiles/filedetails/?id=2110677827
## Mod Versions 
 1588804801 (what the mods.json said)
yes I use the subscription

yes I have tried 
## Steps to Reproduce

1.load the save
2.
3.
4.

## Output Log

[error log.txt](https://github.com/peterhaneve/ONIMods/files/4709636/error.log.txt)
the error log shows what the log of what the error screen said
[debug.log](https://github.com/peterhaneve/ONIMods/files/4709640/debug.log)
[output_log.txt](https://github.com/peterhaneve/ONIMods/files/4709641/output_log.txt)

the mod is broken

**Comment by peterhaneve** [comment]
This crash is due to **Mineral Processing** calling `GlobalResources.Instance()` too early. Move Mineral Processing to last in the mods screen order as is stated on its mod page, and Smart Pumps should work better.

**Comment by tonimark** [comment]
> This crash is due to **Mineral Processing** calling `GlobalResources.Instance()` too early. Move Mineral Processing to last in the mods screen order as is stated on its mod page, and Smart Pumps should work better.

i will try
