### ISSUE TITLE
Airlock door doesn't work if power grid is out/down

### ISSUE THREAD

**Issue by Draxial** [peterhaneve/ONIMods#58]
The airlock mod is incredible, thanks for it! I found a minor bug, when my base runs out of battery power, the airlock still has its internal power, but it doesn't works; my food is inside the airlock, so I constantly get "! food shortage" every time the power is out;

PS:About the airlock being inaccessible when the wire wasn't built first, suggestion: move the power connection to one of the corners instead of having it right in the middle

## Expected Behavior
When the power is out, the airlock should still work as it has internal power

## Current Behavior
When the power is out, the airlock doesn't works even having internal power

## Mod Versions
Steam subscription, tried force update already; 1.2

## Steps to Reproduce
1. Create airlock while having power
2. Cut the power to airlock when the airlock has full internal power

![image](https://user-images.githubusercontent.com/53184989/83834943-e640dc80-a6c5-11ea-8f37-d57d4298d874.png)

**Comment by peterhaneve** [comment]
This issue should be fixed by c2899b2.
