### ISSUE TITLE
Type selection menu could be better

### ISSUE THREAD

**Issue by NanakiPL** [peterhaneve/ONIMods#6]
Hey. First of all: great mod. I've been looking forward for this for a long time. There are things that works as mods, and things that should be in base game, this is base game material.

There's one thing though. The material selector you use isn't great for this use. I suspect it was easier to implement quickly and I wouldn't be surprised that what I'm writing here is already in the works :) The "slider" is very tedious to look for specific material when you have sooo many option available. And if you want to sweep a specific type, you need to basically repeat the search for each type (hopefully they're close to each other on the list).

What the sweep command needs is the menu you get for storage compactors, fridges, conveyor loaders etc. Apart from being easy to look for, you get the ability to select multiple materials and whole groups (multi-select part needs implementing ofc). Seep all the critter eggs, all the ores, all the diamonds and rust from the oil biome, and leave the garbage etc.

If there's a way to mod this ui element, a simple invert selection button would make "sweep everything except" a breeze too.

Cheers and again great job. I wish GitHub had an option to file something as an "idea" instead of "issue" so feel free to treat it like this and close this at your leisure. I won't get mad :)

**Comment by peterhaneve** [comment]
Part of the initial reason, as you may have guessed, to use the recipe menu was to limit sweeping to one type. Sweeping multiple types can be slow on performance.

Unfortunately, the recipe control does not allow bottles to be shown. The compactor tree control would in theory but it would require merging the bottler menu, edible menu, and solid menu.

**Comment by peterhaneve** [comment]
A quick hack allows bottles to be swept now with the current control. The compactor tree control unfortunately cannot be used, so it would have to be rewritten to be used here.

**Comment by NanakiPL** [comment]
Hmm. Maybe there's no need to merge these. Now you can select between "Sweep all" and "Sweep by type" to access the filter option. Selection over there could work. "Sweep solids by type" uses conveyor loader tree (includes foods), "Sweep bottles by type" uses bottle emptier tree and "Sweep canisters by type" uses canister emptier tree.

**Comment by jmucchiello** [comment]
What about changing the initial "Sweep All" or "Sweep by Type" menu so that it says 

Sweep All
Sweep consumables
sweep eggs
sweep consumables ore
etc
And then they have the left/right scrolling list of icons?

Also an All but X option would be nice too.

**Comment by peterhaneve** [comment]
All of these issues have been fixed in Sweep By Type 1.4 (ca8f9bc), now live on Steam.
