### ISSUE TITLE
Airlock Door vacuums out Vacuum.

### ISSUE THREAD

**Issue by Stormageddon01** [peterhaneve/ONIMods#60]
Airlock Doors from the mod of the same name will always spend time attempting to produce a vacuum (and use power), when there would be no gasses in it's interior.

Expected Behavior:
Dupe enters from side in vacuum. Airlock does not 'empty', as it would be empty (though that appears to not be simulated), and consumes no power. Opposite door opens and dupe goes through. Airlock empties in preparation for next operation.

Current Behavior:
Dupe enters from side in vacuum. Airlock 'empties', (appears to not be simulated), and consumes power. Opposite door opens and dupe goes through. Airlock empties in preparation for next operation.

Mod Versions:
Steam, no force Mod Updater. A massive amount of other mods were present.

Steps to Reproduce:
1. Build a door with one end opening into a gaseous environment, and the other end an environment comprised of Vacuum.
2. Have a Dupe attempt to travel from the Vacuum side to the gaseous side, with no other valid path.
3. Proceed to observe the behavior above.

Output Log:
Is this really necessary? I will try to give you one if asked. (I have no idea how.)

**Comment by peterhaneve** [comment]
As of version 1.4 (2aa77d7), Airlock Door will operate much faster in Vacuum and will scale the time taken to empty the Airlock to the pressure of the materials inside.
