### ISSUE TITLE
AirlockDoor feature request: Add an insulated version

### ISSUE THREAD

**Issue by alpe12** [peterhaneve/ONIMods#61]
I tried changing the Thermal Conductivity using the CustomizeBuildings mods and it didn't work.
So I'm requesting here.
Thanks.

**Comment by peterhaneve** [comment]
Customize Buildings will not affect the conductivity of an Airlock Door, as it uses a sim cell occupier like a regular Airlock which is not affected by the ThermalConductivity multiplier.

If strong thermal isolation is required, two Airlock Doors with a Vacuum between them will conduct little to no heat.

**Comment by alpe12** [comment]
> If strong thermal isolation is required, two Airlock Doors with a Vacuum between them will conduct little to no heat.

That would be way overkill.
Since theorically there is already a vacuum in the middle it should conduct very little heat, even considering the backplate.
