### ISSUE TITLE
AirlockDoor Door seems to be leaking gases.

### ISSUE THREAD

**Issue by jaydys** [peterhaneve/ONIMods#62]
When using the door with multiple gases on either or both sides small amounts of gas seep through.
## Expected Behavior
All gases should stay on their original side of the door.

## Current Behavior
Specifically I am sectioning off an enclosed room of chlorine from my base filled with O2 and CO2.
When Dupes move through the door I can see very small amounts of chlorine being released into my base.

## Mod Versions
Currently using the Steam version.  Did not install until most recent version so no updates to be done.

## Steps to Reproduce

1. Setup door between rooms with multiple gases on either or both sides.
2. Have dupes travel back and forth with heavy usage.
3. Watch gas overlay and see tiny amounts of one gas slipping to the opposite side of the door.

## Output Log
Not really a coding error but okay.
[output_log.txt](https://github.com/peterhaneve/ONIMods/files/4833183/output_log.txt)

And a screenshot of the result.
![AirlockDoorsLeak](https://user-images.githubusercontent.com/45528006/85778839-9bc0e780-b6e8-11ea-9058-666d3464c715.png)

Additional:  It seemed to be fine with vacuum on one side and gases on the other, but with gases on both sides there are leaks.
Maybe instead of actually pumping out gas, just block any gas movement through the doors and run the animation?  Probably make it easier.

I have tested this at least 10 times, but I will continue to test it.  I truly love this mod and it is VERY NEEDED!

**Comment by peterhaneve** [comment]
This issue is more likely due to the current bug (fixed in the testing branch) where Duplicants sometimes exhale carbon dioxide into the wrong location, which could teleport Chlorine through the door.

Try adding another tile above the door on the left.

**Comment by jaydys** [comment]
I will give this a try and let you know.

JP.

**Comment by jaydys** [comment]
I put overhangs on both sides of the door and played with heavy traffic and not even a tiny bit escaped through.
Thank you for the response.
![image](https://user-images.githubusercontent.com/45528006/85892877-54edf300-b7b7-11ea-863b-bee9cc395e5f.png)
