### ISSUE TITLE
ModUpdateDate crash upon use.

### ISSUE THREAD

**Issue by HyperWilson** [peterhaneve/ONIMods#63]
The game seems to immediately crash when trying to manually update a mod, the error within the output.log is as follows:

MissingMethodException: void ConfirmDialogScreen.PopupConfirmDialog(string,System.Action,System.Action,string,System.Action,string,string,string,UnityEngine.Sprite,bool)
  at PeterHan.ModUpdateDate.ModUpdateTask.TryUpdateMods (UnityEngine.GameObject _) [0x0010a] in <18410b13ed57488a9a6ba2bfe780b0f2>:0 
  at PeterHan.PLib.UI.PButton+<>c__DisplayClass14_0.<Build>b__0 () [0x0000a] in <18410b13ed57488a9a6ba2bfe780b0f2>:0 
  at KButton.SignalClick (KKeyCode btn) [0x00010] in <1dcc11867b524f7cb2488468843e982e>:0 
  at KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00069] in <1dcc11867b524f7cb2488468843e982e>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00008] in <cfe2f64a3dc9415eb325f322bb4ecd6a>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00070] in <cfe2f64a3dc9415eb325f322bb4ecd6a>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: <18410b13ed57488a9a6ba2bfe780b0f2> Line: 0)

-------------------------------------------------------------------------
This is displayed upon the crash screen
-------------------------------------------------------------------------

PeterHan.ModUpdateDate.ModUpdateTask.TryUpdateMods (UnityEngine.GameObject _) (at <18410b13ed57488a9a6ba2bfe780b0f2>:0)
PeterHan.PLib.UI.PButton+<>c__DisplayClass14_0.<Build>b__0 () (at <18410b13ed57488a9a6ba2bfe780b0f2>:0)
KButton.SignalClick (KKeyCode btn) (at <1dcc11867b524f7cb2488468843e982e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1dcc11867b524f7cb2488468843e982e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by honorgog** [comment]
This just happened to me as well.  Perhaps the latest patch blew something up.

**Comment by TroublesomeCorvid** [comment]
Having the same issue myself.  REALLY wish Klei gave us the option to roll-back patches until our favorite mods can catch up.

**Comment by peterhaneve** [comment]
The recent "hotfix" rewrote how Klei handles dialogs, causing Mod Updater to crash - but if Steam will not update Mod Updater due to caching or bugs in the distribution network, no workaround is possible to update through Steam.

For any users where Steam is still failing to serve the correct version, you must:

- Disable Mod Updater from Steam
- Install a [local copy](https://github.com/peterhaneve/ONIMods/releases/tag/ModsLatest)
- Update all outdated mods
- Uninstall the local copy
- Re-enable Mod Updater from Steam
