### ISSUE TITLE
Getting constant false possitives

### ISSUE THREAD

**Issue by jmucchiello** [peterhaneve/ONIMods#64]
Cookie is sleeping in his cot next a bunch of other dupes also sleeping in cots in the same room. Cookie is reported Confined.
[20:19:33.362] [1] [WARNING] [PLib/Claustrophobia] Cookie is now Confined!

I have the mod set to report only after 10 seconds.

This started happening with the Friday release that was just a small update: 420700

## Mod Versions
Latest steam version. Fully updated.
  {
      "label": {
        "distribution_platform": 1,
        "id": "1836997281",
        "version": **1588804122**,
        "title": "Claustrophobia - Stuck Duplicant Alert"
      },
      "status": 1,
      "enabled": true,
      "crash_count": 0,
      "reinstall_path": null
    },

## Output Log
There's nothing useful in the output log but here, I'll attach it.
[output_log.txt](https://github.com/peterhaneve/ONIMods/files/4909406/output_log.txt)

**Comment by peterhaneve** [comment]
Without a screenshot of your base it is difficult to be sure, but one common cause of false positives is bases with Duplicants confined to only one bedroom behind Atmo Suit docks. If all suits are occupied or charging, the Duplicant technically cannot path to any location outside of the room, causing false positives.

**Comment by jmucchiello** [comment]
I don't do that. I have a wide base with two exits, each with their own
docks. What commonly happens is someone take off their atmosuit and then go
idle right at the checkpoint. That causes the thing to go off all the time.
But Cookie sleeps in a room with 6 cots and 4 statues just off the central
ladder/firepole. The interior of the base is basically a big room with two
atmosuit exits, a few ranch rooms, 3 barracks, a single bathroom
(scheduling), and a great hall. Sometimes Cookie is at the grill, making
food and sudden the whistle blows and the confined alert pops up.

Only started happening after the 420700 update. I had to give up on the
base. It was unplayable. I'd send you the save file but I have 43 mods
running and it isn't worth messing around with turning most of them off to
see if it still works.
