### ISSUE TITLE
Configurable speed [Airlock Door]

### ISSUE THREAD

**Issue by Damntry** [peterhaneve/ONIMods#65]
Not really an issue, just a feature for your consideration.

Currently the whole functionality is very vanilla like and it looks like something Klei would actually add, but would it be possible to add a config option to speed the cycling process while the dupe is waiting to exit the airlock? It would make for a good middle ground between your mod and using something that simply makes all doors not leak gasses.

Regards.

**Comment by peterhaneve** [comment]
As of version 1.4 (2aa77d7), Airlock Door is now much faster in low pressure environments, and in general slightly faster than before for most reasonable base setups.
