### ISSUE TITLE
Smart Pumps Overlay 

### ISSUE THREAD

**Issue by eL-Du-de** [peterhaneve/ONIMods#67]
## Expected Behavior
Filtered Liquid Pump shows up in Liquid-Overlay

## Current Behavior
Filtered Liquid Pump shows up in Gas-Overlay

## Mod Versions
Steam-Version using Mod-Updater

## Steps to Reproduce

Just hit F6 or F7 while a Filtered Liquid Pump is on screen

**Comment by peterhaneve** [comment]
This issue has been fixed in 2aa77d7, but the Steam version will not be updated (as it is a cosmetic issue only) until some other reworks are done.
