### ISSUE TITLE
When Powered, Dupes cannot climb

### ISSUE THREAD

**Issue by KawaiiDouchebag** [peterhaneve/ONIMods#69]
## Expected Behavior
Dupes should be able to climb on top of the airlock at all times, assuming there is nothing blocking access to the top of the airlock such as a tile.

## Current Behavior
The airlock can be climbed on top of when it has not been powered, once it gets enough charge to allow a dupe inside it, dupes cannot walk on top of the airlock anymore, and sometimes (rarely) fall into it.

## Mod Versions

v1.4.0.0, steam subscription, yes.

## Steps to Reproduce
1. Place an airlock down
2. Place a tile three squares above the ground, next to the opposite side of the airlock
3. Have a dupe stand on that square
4. Power the airlock
5. When the airlock is powered that dupe is now stranded

## Output Log

There is no file in that folder.

**Comment by KawaiiDouchebag** [comment]
Issue placed in wrong section, Closing

**Comment by KawaiiDouchebag** [comment]
Issue is in correct section, i had not realized all mods shared the same issue section.
This issue is in relation to the "Airlock Door" mod.

**Comment by peterhaneve** [comment]
When Airlock Door is in operation, the middle of the door is technically not solid, but a Vacuum. Therefore, Duplicants cannot stand on that tile, preventing a Duplicant trapped on a single solid tile above either door from climbing down (Duplicants cannot climb down three tile ledges).

Doors which are out of power, to prevent path finding from passing through them, use a workaround by temporarily filling the middle cells with a solid material. Unfortunately this change is required to prevent Duplicants from standing idle waiting for an unpowered door to activate, and is the same procedure used by the Mechanized Airlock.
