### ISSUE TITLE
Claustrophobia "confined" alert

### ISSUE THREAD

**Issue by ethanleet** [peterhaneve/ONIMods#7]
Whenever I intentionally trap my newly hired interns inside the core base to run on hamster wheels, I keep getting confined warning. Can something be done about the criteria that defines being confined? E.g. dupes are not confined if they have access to food and bathroom etc.

**Comment by peterhaneve** [comment]
In b16d2531 (Claustrophobia 1.9) there is now an option in the Mods menu which, if selected, disables the _Confined_ alert for Duplicants which can access beds, mess tables (if available), and toilets. This option begins disabled by default for compatibility.
