### ISSUE TITLE
[Enhancement] AI Improvements: Sweeping

### ISSUE THREAD

**Issue by kaedys** [peterhaneve/ONIMods#70]
Not sure if this falls within scope of the AI Improvements mod, but I feel like it's the closest mod out there for this.

I've noticed that dupe AI is particularly bad when it comes to sweep tasks, especially when Proximity is enabled.  They select a sweep task properly based on priority (usually), by they completely ignore the priority on storage bins and instead will deliver the item to the closest storage bin that accepts that item _relative to the position they were at when they acquired the sweep task_.

If your dupe is in the middle of your base, and picks up a high-priority sweep out in the boonies, he/she will go and collect the item way out there, then walk all the way back to your base to deliver it, even if there's an equal or higher priority storage bin literally right next to the item being swept.

I'm not familiar with ONI's API capabilities, but if that's a piece of the AI that can be touched, it'd be nice if the AI for sweep commands could be adjusted so that the storage bin was selected by proximity to the swept item, rather than proximity to the dupe when they pick up the task.

**Comment by peterhaneve** [comment]
Storage tasks are generated by the destination of the item, not by the material chunk on the map. This is an important optimization in the base game, as Duplicants path to each possible chore every update, and pathfinding to every chunk would greatly slow down the game. Therefore, the Duplicant choosing a storage destination very close to their current location makes sense.

Changing the behavior to choose a storage bin next to the item to be picked up would probably cause a large performance decrease. It might be in scope for Efficient Supply, but pathfinding is slow as it is, and major improvements would have to be made to the rest of the game before making this improvement.
