### ISSUE TITLE
Hitch when clicking "sweep"

### ISSUE THREAD

**Issue by kaedys** [peterhaneve/ONIMods#72]
## Expected Behavior
Love the new scrolling behavior in today's update, but I'm now getting a pretty noticeable hitch or pause both when I click to select and click to unselect the sweep tool.  It's approximately a half second in length, and occurs every time I click the button.  It does not occur on any other tools.

The expected behavior is, of course, no unexpected hitching.

## Current Behavior
☝️ 

## Mod Versions
Steam subscription, updated via Mod Manager this morning to today's release (12 September)

## Steps to Reproduce
I'm not sure if there's another mod interaction going on here, because I have quite a few installed an enabled.  For me, however, it's as simple as having the mod active and clicking the sweep button.  It happens on every click, both to activate and deactivate the tool.

## Output Log
Output log attached, but nothing is showing up in it that seems relevant.  I also have the debug window mod running, but nothing is showing up in it during this hitch.

[output_log.txt](https://github.com/peterhaneve/ONIMods/files/5213066/output_log.txt)

**Comment by peterhaneve** [comment]
Removing unnecessary layout groups in d3e78ff reduced the load time of Sweep by Type's dialog from 140ms to 56ms!
