### ISSUE TITLE
Polymer Press issue caused by Stock Bug Fix Mod

### ISSUE THREAD

**Issue by PsychoDad9999** [peterhaneve/ONIMods#74]
## Issue

If the Stock Bug Fix Mod is enabled and there are solid tiles placed left of the polymer press, the plastic is trapped inside of the solid block, instead of falling to the ground.

## Mod Versions

Steam Version 2.8.0.0

## Steps to Reproduce

1. Place some solid tiles next to the polymer press (see image below).
2. Plastic ends up in the top left tile

![plastic](https://user-images.githubusercontent.com/52836134/93454522-6983e800-f8db-11ea-94f5-15986de6f8d8.jpg)

Plastic ends up in the tile with the burried object
![stockbugfixbug2](https://user-images.githubusercontent.com/52836134/93455910-422e1a80-f8dd-11ea-8da2-c7157c9afe10.gif)

**Comment by peterhaneve** [comment]
This issue exists in the stock polymer press without any mods if it is facing to the right:

![image](https://user-images.githubusercontent.com/29011570/93660668-0fcc0c80-fa06-11ea-9bee-23c489010aca.png)

Stock Bug Fix merely aims to make the Polymer Press symmetrical, so it would not be unexpected for the plastic to end up in the tile shown in your image.
