### ISSUE TITLE
Behavior of dupes waiting for sinks + Suggestion.

### ISSUE THREAD

**Issue by nirahiel** [peterhaneve/ONIMods#75]
Hi, could you make a queue for showers ?
Right now I have 4 showers at the end of a barracks of 12 beds and only 4 dupes can shower at a time, the others just leave, and while they come back to shower when the showers are free, some of them go to the hamster wheels and don't stop until after the shower schedule is over. If I could get them to wait here that'd be awesome.
(Waiting at the first shower until one is free would be the best)
If that's not possible, could you make a shower output green signal when it's free and red when it's in use or about to be used (reserved) ?

While I'm talking about it, having the dupes wait at the first sink of a chain would be best, when work is over and dupes come back to the base they often have to wash hands and the first X dupes use the X available sinks, then all the remaining dupes pile up at the last sink and when the first X dupes are done, all the sinks except the last one become unused, wasting a lot of time.

**Comment by peterhaneve** [comment]
Showers do not register the right type of reactable to require pass-by use in the first place, and they take much longer to complete than sinks. Queuing for showers is outside the scope of Queue for Sinks but could be made in a separate mod.
