### ISSUE TITLE
Mod manager reports an update every day

### ISSUE THREAD

**Issue by MrEManGit** [peterhaneve/ONIMods#76]
## Expected Behavior

All other mods only update when there is an update.

## Current Behavior

Every day, Mod Manager (an ONI mod - https://steamcommunity.com/sharedfiles/filedetails/?id=1843965353&searchtext=mod+manager) reports that Sweep By Type has been updated and requests to download and restart ONI.  I don't think Sweep By Type is actually changed every day, but there must be something that tricks Mod Manager into thinking it is updated.  I can ignore the dialog in Mod Manager, but that defeats the purpose of Mod Manager to let me know when there are changes to my mods.

## Steps to Reproduce

1. Start the game.  It (the issue above) happens once every day.
2.
3.
4.

**Comment by peterhaneve** [comment]
It is likely that Sweep By Type's local files are actually outdated, but Mod Manager does not correctly update mods in some circumstances due to Steam caching. Use Mod Updater (https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) instead.
