### ISSUE TITLE
Feature Request: Seed items not composting

### ISSUE THREAD

**Issue by fleeting-aardvark** [peterhaneve/ONIMods#77]
I would like to make a feature request of what appears to be a bug in the standard operation of Oxygen Not Included.

## Expected Behavior

Seeds should be picked up to be composted.

## Current Behavior

When seeds {usually meal lice and waterweed} are selected to be composted, then duplicants do not ever pick up the seeds to compost them.

## Mod Versions

Steam, and mod is up to date.

## Steps to Reproduce

1. Select a seed to compost.
2. Watch duplicants ignore seeds forever.

**Comment by peterhaneve** [comment]
Take a look at the errands list on the compost - is there an errand scheduled to deliver the seeds? Composting is considered a farming errand, which some players may accidentally block off to farming priority Duplicants due to germ spread.

**Comment by fleeting-aardvark** [comment]
I was under the impression that composting was a supply request.  I will check this and report back.

**Comment by fleeting-aardvark** [comment]
Seeds are still not being composted.  I have several "farmers" with the farming skill as the highest priority.  When setting the seed to compost, the description says it is based on the "compost" skill.  Yet in the priorities, there is no "compost" skill.  While the "compost" skill may imply farming, it does not appear to be working off of farming. On the compost itself, it says it requires "farming" or the "supply" skill.

**Comment by peterhaneve** [comment]
I cannot reproduce the issue. See if storing items is on the errands list for the compost. If it is blank, this is a different stock game bug that is unfortunately outside of Stock Bug Fix's ability to easily fix, as it can affect many types of chores.
![image](https://user-images.githubusercontent.com/29011570/98607699-9088e580-229e-11eb-9f74-94ede173baa2.png)

**Comment by fleeting-aardvark** [comment]
The reason why this cannot be easily reproduced is actually because the "problem" is not easily identified. I believe I have identified the problem now and it is not a bug.  It is that seeds are not the highest priority to be composted when there is not enough 'locations' for the items to be composted.  After starting a separate game and having more than one compost pile, seeds now properly compost.

My apologies for wasting your time.
