### ISSUE TITLE
Configuration option to turn off fishrelease bug.

### ISSUE THREAD

**Issue by fleeting-aardvark** [peterhaneve/ONIMods#78]
I would like to have an option to turn off the fish release bug.  Either in the configuration file or possibly on the 'building' itself.

## Expected Behavior

Configurable option to turn off specific stock bug fixes.

## Current Behavior

Only configuration option for "FixOverheat" bug.  No configuration option for other bug fixes.

## Mod Versions

Steam, mod is up to date.

## Steps to Reproduce

1. Load up Oxygen Not included.
2. Select this mods config button.
3. See only "Fix Overheat" bug option.

**Comment by peterhaneve** [comment]
Why do you want this bug fix disabled? Does it cause crashes, or conflict with another mod?

**Comment by fleeting-aardvark** [comment]
This bug fix does not cause crashes and does not conflict with any other mod.  However it does prevent duplicants from releasing more fish into a holding tank for all of the fish when the amount of fish reaches 20.  It requires a workaround to have the fish be released into a separate room on top of a mesh door just to fall into my fish holding tank.  While I appreciate the fix, I like the old behavior of this bug fix.
