### ISSUE TITLE
Feature Request: Autosweeper and Oxidizer Tank Bug

### ISSUE THREAD

**Issue by fleeting-aardvark** [peterhaneve/ONIMods#79]
Auto sweeper keeps visually moving very small amounts of oxidizer even when oxidizer tank is already at set amount.

## Expected Behavior

The auto sweeper should move only the correct amount then stop.

## Current Behavior

As description says, the auto sweeper keeps moving very small amounts of oxidizer. Though the tank is not changing amounts.

## Mod Versions

Steam, currently up to date.

## Steps to Reproduce

1. Create oxidizer tank on rocket.
2. Have auto sweeper move oxylite to tank to fill it up.
3. Wait for full / near full condition and watch auto sweeper continue sweeping small amounts.

Reported bug by someone else on klie's site:
https://forums.kleientertainment.com/klei-bug-tracker/oni/auto-sweeper-oxylite-to-oxidizer-tank-loop-bug-r21133/

**Comment by peterhaneve** [comment]
Does this issue only reproduce with one of the mods in this repository installed? If it is a vanilla bug, consider making a Klei report, unless you want a feature request of Stock Bug Fix.

**Comment by fleeting-aardvark** [comment]
It is a vanilla bug as reported on klei's forum.  However, they have not fixed it yet.  That bug was reported over a year ago and is still happening.
