### ISSUE TITLE
Make AirLockDoor close only on one side 

### ISSUE THREAD

**Issue by TrabacchinLuigi** [peterhaneve/ONIMods#80]
The airlock door does not need to be vacuumed until a duplicant need to pass through, one side could stay open until a duplicant reach the middle from the open side, or the closed side.
i'm not sure how the door is actually vacuumed, but the middle section can be emptied to the side the last section of the door closed.

**Comment by peterhaneve** [comment]
While a decent suggestion, making this change now would be incompatible with existing bases. Many existing users of this mod may not be expecting the center of the door to be filled with liquids or gases, and they would have no opportunity to choose the rotation of the door in this scenario.
