### ISSUE TITLE
Request for new mod: Remove temperature clamping on construction

### ISSUE THREAD

**Issue by aslakg** [peterhaneve/ONIMods#81]
Not sure if possible to do, but I've been looking for a mod that removes the clamping of temperatures when building tiles and buildings. If I'm building with 200 degree rock, I'd like the tile to be 200 degrees, instead of being artificially clamped to a maximum. This would make it more important to cool building materials for normal construction.
It would also allow one to make changes to f.ex. a hot steam room without cooling it down and losing heat.
Or build in a cold zone without heating it up, if one has cold materials there. F.ex. in a cold biome if you dig up granite, then place it as a tile, it'll start melting snow. Even though it was freezing granite in the first place.
I have no idea if the code that does this is open to modding, but would love this if possible.

**Comment by peterhaneve** [comment]
Please consider making requests for completely new mods on the [Klei modding forum](https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/) so that they are visible to all modders.
