### ISSUE TITLE
Feature Request: Configuration option for fish release

### ISSUE THREAD

**Issue by fleeting-aardvark** [peterhaneve/ONIMods#82]
There is not an option to turn off the fish release bug fix.

## Expected Behavior
A configurable option to turn off the specific fish release bug fixe.

## Current Behavior
Only configuration option for "FixOverheat" bug. No configuration option for other bug fixes.

## Mod Versions
Steam, mod is up to date

## Steps to Reproduce
1. Load up Oxygen Not included with mod enabled.
2. Select this mods config button.
3. See only "Fix Overheat" bug option.

## Discussion
This bug fix does not cause crashes and does not conflict with any other mod. However it does prevent duplicants from releasing more fish into a holding tank for all of the fish when the amount of fish reaches 20. It requires a workaround to have the fish be released into a separate room on top of a mesh door just to fall into my fish holding tank. While I appreciate the fix, I like the old behavior of this bug fix.

**Comment by peterhaneve** [comment]
Instead of adding an option for this bug fix, consider using the mod [No Sensor Limits](https://steamcommunity.com/sharedfiles/filedetails/?id=2277619848), which allows the upper critter limit for fish releases to be increased.

**Comment by fleeting-aardvark** [comment]
Seems to be a bit disingenuous to provide fixes for many bugs but only be able to turn off one of them.  And then you want me to use another mod.

That does not fix the feature request.  That just puts it off on someone else.
