### ISSUE TITLE
Duplicants get stuck in the door spot for the airlock.

### ISSUE THREAD

**Issue by A-p-o-t-h-i-c-o-n** [peterhaneve/ONIMods#84]
Whenever duplicants try going through the airlock, they will get stuck on the spot that the door is on the side they were entering from. When this happens they just stand there forever ignoring any task. They wont sleep, "make a mess", or anything. Reloading the game gets them unstuck but they just try going through again and get re-stuck.

## Expected Behavior
They should walk into the middle of the airlock.

## Current Behavior
They get stuck in the doorway of the side they were entering from.

## Mod Versions
I am using the steam subscription version, and the mod has not had any updates since I've installed it.

## Steps to Reproduce

1. Place the door
2. Power it
3. Try to move a duplicant from one side to the other via tasks or the manual moving thing.

## Output Log
[output_log.txt](https://github.com/peterhaneve/ONIMods/files/5505210/output_log.txt)

**Comment by peterhaneve** [comment]
I am unable to reproduce this issue. Do you have a save file that can reliably get Duplicants stuck in this spot?
