### ISSUE TITLE
Got error with queue

### ISSUE THREAD

**Issue by UlyanaLeyana** [peterhaneve/ONIMods#91]
## Expected Behavior

I think they should stop washing their hands over and over again.

## Current Behavior

Got error. I think this is due to the fact that they get stuck near the sink. They just washed their hands over and over. I saw it 2 times, but I'm not sure why I got this error.

## Mod Versions

Steam subscription, Subscribed today.

## Steps to Reproduce

1. I think I need a sink with pipes and about 8-10 duplicates. With primitive sink everything was okay.
2.
3.
4.

## Output Log

NullReferenceException: Object reference not set to an instance of an object

PeterHan.QueueForSinks.SinkCheckpoint.MustStop (UnityEngine.GameObject reactor, System.Single direction) (at <45f9481edc8849b8bf0692c06985b2c8>:0)
PeterHan.QueueForSinks.WorkCheckpoint`1+WorkCheckpointReactable[T].MustStop (UnityEngine.GameObject dupe, System.Single x) (at <45f9481edc8849b8bf0692c06985b2c8>:0)
PeterHan.QueueForSinks.WorkCheckpoint`1+WorkCheckpointReactable[T].Update (System.Single dt) (at <45f9481edc8849b8bf0692c06985b2c8>:0)
ReactionMonitor.<InitializeStates>b__4_2 (ReactionMonitor+Instance smi, System.Single dt) (at <1c58b1f98f5849baa9083bfd5185b144>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <f30d3c85d1f64155aa0dc6c7adb0d1eb>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <f30d3c85d1f64155aa0dc6c7adb0d1eb>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <f30d3c85d1f64155aa0dc6c7adb0d1eb>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <f30d3c85d1f64155aa0dc6c7adb0d1eb>:0)
Game.SimEveryTick (System.Single dt) (at <1c58b1f98f5849baa9083bfd5185b144>:0)
Game.Update () (at <1c58b1f98f5849baa9083bfd5185b144>:0)

**Comment by peterhaneve** [comment]
The crash should be fixed by a81335c1, but the Steam mod has not yet been updated due to the holidays.
