### ISSUE TITLE
 “Thermal Tooltips” Chinese traslation

### ISSUE THREAD

**Issue by Ventulus-lab** [peterhaneve/ONIMods#95]
I have translated “Thermal Tooltips” po file to Chinese.Please put it in the mod, so that Chinese players can check the card easier
[zh.po.zip](https://github.com/peterhaneve/ONIMods/files/5753055/zh.po.zip)

**Comment by peterhaneve** [comment]
Thank you for contributing the translation! I have added this translation to the code base in 1dcfa0a, but due to the holidays the Steam mod may not be updated for a few days.
