### ISSUE TITLE
ModUpdater not working with CS-442712

### ISSUE THREAD

**Issue by Dirk-Manderin** [peterhaneve/ONIMods#97]
## Expected Behavior
Mod should load

## Current Behavior
Enable mod in ONI and restart.  After the game restarts, I get a prompt that the mod failed to load and do another restart.  After second restart game loads but ModUpdater is disabled.

## Mod Versions
Using Epic version and local folder

## Steps to Reproduce

1. Enable mod in ONI and restart.
2. After the game restarts, I get a prompt that the mod failed to load and do another restart.
3. After second restart game loads but ModUpdater is disabled.
4.

## Output Log
There is no output log file in that location.

**Comment by peterhaneve** [comment]
Mod Updater does not work with the Epic Games Store version of Oxygen Not Included, as it uses the currently logged in Steam Workshop user to download mods without infringing on the Steam or Klei EULA. As the Epic Games Store does not yet distribute mods, EGS uses will need to check mod authors' GitHub websites for updated versions.
